/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.xpos.gui;

import com.xpos.commons.SystemLogger;
import com.xpos.database.DbConnect;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;

/**
 *
 * @author Jamit
 */
public class EmpPosition extends javax.swing.JPanel {

    DefaultTableModel tablemodel;
    DateTimeFormatter defaultDateFormat = DateTimeFormatter.ofPattern("yyyy-MM-dd");

    private static Logger log;
    int empPosId;

    /**
     * Creates new form EmpPosition
     */
    public EmpPosition() {
        initComponents();
        SystemLogger.initLogger();
        log = Logger.getLogger(EmpPosition.class);
        log.info("employee position running start...");
        fillEmpPosTable(null);
    }

    public void clearEmpPosPanel() {
        log.info("clear employee position panel");
        empPosSearch.setText("");
        empPosName.setText("");
        empPosPerSale.setSelected(false);
        empPosPerPurchase.setSelected(false);
        empPosPerReturn.setSelected(false);
        empPosPerCustomer.setSelected(false);
        empPosPerSupplier.setSelected(false);
        empPosPerEmployee.setSelected(false);
        empPosPerUserPosition.setSelected(false);
        empPosPerUserProfile.setSelected(false);
        empPosPerProducts.setSelected(false);
        empPosPerInvoice.setSelected(false);
        empPosPerXIncome.setSelected(false);
        empPosPerXCost.setSelected(false);
        empPosPerReport.setSelected(false);
        fillEmpPosTable(null);
    }

    public void fillEmpPosTable(String query) {
        log.info("fill customer table, query : " + query);
        tablemodel = (DefaultTableModel) empPosTable.getModel();
        tablemodel.setRowCount(0);
        if (query == null) {
            log.info("query null then assigning query");
            query = "select * from employeeposition where status=1";
        }
        try {
            log.info("executing query");
            ResultSet rs = DbConnect.getFromDB(query);
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getInt("Id"));
                v.add(rs.getString("PositionName"));
                v.add(rs.getBoolean("Sale") ? "Allow" : "Deny");
                v.add(rs.getBoolean("Purchase") ? "Allow" : "Deny");
                v.add(rs.getBoolean("Return") ? "Allow" : "Deny");
                v.add(rs.getBoolean("Customer") ? "Allow" : "Deny");
                v.add(rs.getBoolean("Supplier") ? "Allow" : "Deny");
                v.add(rs.getBoolean("Employee") ? "Allow" : "Deny");
                v.add(rs.getBoolean("UserPosition") ? "Allow" : "Deny");
                v.add(rs.getBoolean("UserProfile") ? "Allow" : "Deny");
                v.add(rs.getBoolean("Products") ? "Allow" : "Deny");
                v.add(rs.getBoolean("Invoice") ? "Allow" : "Deny");
                v.add(rs.getBoolean("ExIncome") ? "Allow" : "Deny");
                v.add(rs.getBoolean("ExCost") ? "Allow" : "Deny");
                v.add(rs.getBoolean("Report") ? "Allow" : "Deny");

                tablemodel.addRow(v);
            }
            log.info("table filled with data");
        } catch (SQLException e) {
            log.error("table filling failed", e);
        } catch (ClassNotFoundException e) {
            log.error("table filling failed", e);
        } catch (Exception e) {
            log.error("table filling failed", e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        empPosName = new app.bolivia.swing.JCTextField();
        empPosButInsert = new javax.swing.JButton();
        empPosButEdit = new javax.swing.JButton();
        empPosButDelete = new javax.swing.JButton();
        empPosButCancel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        empPosPerSale = new javax.swing.JCheckBox();
        empPosPerPurchase = new javax.swing.JCheckBox();
        empPosPerUserPosition = new javax.swing.JCheckBox();
        empPosPerUserProfile = new javax.swing.JCheckBox();
        empPosPerProducts = new javax.swing.JCheckBox();
        empPosPerInvoice = new javax.swing.JCheckBox();
        empPosPerXIncome = new javax.swing.JCheckBox();
        empPosPerXCost = new javax.swing.JCheckBox();
        empPosPerReport = new javax.swing.JCheckBox();
        empPosPerEmployee = new javax.swing.JCheckBox();
        empPosPerReturn = new javax.swing.JCheckBox();
        empPosPerCustomer = new javax.swing.JCheckBox();
        empPosPerSupplier = new javax.swing.JCheckBox();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        empPosTable = new rojeru_san.complementos.RSTableMetro();
        empPosSearch = new app.bolivia.swing.JCTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setBackground(new java.awt.Color(26, 140, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("EMP POSITIONS");
        jLabel8.setOpaque(true);
        jLabel8.setPreferredSize(new java.awt.Dimension(150, 22));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        empPosName.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        empPosName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        empPosName.setPhColor(new java.awt.Color(0, 51, 255));
        empPosName.setPlaceholder("Name");
        empPosName.setPreferredSize(new java.awt.Dimension(200, 30));

        empPosButInsert.setBackground(new java.awt.Color(0, 60, 128));
        empPosButInsert.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        empPosButInsert.setForeground(new java.awt.Color(255, 255, 255));
        empPosButInsert.setText("INSERT");
        empPosButInsert.setBorder(null);
        empPosButInsert.setFocusPainted(false);
        empPosButInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empPosButInsertActionPerformed(evt);
            }
        });

        empPosButEdit.setBackground(new java.awt.Color(0, 60, 128));
        empPosButEdit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        empPosButEdit.setForeground(new java.awt.Color(255, 255, 255));
        empPosButEdit.setText("EDIT");
        empPosButEdit.setBorder(null);
        empPosButEdit.setFocusPainted(false);
        empPosButEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empPosButEditActionPerformed(evt);
            }
        });

        empPosButDelete.setBackground(new java.awt.Color(0, 60, 128));
        empPosButDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        empPosButDelete.setForeground(new java.awt.Color(255, 255, 255));
        empPosButDelete.setText("DELETE");
        empPosButDelete.setBorder(null);
        empPosButDelete.setFocusPainted(false);
        empPosButDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empPosButDeleteActionPerformed(evt);
            }
        });

        empPosButCancel.setBackground(new java.awt.Color(0, 60, 128));
        empPosButCancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        empPosButCancel.setForeground(new java.awt.Color(255, 255, 255));
        empPosButCancel.setText("CANCEL");
        empPosButCancel.setBorder(null);
        empPosButCancel.setFocusPainted(false);
        empPosButCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empPosButCancelActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Access Permission", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N

        empPosPerSale.setBackground(new java.awt.Color(255, 255, 255));
        empPosPerSale.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        empPosPerSale.setForeground(new java.awt.Color(26, 140, 255));
        empPosPerSale.setText("Sale");

        empPosPerPurchase.setBackground(new java.awt.Color(255, 255, 255));
        empPosPerPurchase.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        empPosPerPurchase.setForeground(new java.awt.Color(26, 140, 255));
        empPosPerPurchase.setText("Purchase");

        empPosPerUserPosition.setBackground(new java.awt.Color(255, 255, 255));
        empPosPerUserPosition.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        empPosPerUserPosition.setForeground(new java.awt.Color(26, 140, 255));
        empPosPerUserPosition.setText("User Position");

        empPosPerUserProfile.setBackground(new java.awt.Color(255, 255, 255));
        empPosPerUserProfile.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        empPosPerUserProfile.setForeground(new java.awt.Color(26, 140, 255));
        empPosPerUserProfile.setText("User Profile");

        empPosPerProducts.setBackground(new java.awt.Color(255, 255, 255));
        empPosPerProducts.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        empPosPerProducts.setForeground(new java.awt.Color(26, 140, 255));
        empPosPerProducts.setText("Products");
        empPosPerProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empPosPerProductsActionPerformed(evt);
            }
        });

        empPosPerInvoice.setBackground(new java.awt.Color(255, 255, 255));
        empPosPerInvoice.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        empPosPerInvoice.setForeground(new java.awt.Color(26, 140, 255));
        empPosPerInvoice.setText("Invoice");

        empPosPerXIncome.setBackground(new java.awt.Color(255, 255, 255));
        empPosPerXIncome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        empPosPerXIncome.setForeground(new java.awt.Color(26, 140, 255));
        empPosPerXIncome.setText("Extra Income");

        empPosPerXCost.setBackground(new java.awt.Color(255, 255, 255));
        empPosPerXCost.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        empPosPerXCost.setForeground(new java.awt.Color(26, 140, 255));
        empPosPerXCost.setText("Extra Cost");

        empPosPerReport.setBackground(new java.awt.Color(255, 255, 255));
        empPosPerReport.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        empPosPerReport.setForeground(new java.awt.Color(26, 140, 255));
        empPosPerReport.setText("Report");

        empPosPerEmployee.setBackground(new java.awt.Color(255, 255, 255));
        empPosPerEmployee.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        empPosPerEmployee.setForeground(new java.awt.Color(26, 140, 255));
        empPosPerEmployee.setText("Employee");

        empPosPerReturn.setBackground(new java.awt.Color(255, 255, 255));
        empPosPerReturn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        empPosPerReturn.setForeground(new java.awt.Color(26, 140, 255));
        empPosPerReturn.setText("Return");

        empPosPerCustomer.setBackground(new java.awt.Color(255, 255, 255));
        empPosPerCustomer.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        empPosPerCustomer.setForeground(new java.awt.Color(26, 140, 255));
        empPosPerCustomer.setText("Customer");

        empPosPerSupplier.setBackground(new java.awt.Color(255, 255, 255));
        empPosPerSupplier.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        empPosPerSupplier.setForeground(new java.awt.Color(26, 140, 255));
        empPosPerSupplier.setText("Supplier");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(empPosPerReport)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(empPosPerSale)
                            .addComponent(empPosPerReturn)
                            .addComponent(empPosPerSupplier)
                            .addComponent(empPosPerUserPosition)
                            .addComponent(empPosPerProducts)
                            .addComponent(empPosPerXIncome))
                        .addGap(102, 102, 102)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(empPosPerXCost)
                            .addComponent(empPosPerInvoice)
                            .addComponent(empPosPerUserProfile)
                            .addComponent(empPosPerEmployee)
                            .addComponent(empPosPerCustomer)
                            .addComponent(empPosPerPurchase))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empPosPerSale)
                    .addComponent(empPosPerPurchase))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empPosPerReturn)
                    .addComponent(empPosPerCustomer))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empPosPerSupplier)
                    .addComponent(empPosPerEmployee))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empPosPerUserPosition)
                    .addComponent(empPosPerUserProfile))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empPosPerProducts)
                    .addComponent(empPosPerInvoice))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empPosPerXIncome)
                    .addComponent(empPosPerXCost))
                .addGap(29, 29, 29)
                .addComponent(empPosPerReport)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(empPosName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel13Layout.createSequentialGroup()
                        .addComponent(empPosButInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(empPosButEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(empPosButDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(empPosButCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(empPosName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empPosButInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empPosButEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empPosButDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empPosButCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));

        empPosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Sale", "Purchase", "Return", "Customer", "Supplier", "Employee", "User Position", "User Profile", "Products", "Invoice", "Extra Income", "Extra Cost", "Report"
            }
        ));
        empPosTable.setColorBackgoundHead(new java.awt.Color(26, 140, 255));
        empPosTable.setFuenteHead(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        empPosTable.setRowHeight(25);
        empPosTable.setRowMargin(0);
        empPosTable.setSelectionBackground(new java.awt.Color(0, 60, 128));
        empPosTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empPosTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(empPosTable);

        empPosSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        empPosSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        empPosSearch.setPhColor(new java.awt.Color(0, 51, 255));
        empPosSearch.setPlaceholder("Search");
        empPosSearch.setPreferredSize(new java.awt.Dimension(200, 30));
        empPosSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                empPosSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(empPosSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(empPosSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void empPosButInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empPosButInsertActionPerformed
        //log.info("user pressed insert button");
        String name = empPosName.getText();
        boolean salePerm = empPosPerSale.isSelected();
        boolean purchasePerm = empPosPerPurchase.isSelected();
        boolean returnPerm = empPosPerReturn.isSelected();
        boolean customerPerm = empPosPerCustomer.isSelected();
        boolean supplierPerm = empPosPerSupplier.isSelected();
        boolean employeePerm = empPosPerEmployee.isSelected();
        boolean userPosPerm = empPosPerUserPosition.isSelected();
        boolean userProfPerm = empPosPerUserProfile.isSelected();
        boolean productsPerm = empPosPerProducts.isSelected();
        boolean invoicePerm = empPosPerInvoice.isSelected();
        boolean exIncomePerm = empPosPerXIncome.isSelected();
        boolean exCostPerm = empPosPerXCost.isSelected();
        boolean reportPerm = empPosPerReport.isSelected();

        String query = "INSERT INTO `employeeposition`(`PositionName`, `Sale`, "
                + "`Purchase`, `Return`, `Customer`, `Supplier`, `Employee`, "
                + "`UserPosition`, `UserProfile`, `Products`, `ExIncome`, "
                + "`ExCost`, `Invoice`, `Report`) VALUES ('" + name + "'," + salePerm + "," + purchasePerm
                + "," + returnPerm + "," + customerPerm + "," + supplierPerm + "," + employeePerm
                + "," + userPosPerm + "," + userProfPerm + "," + productsPerm + "," + exIncomePerm
                + "," + exCostPerm + "," + invoicePerm + "," + reportPerm + ")";

        try {
            DbConnect.pushToDB(query);
            clearEmpPosPanel();
            log.error("executing query");
        } catch (SQLException e) {
            log.error("data insert failed", e);
        } catch (ClassNotFoundException e) {
            log.error("data insert failed", e);
        } catch (Exception e) {
            log.error("data insert failed", e);
        }
    }//GEN-LAST:event_empPosButInsertActionPerformed

    private void empPosButEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empPosButEditActionPerformed
        //log.info("user pressed edit button");
        String name = empPosName.getText().toString();
        boolean salePerm = empPosPerSale.isSelected();
        boolean purchasePerm = empPosPerPurchase.isSelected();
        boolean returnPerm = empPosPerReturn.isSelected();
        boolean customerPerm = empPosPerCustomer.isSelected();
        boolean supplierPerm = empPosPerSupplier.isSelected();
        boolean employeePerm = empPosPerEmployee.isSelected();
        boolean userPosPerm = empPosPerUserPosition.isSelected();
        boolean userProfPerm = empPosPerUserProfile.isSelected();
        boolean productsPerm = empPosPerProducts.isSelected();
        boolean invoicePerm = empPosPerInvoice.isSelected();
        boolean exIncomePerm = empPosPerXIncome.isSelected();
        boolean exCostPerm = empPosPerXCost.isSelected();
        boolean reportPerm = empPosPerReport.isSelected();

        String query = "UPDATE `employeeposition` SET `PositionName`='" + name + "',`Sale`=" + salePerm
                + ",`Purchase`=" + purchasePerm + ",`Return`=" + returnPerm + ",`Customer`=" + customerPerm
                + ",`Supplier`=" + supplierPerm + ",`Employee`=" + employeePerm + ",`UserPosition`=" + userPosPerm
                + ",`UserProfile`=" + userProfPerm + ",`Products`=" + productsPerm + ",`ExIncome`=" + exIncomePerm
                + ",`ExCost`=" + exCostPerm + ",`Invoice`=" + invoicePerm + ",`Report`=" + reportPerm + " WHERE `Id`=" + empPosId;

        try {
            DbConnect.pushToDB(query);
            clearEmpPosPanel();
            log.error("executing query");
        } catch (SQLException e) {
            log.error("data edit failed", e);
        } catch (ClassNotFoundException e) {
            log.error("data edit failed", e);
        } catch (Exception e) {
            log.error("data edit failed", e);
        }
    }//GEN-LAST:event_empPosButEditActionPerformed

    private void empPosButDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empPosButDeleteActionPerformed
        log.error("user presses delete button");
        String query = "UPDATE `employeeposition` SET `Status`=0 WHERE `Id`=" + empPosId;
        try {
            DbConnect.pushToDB(query);
            clearEmpPosPanel();
            log.error("executing query");
        } catch (SQLException e) {
            log.error("data delete failed", e);
        } catch (ClassNotFoundException e) {
            log.error("data delete failed", e);
        } catch (Exception e) {
            log.error("data delete failed", e);
        }
    }//GEN-LAST:event_empPosButDeleteActionPerformed

    private void empPosButCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empPosButCancelActionPerformed
        clearEmpPosPanel();
    }//GEN-LAST:event_empPosButCancelActionPerformed

    private void empPosPerProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empPosPerProductsActionPerformed
        //TODO add your handling code here:
    }//GEN-LAST:event_empPosPerProductsActionPerformed

    private void empPosTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empPosTableMouseClicked
        log.info("user clicked table row");
        int selectedRow = empPosTable.getSelectedRow();
        empPosId = Integer.parseInt(empPosTable.getValueAt(selectedRow, 0).toString());
        String posName = empPosTable.getValueAt(selectedRow, 1).toString();
        boolean salePerm = empPosTable.getValueAt(selectedRow, 2).toString().equals("Allow");
        boolean purchasePerm = empPosTable.getValueAt(selectedRow, 3).toString().equals("Allow");
        boolean returnPerm = empPosTable.getValueAt(selectedRow, 4).toString().equals("Allow");
        boolean customerPerm = empPosTable.getValueAt(selectedRow, 5).toString().equals("Allow");
        boolean supplierPerm = empPosTable.getValueAt(selectedRow, 6).toString().equals("Allow");
        boolean employeePerm = empPosTable.getValueAt(selectedRow, 7).toString().equals("Allow");
        boolean userPosPerm = empPosTable.getValueAt(selectedRow, 8).toString().equals("Allow");
        boolean userProfPerm = empPosTable.getValueAt(selectedRow, 9).toString().equals("Allow");
        boolean productPerm = empPosTable.getValueAt(selectedRow, 10).toString().equals("Allow");
        boolean invoicePerm = empPosTable.getValueAt(selectedRow, 11).toString().equals("Allow");
        boolean xIncomePerm = empPosTable.getValueAt(selectedRow, 12).toString().equals("Allow");
        boolean xCostPerm = empPosTable.getValueAt(selectedRow, 13).toString().equals("Allow");
        boolean reportPerm = empPosTable.getValueAt(selectedRow, 14).toString().equals("Allow");

        empPosName.setText(posName);
        empPosPerSale.setSelected(salePerm);
        empPosPerPurchase.setSelected(purchasePerm);
        empPosPerReturn.setSelected(returnPerm);
        empPosPerCustomer.setSelected(customerPerm);
        empPosPerSupplier.setSelected(supplierPerm);
        empPosPerEmployee.setSelected(employeePerm);
        empPosPerUserPosition.setSelected(userPosPerm);
        empPosPerUserProfile.setSelected(userProfPerm);
        empPosPerProducts.setSelected(productPerm);
        empPosPerInvoice.setSelected(invoicePerm);
        empPosPerXIncome.setSelected(xIncomePerm);
        empPosPerXCost.setSelected(xCostPerm);
        empPosPerReport.setSelected(reportPerm);
    }//GEN-LAST:event_empPosTableMouseClicked

    private void empPosSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_empPosSearchKeyReleased
        String query = "select * from employeeposition where PositionName like '%" + empPosSearch.getText().toString() + "%'";
        fillEmpPosTable(query);
        log.info("search function");
    }//GEN-LAST:event_empPosSearchKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton empPosButCancel;
    private javax.swing.JButton empPosButDelete;
    private javax.swing.JButton empPosButEdit;
    private javax.swing.JButton empPosButInsert;
    private app.bolivia.swing.JCTextField empPosName;
    private javax.swing.JCheckBox empPosPerCustomer;
    private javax.swing.JCheckBox empPosPerEmployee;
    private javax.swing.JCheckBox empPosPerInvoice;
    private javax.swing.JCheckBox empPosPerProducts;
    private javax.swing.JCheckBox empPosPerPurchase;
    private javax.swing.JCheckBox empPosPerReport;
    private javax.swing.JCheckBox empPosPerReturn;
    private javax.swing.JCheckBox empPosPerSale;
    private javax.swing.JCheckBox empPosPerSupplier;
    private javax.swing.JCheckBox empPosPerUserPosition;
    private javax.swing.JCheckBox empPosPerUserProfile;
    private javax.swing.JCheckBox empPosPerXCost;
    private javax.swing.JCheckBox empPosPerXIncome;
    private app.bolivia.swing.JCTextField empPosSearch;
    private rojeru_san.complementos.RSTableMetro empPosTable;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
