/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.xpos.gui;

import com.xpos.database.DbConnect;
import com.xpos.encrypt.MD5;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jamit
 */
public class UserProfile extends javax.swing.JPanel {

    DefaultTableModel tablemodel;
    DateTimeFormatter defaultDateFormat = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    int userProId;

    /**
     * Creates new form UserProfile
     */
    public UserProfile() {
        initComponents();
        clearUserProPanel();
    }

    public void clearUserProPanel() {
        loadUserProCombo();
        userProUsername.setText("");
        userProPassword.setText("");
        userProActive.setSelected(true);
        userProSearch.setText("");
        fillUserProTable(null);
    }

    public void loadUserProCombo() {
        try {
            ResultSet rs = DbConnect.getFromDB("select Id,Name from employee where status=1");
            Vector v = new Vector();
            v.add("Select Position");
            while (rs.next()) {
                String position = rs.getString("Id") + " - " + rs.getString("Name");
                v.add(position);
            }
            userProEmployeeCombo.setModel(new DefaultComboBoxModel(v));
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void fillUserProTable(String query) {
        tablemodel = (DefaultTableModel) userProTable.getModel();
        tablemodel.setRowCount(0);
        if (query == null) {
            query = "SELECT userprofile.Id,userprofile.Employee_Id,employee.Name, userprofile.Username,userprofile.Status FROM userprofile JOIN employee on userprofile.Employee_Id=employee.Id";
        }
        try {
            ResultSet rs = DbConnect.getFromDB(query);
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getInt("userprofile.Id"));
                v.add(rs.getInt("userprofile.Employee_Id"));
                v.add(rs.getString("employee.Name"));
                v.add(rs.getString("userprofile.Username"));
                v.add(rs.getBoolean("userprofile.Status") ? "Active" : "Not Active");

                tablemodel.addRow(v);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        isActive = new javax.swing.ButtonGroup();
        jLabel10 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        userProButInsert = new javax.swing.JButton();
        userProButEdit = new javax.swing.JButton();
        userProButDelete = new javax.swing.JButton();
        userProButCancel = new javax.swing.JButton();
        userProUsername = new app.bolivia.swing.JCTextField();
        jPanel19 = new javax.swing.JPanel();
        userProActive = new javax.swing.JRadioButton();
        userProNotActive = new javax.swing.JRadioButton();
        userProEmployeeCombo = new javax.swing.JComboBox<>();
        userProPassword = new javax.swing.JPasswordField();
        jPanel20 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        userProTable = new rojeru_san.complementos.RSTableMetro();
        userProSearch = new app.bolivia.swing.JCTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setBackground(new java.awt.Color(26, 140, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("USER PROFILE");
        jLabel10.setOpaque(true);

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));

        userProButInsert.setBackground(new java.awt.Color(0, 60, 128));
        userProButInsert.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        userProButInsert.setForeground(new java.awt.Color(255, 255, 255));
        userProButInsert.setText("INSERT");
        userProButInsert.setBorder(null);
        userProButInsert.setFocusPainted(false);
        userProButInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userProButInsertActionPerformed(evt);
            }
        });

        userProButEdit.setBackground(new java.awt.Color(0, 60, 128));
        userProButEdit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        userProButEdit.setForeground(new java.awt.Color(255, 255, 255));
        userProButEdit.setText("EDIT");
        userProButEdit.setBorder(null);
        userProButEdit.setFocusPainted(false);
        userProButEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userProButEditActionPerformed(evt);
            }
        });

        userProButDelete.setBackground(new java.awt.Color(0, 60, 128));
        userProButDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        userProButDelete.setForeground(new java.awt.Color(255, 255, 255));
        userProButDelete.setText("DELETE");
        userProButDelete.setBorder(null);
        userProButDelete.setFocusPainted(false);
        userProButDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userProButDeleteActionPerformed(evt);
            }
        });

        userProButCancel.setBackground(new java.awt.Color(0, 60, 128));
        userProButCancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        userProButCancel.setForeground(new java.awt.Color(255, 255, 255));
        userProButCancel.setText("CANCEL");
        userProButCancel.setBorder(null);
        userProButCancel.setFocusPainted(false);
        userProButCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userProButCancelActionPerformed(evt);
            }
        });

        userProUsername.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Username", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        userProUsername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        userProUsername.setPhColor(new java.awt.Color(0, 51, 255));
        userProUsername.setPreferredSize(new java.awt.Dimension(200, 30));

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Is Active", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N

        userProActive.setBackground(new java.awt.Color(255, 255, 255));
        isActive.add(userProActive);
        userProActive.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        userProActive.setForeground(new java.awt.Color(26, 140, 255));
        userProActive.setSelected(true);
        userProActive.setText("Active");

        userProNotActive.setBackground(new java.awt.Color(255, 255, 255));
        isActive.add(userProNotActive);
        userProNotActive.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        userProNotActive.setForeground(new java.awt.Color(26, 140, 255));
        userProNotActive.setText("Not-Active");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userProActive)
                .addGap(18, 18, 18)
                .addComponent(userProNotActive)
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userProActive)
                    .addComponent(userProNotActive))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        userProEmployeeCombo.setForeground(new java.awt.Color(26, 140, 255));
        userProEmployeeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Employee" }));
        userProEmployeeCombo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Select Employee", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        userProEmployeeCombo.setOpaque(false);

        userProPassword.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Default Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userProPassword)
                    .addComponent(jPanel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userProUsername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userProEmployeeCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel18Layout.createSequentialGroup()
                        .addComponent(userProButInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(userProButEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(userProButDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(userProButCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userProEmployeeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userProUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userProPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userProButInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userProButEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userProButDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userProButCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));

        userProTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Employee Id", "Employee Name", "UserName", "Status"
            }
        ));
        userProTable.setColorBackgoundHead(new java.awt.Color(26, 140, 255));
        userProTable.setFuenteHead(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        userProTable.setRowHeight(25);
        userProTable.setRowMargin(0);
        userProTable.setSelectionBackground(new java.awt.Color(0, 60, 128));
        userProTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userProTableMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(userProTable);

        userProSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        userProSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        userProSearch.setPhColor(new java.awt.Color(0, 51, 255));
        userProSearch.setPlaceholder("Search");
        userProSearch.setPreferredSize(new java.awt.Dimension(200, 30));
        userProSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                userProSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6)
                    .addComponent(userProSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userProSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1240, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void userProButInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userProButInsertActionPerformed
        int employeeId = Integer.parseInt(userProEmployeeCombo.getSelectedItem().toString().split(" - ")[0]);
        String username = userProUsername.getText();
        String password = MD5.getMd5(new String(userProPassword.getPassword()));
        boolean active = userProActive.isSelected() ? true : false;

        String query = "INSERT INTO `userprofile`(`Employee_Id`, `Username`, `Password`, `Status`) VALUES (" + employeeId
                + ",'" + username + "','" + password + "'," + active + ")";
        try {
            DbConnect.pushToDB(query);
            clearUserProPanel();
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_userProButInsertActionPerformed

    private void userProButEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userProButEditActionPerformed
        int employeeId = Integer.parseInt(userProEmployeeCombo.getSelectedItem().toString().split(" - ")[0]);
        String username = userProUsername.getText();
        String password = MD5.getMd5(new String(userProPassword.getPassword()));
        boolean active = userProActive.isSelected() ? true : false;

        String query = null;

        if (password.equals("d41d8cd98f00b204e9800998ecf8427e")) {
            query = "UPDATE `userprofile` SET `Employee_Id`=" + employeeId + ",`Username`='" + username
                    + "',`Status`=" + active + " WHERE Id=" + userProId;
        } else {
            query = "UPDATE `userprofile` SET `Employee_Id`=" + employeeId + ",`Username`='" + username
                    + "',`Password`='" + password + "',`Status`=" + active + " WHERE Id=" + userProId;
        }
        try {
            DbConnect.pushToDB(query);
            clearUserProPanel();
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_userProButEditActionPerformed

    private void userProButDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userProButDeleteActionPerformed
        String query = "UPDATE `userprofile` SET `Status`=0 WHERE Id=" + userProId;
        try {
            DbConnect.pushToDB(query);
            clearUserProPanel();
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_userProButDeleteActionPerformed

    private void userProButCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userProButCancelActionPerformed
        clearUserProPanel();
    }//GEN-LAST:event_userProButCancelActionPerformed

    private void userProTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userProTableMouseClicked
        int selectedRow = userProTable.getSelectedRow();
        userProId = Integer.parseInt(userProTable.getValueAt(selectedRow, 0).toString());
        int employeeId = Integer.parseInt(userProTable.getValueAt(selectedRow, 1).toString());
        String name = userProTable.getValueAt(selectedRow, 2).toString();
        userProEmployeeCombo.setSelectedItem(employeeId + " - " + name);
        userProUsername.setText(userProTable.getValueAt(selectedRow, 3).toString());
        userProActive.setSelected(userProTable.getValueAt(selectedRow, 4).toString().equals("Active"));
        userProNotActive.setSelected(userProTable.getValueAt(selectedRow, 4).toString().equals("Not Active"));
    }//GEN-LAST:event_userProTableMouseClicked

    private void userProSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userProSearchKeyReleased
        String query = "SELECT userprofile.Id,userprofile.Employee_Id,employee.Name,"
                + " userprofile.Username,userprofile.Status FROM userprofile "
                + "JOIN employee on userprofile.Employee_Id=employee.Id "
                + "WHERE  employee.Name LIKE '%" + userProSearch.getText() + "%'";
        fillUserProTable(query);
    }//GEN-LAST:event_userProSearchKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup isActive;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JRadioButton userProActive;
    private javax.swing.JButton userProButCancel;
    private javax.swing.JButton userProButDelete;
    private javax.swing.JButton userProButEdit;
    private javax.swing.JButton userProButInsert;
    private javax.swing.JComboBox<String> userProEmployeeCombo;
    private javax.swing.JRadioButton userProNotActive;
    private javax.swing.JPasswordField userProPassword;
    private app.bolivia.swing.JCTextField userProSearch;
    private rojeru_san.complementos.RSTableMetro userProTable;
    private app.bolivia.swing.JCTextField userProUsername;
    // End of variables declaration//GEN-END:variables
}
