/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.xpos;

import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JFrame;

/**
 *
 * @author Jamit
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/com/xpos/images/icon.png")));
        setTitle("XPOS 2.0");
        runDateTime();
        setVisibleFalseAllPanels();
        setDashboardComponent();
    }

    Timer myTimer = new Timer();
    TimerTask task = new TimerTask() {
        @Override
        public void run() {
            Date d = new Date();
            SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss");
            systemTime.setText(s.format(d));
            SimpleDateFormat k = new SimpleDateFormat("yyyy-MM-dd");
            systemDate.setText(k.format(d));
        }
    };

    public void runDateTime() {
        myTimer.scheduleAtFixedRate(task, 0, 500);
    }

    public void setDashboardComponent(){
        dailyCustomerCount.setCompoName(" Today Customers");
        dailySaleCount.setCompoName(" Today Sales");
        dailyPurchaseCount.setCompoName(" Today Purchases");
        dailyReturnCount.setCompoName(" Today Returns");
        productCount.setCompoName(" Products");
        remProductCount.setCompoName(" Removed Products");
        employeeCount.setCompoName(" Employees");
        ongoingPOs.setCompoName(" Ongoing Purchases");
        supplierCount.setCompoName(" Suppliers");
        ongoingQuates.setCompoName(" Ongoing quates");
        categoryCount.setCompoName(" Categories");
        stockItemCount.setCompoName(" Stock Items");
    }
    
    public void setVisibleFalseAllPanels() {
        dashboard.setVisible(false);
        supplier.setVisible(false);
        Product.setVisible(false);
        Customer.setVisible(false);
        EmpPosition.setVisible(false);
        Employee.setVisible(false);
        UserProfile.setVisible(false);
        ExCost.setVisible(false);
        ExIncome.setVisible(false);
        Purchase.setVisible(false);
        Sale.setVisible(false);
        Batch.setVisible(false);
        HRM.setVisible(false);
        Brand.setVisible(false);
        Category.setVisible(false);
        SupplierProduct.setVisible(false);
        PurchaseOrder.setVisible(false);
        Return.setVisible(false);
        Invoices.setVisible(false);
        SaleInvoice.setVisible(false);
        PurchaseInvoice.setVisible(false);
        ReturnInvoice.setVisible(false);
        POInvoice.setVisible(false);
        ProductDetail.setVisible(false);
        reqForQuate.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        SideBar2 = new javax.swing.JPanel();
        homeBut2 = new javax.swing.JButton();
        supplierBut = new javax.swing.JButton();
        product = new javax.swing.JButton();
        customer = new javax.swing.JButton();
        exCost = new javax.swing.JButton();
        exIncome = new javax.swing.JButton();
        purchase = new javax.swing.JButton();
        sale = new javax.swing.JButton();
        hrm = new javax.swing.JButton();
        supplierProduct = new javax.swing.JButton();
        purchaseOrder = new javax.swing.JButton();
        returnPanel = new javax.swing.JButton();
        invoiceBtn = new javax.swing.JButton();
        invoiceBtn1 = new javax.swing.JButton();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        systemUserName = new javax.swing.JLabel();
        systemDate = new javax.swing.JLabel();
        systemTime = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        dashboard = new javax.swing.JPanel();
        dailyCustomerCount = new com.xpos.dashboard.component.Dashpanel();
        dailySaleCount = new com.xpos.dashboard.component.Dashpanel();
        dailyPurchaseCount = new com.xpos.dashboard.component.Dashpanel();
        dailyReturnCount = new com.xpos.dashboard.component.Dashpanel();
        productCount = new com.xpos.dashboard.component.Dashpanel();
        supplierCount = new com.xpos.dashboard.component.Dashpanel();
        remProductCount = new com.xpos.dashboard.component.Dashpanel();
        ongoingQuates = new com.xpos.dashboard.component.Dashpanel();
        employeeCount = new com.xpos.dashboard.component.Dashpanel();
        categoryCount = new com.xpos.dashboard.component.Dashpanel();
        ongoingPOs = new com.xpos.dashboard.component.Dashpanel();
        stockItemCount = new com.xpos.dashboard.component.Dashpanel();
        supplier = new com.xpos.gui.Supply();
        Sale = new com.xpos.gui.Sale();
        Purchase = new com.xpos.gui.Purchase();
        ExCost = new com.xpos.gui.ExCost();
        ExIncome = new com.xpos.gui.ExIncome();
        Customer = new com.xpos.gui.Customer();
        HRM = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jPanel35 = new javax.swing.JPanel();
        Employee = new com.xpos.gui.Employee();
        UserProfile = new com.xpos.gui.UserProfile();
        EmpPosition = new com.xpos.gui.EmpPosition();
        employee = new javax.swing.JButton();
        userProfile = new javax.swing.JButton();
        userPosition = new javax.swing.JButton();
        SupplierProduct = new com.xpos.gui.SupplierProduct();
        PurchaseOrder = new com.xpos.gui.PurchaseOrder();
        Return = new com.xpos.gui.Return();
        ProductDetail = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jPanel36 = new javax.swing.JPanel();
        Product = new com.xpos.gui.Product();
        Batch = new com.xpos.gui.ProductBatch();
        Brand = new com.xpos.gui.Brand();
        Category = new com.xpos.gui.Category();
        productBatchPanelBtn = new javax.swing.JButton();
        categoryPanelBtn = new javax.swing.JButton();
        brandPanelBtn = new javax.swing.JButton();
        productPanelBtn = new javax.swing.JButton();
        Invoices = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jPanel37 = new javax.swing.JPanel();
        SaleInvoice = new com.xpos.gui.SaleInvoice();
        PurchaseInvoice = new com.xpos.gui.PurchaseInvoice();
        ReturnInvoice = new com.xpos.gui.ReturnInvoice();
        POInvoice = new com.xpos.gui.POInvoice();
        purchaseInvoiceBtn = new javax.swing.JButton();
        purchaseOrderBtn = new javax.swing.JButton();
        returnInvoiceBtn = new javax.swing.JButton();
        saleInvoiceBtn = new javax.swing.JButton();
        reqForQuate = new com.xpos.gui.ReqForQuate();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("XPOS 2.0"); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1920, 996));

        SideBar2.setBackground(new java.awt.Color(26, 140, 255));

        homeBut2.setBackground(new java.awt.Color(0, 60, 128));
        homeBut2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        homeBut2.setForeground(new java.awt.Color(255, 255, 255));
        homeBut2.setText("DASHBOARD");
        homeBut2.setBorder(null);
        homeBut2.setFocusPainted(false);
        homeBut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBut2ActionPerformed(evt);
            }
        });

        supplierBut.setBackground(new java.awt.Color(0, 60, 128));
        supplierBut.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        supplierBut.setForeground(new java.awt.Color(255, 255, 255));
        supplierBut.setText("SUPPLIER");
        supplierBut.setBorder(null);
        supplierBut.setFocusPainted(false);
        supplierBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierButActionPerformed(evt);
            }
        });

        product.setBackground(new java.awt.Color(0, 60, 128));
        product.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        product.setForeground(new java.awt.Color(255, 255, 255));
        product.setText("PRODUCT DETAILS");
        product.setBorder(null);
        product.setFocusPainted(false);
        product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productActionPerformed(evt);
            }
        });

        customer.setBackground(new java.awt.Color(0, 60, 128));
        customer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        customer.setForeground(new java.awt.Color(255, 255, 255));
        customer.setText("CUSTOMER");
        customer.setBorder(null);
        customer.setFocusPainted(false);
        customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerActionPerformed(evt);
            }
        });

        exCost.setBackground(new java.awt.Color(0, 60, 128));
        exCost.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exCost.setForeground(new java.awt.Color(255, 255, 255));
        exCost.setText("ADDITIONAL COST");
        exCost.setBorder(null);
        exCost.setFocusPainted(false);
        exCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exCostActionPerformed(evt);
            }
        });

        exIncome.setBackground(new java.awt.Color(0, 60, 128));
        exIncome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exIncome.setForeground(new java.awt.Color(255, 255, 255));
        exIncome.setText("EXTRA INCOME");
        exIncome.setBorder(null);
        exIncome.setFocusPainted(false);
        exIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exIncomeActionPerformed(evt);
            }
        });

        purchase.setBackground(new java.awt.Color(0, 60, 128));
        purchase.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        purchase.setForeground(new java.awt.Color(255, 255, 255));
        purchase.setText("PURCHASE");
        purchase.setBorder(null);
        purchase.setFocusPainted(false);
        purchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseActionPerformed(evt);
            }
        });

        sale.setBackground(new java.awt.Color(0, 60, 128));
        sale.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sale.setForeground(new java.awt.Color(255, 255, 255));
        sale.setText("SALE");
        sale.setBorder(null);
        sale.setFocusPainted(false);
        sale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleActionPerformed(evt);
            }
        });

        hrm.setBackground(new java.awt.Color(0, 60, 128));
        hrm.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        hrm.setForeground(new java.awt.Color(255, 255, 255));
        hrm.setText("HUMAN RESOURCE");
        hrm.setBorder(null);
        hrm.setFocusPainted(false);
        hrm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrmActionPerformed(evt);
            }
        });

        supplierProduct.setBackground(new java.awt.Color(0, 60, 128));
        supplierProduct.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        supplierProduct.setForeground(new java.awt.Color(255, 255, 255));
        supplierProduct.setText("SUPPLIER PRODUCT");
        supplierProduct.setBorder(null);
        supplierProduct.setFocusPainted(false);
        supplierProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierProductActionPerformed(evt);
            }
        });

        purchaseOrder.setBackground(new java.awt.Color(0, 60, 128));
        purchaseOrder.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        purchaseOrder.setForeground(new java.awt.Color(255, 255, 255));
        purchaseOrder.setText("PURCHASE ORDER");
        purchaseOrder.setBorder(null);
        purchaseOrder.setFocusPainted(false);
        purchaseOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseOrderActionPerformed(evt);
            }
        });

        returnPanel.setBackground(new java.awt.Color(0, 60, 128));
        returnPanel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        returnPanel.setForeground(new java.awt.Color(255, 255, 255));
        returnPanel.setText("RETURN");
        returnPanel.setBorder(null);
        returnPanel.setFocusPainted(false);
        returnPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnPanelActionPerformed(evt);
            }
        });

        invoiceBtn.setBackground(new java.awt.Color(0, 60, 128));
        invoiceBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        invoiceBtn.setForeground(new java.awt.Color(255, 255, 255));
        invoiceBtn.setText("INVOICES");
        invoiceBtn.setBorder(null);
        invoiceBtn.setFocusPainted(false);
        invoiceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoiceBtnActionPerformed(evt);
            }
        });

        invoiceBtn1.setBackground(new java.awt.Color(0, 60, 128));
        invoiceBtn1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        invoiceBtn1.setForeground(new java.awt.Color(255, 255, 255));
        invoiceBtn1.setText("REQUEST FOR QUATE");
        invoiceBtn1.setBorder(null);
        invoiceBtn1.setFocusPainted(false);
        invoiceBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoiceBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SideBar2Layout = new javax.swing.GroupLayout(SideBar2);
        SideBar2.setLayout(SideBar2Layout);
        SideBar2Layout.setHorizontalGroup(
            SideBar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBar2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SideBar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homeBut2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(supplierBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(product, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exIncome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exCost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(purchase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hrm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(supplierProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(purchaseOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(returnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(invoiceBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(invoiceBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        SideBar2Layout.setVerticalGroup(
            SideBar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBar2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeBut2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(supplierBut, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(product, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hrm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exCost, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(purchase, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sale, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(supplierProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(purchaseOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(returnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(invoiceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(invoiceBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Header.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/xpos/images/Logo.png"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jPanel4.setBackground(new java.awt.Color(179, 215, 255));

        systemUserName.setBackground(new java.awt.Color(255, 255, 255));
        systemUserName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        systemUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        systemUserName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/xpos/images/user.png"))); // NOI18N
        systemUserName.setText("USERNAME");
        systemUserName.setAlignmentX(1.0F);
        systemUserName.setAlignmentY(1.0F);
        systemUserName.setOpaque(true);

        systemDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        systemDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        systemDate.setText("date");

        systemTime.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        systemTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        systemTime.setText("   time");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(systemUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(systemTime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(systemDate, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(systemDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(systemTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(systemUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255), 3));
        MainPanel.setLayout(new java.awt.CardLayout());

        dashboard.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout dashboardLayout = new javax.swing.GroupLayout(dashboard);
        dashboard.setLayout(dashboardLayout);
        dashboardLayout.setHorizontalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dashboardLayout.createSequentialGroup()
                        .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(productCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(supplierCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(remProductCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ongoingQuates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(employeeCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(categoryCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ongoingPOs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stockItemCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(dashboardLayout.createSequentialGroup()
                        .addComponent(dailyCustomerCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dailySaleCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dailyPurchaseCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dailyReturnCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dashboardLayout.setVerticalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dailyReturnCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dailyPurchaseCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dailySaleCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dailyCustomerCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dashboardLayout.createSequentialGroup()
                        .addComponent(productCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(supplierCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dashboardLayout.createSequentialGroup()
                        .addComponent(remProductCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ongoingQuates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dashboardLayout.createSequentialGroup()
                        .addComponent(employeeCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(categoryCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dashboardLayout.createSequentialGroup()
                        .addComponent(ongoingPOs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(stockItemCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MainPanel.add(dashboard, "card3");
        MainPanel.add(supplier, "card2");
        MainPanel.add(Sale, "card4");
        MainPanel.add(Purchase, "card5");
        MainPanel.add(ExCost, "card6");
        MainPanel.add(ExIncome, "card7");
        MainPanel.add(Customer, "card8");

        HRM.setBackground(new java.awt.Color(255, 255, 255));
        HRM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255), 0));

        jLabel45.setBackground(new java.awt.Color(26, 140, 255));
        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("HUMAN RESOURCE");
        jLabel45.setOpaque(true);

        jPanel35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255), 2));
        jPanel35.setLayout(new java.awt.CardLayout());
        jPanel35.add(Employee, "card2");
        jPanel35.add(UserProfile, "card3");
        jPanel35.add(EmpPosition, "card4");

        employee.setBackground(new java.awt.Color(0, 60, 128));
        employee.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        employee.setForeground(new java.awt.Color(255, 255, 255));
        employee.setText("EMPLOYEE");
        employee.setBorder(null);
        employee.setFocusPainted(false);
        employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeActionPerformed(evt);
            }
        });

        userProfile.setBackground(new java.awt.Color(0, 60, 128));
        userProfile.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        userProfile.setForeground(new java.awt.Color(255, 255, 255));
        userProfile.setText("USER PROFILE");
        userProfile.setBorder(null);
        userProfile.setFocusPainted(false);
        userProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userProfileActionPerformed(evt);
            }
        });

        userPosition.setBackground(new java.awt.Color(0, 60, 128));
        userPosition.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        userPosition.setForeground(new java.awt.Color(255, 255, 255));
        userPosition.setText("EMPL. POSITION");
        userPosition.setBorder(null);
        userPosition.setFocusPainted(false);
        userPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userPositionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HRMLayout = new javax.swing.GroupLayout(HRM);
        HRM.setLayout(HRMLayout);
        HRMLayout.setHorizontalGroup(
            HRMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HRMLayout.createSequentialGroup()
                .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(HRMLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HRMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel35, javax.swing.GroupLayout.DEFAULT_SIZE, 1624, Short.MAX_VALUE)
                    .addGroup(HRMLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(employee, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        HRMLayout.setVerticalGroup(
            HRMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HRMLayout.createSequentialGroup()
                .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(HRMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employee, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel35, javax.swing.GroupLayout.DEFAULT_SIZE, 866, Short.MAX_VALUE)
                .addContainerGap())
        );

        MainPanel.add(HRM, "card2");
        MainPanel.add(SupplierProduct, "card14");
        MainPanel.add(PurchaseOrder, "card15");
        MainPanel.add(Return, "card16");

        ProductDetail.setBackground(new java.awt.Color(255, 255, 255));
        ProductDetail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255), 0));

        jLabel46.setBackground(new java.awt.Color(26, 140, 255));
        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("PRODUCT DETAILS");
        jLabel46.setOpaque(true);

        jPanel36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255), 2));
        jPanel36.setLayout(new java.awt.CardLayout());
        jPanel36.add(Product, "card5");
        jPanel36.add(Batch, "card11");
        jPanel36.add(Brand, "card12");
        jPanel36.add(Category, "card13");

        productBatchPanelBtn.setBackground(new java.awt.Color(0, 60, 128));
        productBatchPanelBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        productBatchPanelBtn.setForeground(new java.awt.Color(255, 255, 255));
        productBatchPanelBtn.setText("PRODUCT BATCH");
        productBatchPanelBtn.setBorder(null);
        productBatchPanelBtn.setFocusPainted(false);
        productBatchPanelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productBatchPanelBtnActionPerformed(evt);
            }
        });

        categoryPanelBtn.setBackground(new java.awt.Color(0, 60, 128));
        categoryPanelBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        categoryPanelBtn.setForeground(new java.awt.Color(255, 255, 255));
        categoryPanelBtn.setText("CATEGORY");
        categoryPanelBtn.setBorder(null);
        categoryPanelBtn.setFocusPainted(false);
        categoryPanelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryPanelBtnActionPerformed(evt);
            }
        });

        brandPanelBtn.setBackground(new java.awt.Color(0, 60, 128));
        brandPanelBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        brandPanelBtn.setForeground(new java.awt.Color(255, 255, 255));
        brandPanelBtn.setText("BRAND");
        brandPanelBtn.setBorder(null);
        brandPanelBtn.setFocusPainted(false);
        brandPanelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandPanelBtnActionPerformed(evt);
            }
        });

        productPanelBtn.setBackground(new java.awt.Color(0, 60, 128));
        productPanelBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        productPanelBtn.setForeground(new java.awt.Color(255, 255, 255));
        productPanelBtn.setText("PRODUCT");
        productPanelBtn.setBorder(null);
        productPanelBtn.setFocusPainted(false);
        productPanelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productPanelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ProductDetailLayout = new javax.swing.GroupLayout(ProductDetail);
        ProductDetail.setLayout(ProductDetailLayout);
        ProductDetailLayout.setHorizontalGroup(
            ProductDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductDetailLayout.createSequentialGroup()
                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(ProductDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProductDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel36, javax.swing.GroupLayout.DEFAULT_SIZE, 1624, Short.MAX_VALUE)
                    .addGroup(ProductDetailLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(productPanelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(productBatchPanelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(brandPanelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(categoryPanelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        ProductDetailLayout.setVerticalGroup(
            ProductDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductDetailLayout.createSequentialGroup()
                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(ProductDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productBatchPanelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoryPanelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brandPanelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productPanelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel36, javax.swing.GroupLayout.DEFAULT_SIZE, 866, Short.MAX_VALUE)
                .addContainerGap())
        );

        MainPanel.add(ProductDetail, "card2");

        Invoices.setBackground(new java.awt.Color(255, 255, 255));
        Invoices.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255), 0));

        jLabel47.setBackground(new java.awt.Color(26, 140, 255));
        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("PRODUCT DETAILS");
        jLabel47.setOpaque(true);

        jPanel37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255), 2));
        jPanel37.setLayout(new java.awt.CardLayout());
        jPanel37.add(SaleInvoice, "card2");
        jPanel37.add(PurchaseInvoice, "card3");
        jPanel37.add(ReturnInvoice, "card4");
        jPanel37.add(POInvoice, "card5");

        purchaseInvoiceBtn.setBackground(new java.awt.Color(0, 60, 128));
        purchaseInvoiceBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        purchaseInvoiceBtn.setForeground(new java.awt.Color(255, 255, 255));
        purchaseInvoiceBtn.setText("PURCHASE INVOICE");
        purchaseInvoiceBtn.setBorder(null);
        purchaseInvoiceBtn.setFocusPainted(false);
        purchaseInvoiceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseInvoiceBtnActionPerformed(evt);
            }
        });

        purchaseOrderBtn.setBackground(new java.awt.Color(0, 60, 128));
        purchaseOrderBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        purchaseOrderBtn.setForeground(new java.awt.Color(255, 255, 255));
        purchaseOrderBtn.setText("PURCHASE ORDER");
        purchaseOrderBtn.setBorder(null);
        purchaseOrderBtn.setFocusPainted(false);
        purchaseOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseOrderBtnActionPerformed(evt);
            }
        });

        returnInvoiceBtn.setBackground(new java.awt.Color(0, 60, 128));
        returnInvoiceBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        returnInvoiceBtn.setForeground(new java.awt.Color(255, 255, 255));
        returnInvoiceBtn.setText("RETURN INVOICE");
        returnInvoiceBtn.setBorder(null);
        returnInvoiceBtn.setFocusPainted(false);
        returnInvoiceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnInvoiceBtnActionPerformed(evt);
            }
        });

        saleInvoiceBtn.setBackground(new java.awt.Color(0, 60, 128));
        saleInvoiceBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        saleInvoiceBtn.setForeground(new java.awt.Color(255, 255, 255));
        saleInvoiceBtn.setText("SALE INVOICE");
        saleInvoiceBtn.setBorder(null);
        saleInvoiceBtn.setFocusPainted(false);
        saleInvoiceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleInvoiceBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InvoicesLayout = new javax.swing.GroupLayout(Invoices);
        Invoices.setLayout(InvoicesLayout);
        InvoicesLayout.setHorizontalGroup(
            InvoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InvoicesLayout.createSequentialGroup()
                .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(InvoicesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InvoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel37, javax.swing.GroupLayout.DEFAULT_SIZE, 1624, Short.MAX_VALUE)
                    .addGroup(InvoicesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(saleInvoiceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(purchaseInvoiceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(returnInvoiceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(purchaseOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        InvoicesLayout.setVerticalGroup(
            InvoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InvoicesLayout.createSequentialGroup()
                .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(InvoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(purchaseInvoiceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(purchaseOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnInvoiceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saleInvoiceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel37, javax.swing.GroupLayout.DEFAULT_SIZE, 866, Short.MAX_VALUE)
                .addContainerGap())
        );

        MainPanel.add(Invoices, "card2");
        MainPanel.add(reqForQuate, "card15");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(SideBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SideBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1062, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBut2ActionPerformed
        setVisibleFalseAllPanels();
        dashboard.setVisible(true);
    }//GEN-LAST:event_homeBut2ActionPerformed

    private void supplierButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierButActionPerformed
        setVisibleFalseAllPanels();
        supplier.setVisible(true);
    }//GEN-LAST:event_supplierButActionPerformed

    private void productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productActionPerformed
        setVisibleFalseAllPanels();
        ProductDetail.setVisible(true);
    }//GEN-LAST:event_productActionPerformed

    private void customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerActionPerformed
        setVisibleFalseAllPanels();
        Customer.setVisible(true);
    }//GEN-LAST:event_customerActionPerformed

    private void exCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exCostActionPerformed
        setVisibleFalseAllPanels();
        ExCost.setVisible(true);
    }//GEN-LAST:event_exCostActionPerformed

    private void exIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exIncomeActionPerformed
        setVisibleFalseAllPanels();
        ExIncome.setVisible(true);
    }//GEN-LAST:event_exIncomeActionPerformed

    private void purchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseActionPerformed
        setVisibleFalseAllPanels();
        Purchase.setVisible(true);
    }//GEN-LAST:event_purchaseActionPerformed

    private void saleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleActionPerformed
        setVisibleFalseAllPanels();
        Sale.setVisible(true);
    }//GEN-LAST:event_saleActionPerformed

    private void hrmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrmActionPerformed
        setVisibleFalseAllPanels();
        HRM.setVisible(true);
    }//GEN-LAST:event_hrmActionPerformed

    private void employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeActionPerformed
        setVisibleFalseAllPanels();
        HRM.setVisible(true);
        Employee.setVisible(true);
    }//GEN-LAST:event_employeeActionPerformed

    private void userProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userProfileActionPerformed
        setVisibleFalseAllPanels();
        HRM.setVisible(true);
        UserProfile.setVisible(true);
    }//GEN-LAST:event_userProfileActionPerformed

    private void userPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userPositionActionPerformed
        setVisibleFalseAllPanels();
        HRM.setVisible(true);
        EmpPosition.setVisible(true);
    }//GEN-LAST:event_userPositionActionPerformed

    private void supplierProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierProductActionPerformed
        setVisibleFalseAllPanels();
        SupplierProduct.setVisible(true);
    }//GEN-LAST:event_supplierProductActionPerformed

    private void purchaseOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseOrderActionPerformed
        setVisibleFalseAllPanels();
        PurchaseOrder.setVisible(true);
    }//GEN-LAST:event_purchaseOrderActionPerformed

    private void returnPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnPanelActionPerformed
        setVisibleFalseAllPanels();
        Return.setVisible(true);
    }//GEN-LAST:event_returnPanelActionPerformed

    private void productBatchPanelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productBatchPanelBtnActionPerformed
        setVisibleFalseAllPanels();
        ProductDetail.setVisible(true);
        Batch.setVisible(true);
    }//GEN-LAST:event_productBatchPanelBtnActionPerformed

    private void categoryPanelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryPanelBtnActionPerformed
        setVisibleFalseAllPanels();
        ProductDetail.setVisible(true);
        Category.setVisible(true);
    }//GEN-LAST:event_categoryPanelBtnActionPerformed

    private void brandPanelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandPanelBtnActionPerformed
        setVisibleFalseAllPanels();
        ProductDetail.setVisible(true);
        Brand.setVisible(true);
    }//GEN-LAST:event_brandPanelBtnActionPerformed

    private void productPanelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productPanelBtnActionPerformed
        setVisibleFalseAllPanels();
        ProductDetail.setVisible(true);
        Product.setVisible(true);
    }//GEN-LAST:event_productPanelBtnActionPerformed

    private void purchaseInvoiceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseInvoiceBtnActionPerformed
        setVisibleFalseAllPanels();
        Invoices.setVisible(true);
        PurchaseInvoice.setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_purchaseInvoiceBtnActionPerformed

    private void purchaseOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseOrderBtnActionPerformed
        setVisibleFalseAllPanels();
        Invoices.setVisible(true);
        POInvoice.setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_purchaseOrderBtnActionPerformed

    private void returnInvoiceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnInvoiceBtnActionPerformed
        setVisibleFalseAllPanels();
        Invoices.setVisible(true);
        ReturnInvoice.setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_returnInvoiceBtnActionPerformed

    private void saleInvoiceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleInvoiceBtnActionPerformed
        setVisibleFalseAllPanels();
        Invoices.setVisible(true);
        SaleInvoice.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_saleInvoiceBtnActionPerformed

    private void invoiceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoiceBtnActionPerformed
        setVisibleFalseAllPanels();
        Invoices.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_invoiceBtnActionPerformed

    private void invoiceBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoiceBtn1ActionPerformed
        setVisibleFalseAllPanels();
        reqForQuate.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_invoiceBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.xpos.gui.ProductBatch Batch;
    private com.xpos.gui.Brand Brand;
    private com.xpos.gui.Category Category;
    private com.xpos.gui.Customer Customer;
    private com.xpos.gui.EmpPosition EmpPosition;
    private com.xpos.gui.Employee Employee;
    private com.xpos.gui.ExCost ExCost;
    private com.xpos.gui.ExIncome ExIncome;
    private javax.swing.JPanel HRM;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Invoices;
    private javax.swing.JPanel MainPanel;
    private com.xpos.gui.POInvoice POInvoice;
    private com.xpos.gui.Product Product;
    private javax.swing.JPanel ProductDetail;
    private com.xpos.gui.Purchase Purchase;
    private com.xpos.gui.PurchaseInvoice PurchaseInvoice;
    private com.xpos.gui.PurchaseOrder PurchaseOrder;
    private com.xpos.gui.Return Return;
    private com.xpos.gui.ReturnInvoice ReturnInvoice;
    private com.xpos.gui.Sale Sale;
    private com.xpos.gui.SaleInvoice SaleInvoice;
    private javax.swing.JPanel SideBar2;
    private com.xpos.gui.SupplierProduct SupplierProduct;
    private com.xpos.gui.UserProfile UserProfile;
    private javax.swing.JButton brandPanelBtn;
    private com.xpos.dashboard.component.Dashpanel categoryCount;
    private javax.swing.JButton categoryPanelBtn;
    private javax.swing.JButton customer;
    private com.xpos.dashboard.component.Dashpanel dailyCustomerCount;
    private com.xpos.dashboard.component.Dashpanel dailyPurchaseCount;
    private com.xpos.dashboard.component.Dashpanel dailyReturnCount;
    private com.xpos.dashboard.component.Dashpanel dailySaleCount;
    private javax.swing.JPanel dashboard;
    private javax.swing.JButton employee;
    private com.xpos.dashboard.component.Dashpanel employeeCount;
    private javax.swing.JButton exCost;
    private javax.swing.JButton exIncome;
    private javax.swing.JButton homeBut2;
    private javax.swing.JButton hrm;
    private javax.swing.JButton invoiceBtn;
    private javax.swing.JButton invoiceBtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel4;
    private com.xpos.dashboard.component.Dashpanel ongoingPOs;
    private com.xpos.dashboard.component.Dashpanel ongoingQuates;
    private javax.swing.JButton product;
    private javax.swing.JButton productBatchPanelBtn;
    private com.xpos.dashboard.component.Dashpanel productCount;
    private javax.swing.JButton productPanelBtn;
    private javax.swing.JButton purchase;
    private javax.swing.JButton purchaseInvoiceBtn;
    private javax.swing.JButton purchaseOrder;
    private javax.swing.JButton purchaseOrderBtn;
    private com.xpos.dashboard.component.Dashpanel remProductCount;
    private com.xpos.gui.ReqForQuate reqForQuate;
    private javax.swing.JButton returnInvoiceBtn;
    private javax.swing.JButton returnPanel;
    private javax.swing.JButton sale;
    private javax.swing.JButton saleInvoiceBtn;
    private com.xpos.dashboard.component.Dashpanel stockItemCount;
    private com.xpos.gui.Supply supplier;
    private javax.swing.JButton supplierBut;
    private com.xpos.dashboard.component.Dashpanel supplierCount;
    private javax.swing.JButton supplierProduct;
    private javax.swing.JLabel systemDate;
    private javax.swing.JLabel systemTime;
    private javax.swing.JLabel systemUserName;
    private javax.swing.JButton userPosition;
    private javax.swing.JButton userProfile;
    // End of variables declaration//GEN-END:variables
}
