/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.xpos.gui;

import com.xpos.database.DbConnect;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import com.xpos.validation.Validate;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Jamit
 */
public class Brand extends javax.swing.JPanel {

    DefaultTableModel tablemodel;
    DateTimeFormatter defaultDateFormat = DateTimeFormatter.ofPattern("yyyy-MM-dd");

    int brandId;

    /**
     * Creates new form Brand
     */
    public Brand() {
        initComponents();
        clearBrandPanel();
    }

    private boolean validateForm() {
        return Validate.isName(brandName.getText().toString())
                && Validate.isName(brandCompanyName.getText().toString())
                && Validate.isText(brandCompanyAddress.getText().toString())
                && Validate.isText(brandCompanyRegNo.getText().toString());
    }

    public void clearBrandPanel() {
        brandName.setText("");
        brandCompanyName.setText("");
        brandCompanyAddress.setText("");
        brandCompanyRegNo.setText("");
        fillBrandTable(null);
    }

    public void fillBrandTable(String query) {
        tablemodel = (DefaultTableModel) brandTable.getModel();
        tablemodel.setRowCount(0);
        if (query == null) {
            query = "SELECT * FROM `brand` where status=1";
        }
        try {
            ResultSet rs = DbConnect.getFromDB(query);
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getInt("Id"));
                v.add(rs.getString("BrandName"));
                v.add(rs.getString("CompanyName"));
                v.add(rs.getString("CompanyAddress"));
                v.add(rs.getString("CompanyRegNo"));

                tablemodel.addRow(v);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        brandTable = new rojeru_san.complementos.RSTableMetro();
        brandSearch = new app.bolivia.swing.JCTextField();
        jPanel10 = new javax.swing.JPanel();
        brandCompanyName = new app.bolivia.swing.JCTextField();
        brandCompanyAddress = new app.bolivia.swing.JCTextField();
        brandCompanyRegNo = new app.bolivia.swing.JCTextField();
        brandButInsert = new javax.swing.JButton();
        brandButEdit = new javax.swing.JButton();
        brandButDelete = new javax.swing.JButton();
        brandButCancel = new javax.swing.JButton();
        brandName = new app.bolivia.swing.JCTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setBackground(new java.awt.Color(26, 140, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("BRAND ");
        jLabel6.setOpaque(true);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        brandTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Brand", "Company", "Company Address", "Company Reg NO"
            }
        ));
        brandTable.setColorBackgoundHead(new java.awt.Color(26, 140, 255));
        brandTable.setFuenteHead(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        brandTable.setRowHeight(25);
        brandTable.setRowMargin(0);
        brandTable.setSelectionBackground(new java.awt.Color(0, 60, 128));
        brandTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                brandTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(brandTable);

        brandSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        brandSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        brandSearch.setPhColor(new java.awt.Color(0, 51, 255));
        brandSearch.setPlaceholder("Search");
        brandSearch.setPreferredSize(new java.awt.Dimension(200, 30));
        brandSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandSearchActionPerformed(evt);
            }
        });
        brandSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                brandSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
                    .addComponent(brandSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(brandSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        brandCompanyName.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Company Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        brandCompanyName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        brandCompanyName.setPhColor(new java.awt.Color(0, 51, 255));
        brandCompanyName.setPlaceholder("Company Name");
        brandCompanyName.setPreferredSize(new java.awt.Dimension(200, 30));
        brandCompanyName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                brandCompanyNameKeyPressed(evt);
            }
        });

        brandCompanyAddress.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Company Address", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        brandCompanyAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        brandCompanyAddress.setPhColor(new java.awt.Color(0, 51, 255));
        brandCompanyAddress.setPlaceholder("Company Address");
        brandCompanyAddress.setPreferredSize(new java.awt.Dimension(200, 30));
        brandCompanyAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                brandCompanyAddressKeyPressed(evt);
            }
        });

        brandCompanyRegNo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Company Register NO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        brandCompanyRegNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        brandCompanyRegNo.setPhColor(new java.awt.Color(0, 51, 255));
        brandCompanyRegNo.setPlaceholder("Company Register NO");
        brandCompanyRegNo.setPreferredSize(new java.awt.Dimension(200, 30));
        brandCompanyRegNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                brandCompanyRegNoKeyPressed(evt);
            }
        });

        brandButInsert.setBackground(new java.awt.Color(0, 60, 128));
        brandButInsert.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        brandButInsert.setForeground(new java.awt.Color(255, 255, 255));
        brandButInsert.setText("INSERT");
        brandButInsert.setBorder(null);
        brandButInsert.setFocusPainted(false);
        brandButInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandButInsertActionPerformed(evt);
            }
        });

        brandButEdit.setBackground(new java.awt.Color(0, 60, 128));
        brandButEdit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        brandButEdit.setForeground(new java.awt.Color(255, 255, 255));
        brandButEdit.setText("EDIT");
        brandButEdit.setBorder(null);
        brandButEdit.setFocusPainted(false);
        brandButEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandButEditActionPerformed(evt);
            }
        });

        brandButDelete.setBackground(new java.awt.Color(0, 60, 128));
        brandButDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        brandButDelete.setForeground(new java.awt.Color(255, 255, 255));
        brandButDelete.setText("DELETE");
        brandButDelete.setBorder(null);
        brandButDelete.setFocusPainted(false);
        brandButDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandButDeleteActionPerformed(evt);
            }
        });

        brandButCancel.setBackground(new java.awt.Color(0, 60, 128));
        brandButCancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        brandButCancel.setForeground(new java.awt.Color(255, 255, 255));
        brandButCancel.setText("CANCEL");
        brandButCancel.setBorder(null);
        brandButCancel.setFocusPainted(false);
        brandButCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandButCancelActionPerformed(evt);
            }
        });

        brandName.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Brand Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        brandName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        brandName.setPhColor(new java.awt.Color(0, 51, 255));
        brandName.setPlaceholder("Brand Name");
        brandName.setPreferredSize(new java.awt.Dimension(200, 30));
        brandName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                brandNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                brandNameKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(brandName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(brandButInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(brandButEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(brandButDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(brandButCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(brandCompanyName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(brandCompanyAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(brandCompanyRegNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(brandName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brandCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brandCompanyAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brandCompanyRegNo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brandButInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brandButEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brandButDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brandButCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void brandTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brandTableMouseClicked
        int selectedRow = brandTable.getSelectedRow();
        brandId = Integer.parseInt(brandTable.getValueAt(selectedRow, 0).toString());
        String name = brandTable.getValueAt(selectedRow, 1).toString();
        String companyName = brandTable.getValueAt(selectedRow, 2).toString();
        String companyAddress = brandTable.getValueAt(selectedRow, 3).toString();
        String companyRegNO = brandTable.getValueAt(selectedRow, 4).toString();

        brandName.setText(name);
        brandCompanyName.setText(companyName);
        brandCompanyAddress.setText(companyAddress);
        brandCompanyRegNo.setText(companyRegNO);
    }//GEN-LAST:event_brandTableMouseClicked

    private void brandSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brandSearchActionPerformed

    private void brandSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_brandSearchKeyReleased
        String query = "select * from brand where BrandName like '%" + brandSearch.getText() + "%' and status=1";
        fillBrandTable(query);
    }//GEN-LAST:event_brandSearchKeyReleased

    private void brandButInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandButInsertActionPerformed
        if (validateForm()) {
            String name = brandName.getText();
            String companyName = brandCompanyName.getText();
            String companyAddress = brandCompanyAddress.getText();
            String companyRegNO = brandCompanyRegNo.getText();

            String query = "INSERT INTO `brand`(`BrandName`, `CompanyName`, `CompanyAddress`, `CompanyRegNo`) "
                    + "VALUES ('" + name + "','" + companyName + "','" + companyAddress + "','" + companyRegNO + "')";
            try {
                DbConnect.pushToDB(query);
                clearBrandPanel();
            } catch (ClassNotFoundException ex) {
                ex.printStackTrace();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Form Validation Failed", "Validation Failed", 1);
        }
    }//GEN-LAST:event_brandButInsertActionPerformed

    private void brandButEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandButEditActionPerformed
        if (validateForm()) {
            String name = brandName.getText();
            String companyName = brandCompanyName.getText();
            String companyAddress = brandCompanyAddress.getText();
            String companyRegNO = brandCompanyRegNo.getText();

            String query = "UPDATE `brand` SET `BrandName`='" + name + "',`CompanyName`='" + companyName + "',"
                    + "`CompanyAddress`='" + companyAddress + "',`CompanyRegNo`='" + companyRegNO + "' WHERE `Id`=" + brandId;
            try {
                DbConnect.pushToDB(query);
                clearBrandPanel();
            } catch (ClassNotFoundException ex) {
                ex.printStackTrace();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Form Validation Failed", "Validation Failed", 1);
        }
    }//GEN-LAST:event_brandButEditActionPerformed

    private void brandButDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandButDeleteActionPerformed
        String query = "UPDATE `brand` SET `Status`=0 WHERE `Id`=" + brandId;
        try {
            DbConnect.pushToDB(query);
            clearBrandPanel();
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_brandButDeleteActionPerformed

    private void brandButCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandButCancelActionPerformed
        clearBrandPanel();
    }//GEN-LAST:event_brandButCancelActionPerformed

    private void brandNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_brandNameKeyReleased

    }//GEN-LAST:event_brandNameKeyReleased

    private void brandNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_brandNameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (Validate.isText(brandName.getText().toString())) {
                brandCompanyName.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Not Text", "Validation Failed", 1);
            }
        }
    }//GEN-LAST:event_brandNameKeyPressed

    private void brandCompanyNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_brandCompanyNameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (Validate.isText(brandCompanyName.getText().toString())) {
                brandCompanyAddress.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Not Text", "Validation Failed", 1);
            }
        }
    }//GEN-LAST:event_brandCompanyNameKeyPressed

    private void brandCompanyAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_brandCompanyAddressKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (Validate.isText(brandCompanyAddress.getText().toString())) {
                brandCompanyRegNo.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Not Text", "Validation Failed", 1);
            }
        }
    }//GEN-LAST:event_brandCompanyAddressKeyPressed

    private void brandCompanyRegNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_brandCompanyRegNoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!Validate.isText(brandCompanyRegNo.getText().toString())) {
                JOptionPane.showMessageDialog(null, "Not Text", "Validation Failed", 1);
            }
        }
    }//GEN-LAST:event_brandCompanyRegNoKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brandButCancel;
    private javax.swing.JButton brandButDelete;
    private javax.swing.JButton brandButEdit;
    private javax.swing.JButton brandButInsert;
    private app.bolivia.swing.JCTextField brandCompanyAddress;
    private app.bolivia.swing.JCTextField brandCompanyName;
    private app.bolivia.swing.JCTextField brandCompanyRegNo;
    private app.bolivia.swing.JCTextField brandName;
    private app.bolivia.swing.JCTextField brandSearch;
    private rojeru_san.complementos.RSTableMetro brandTable;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
