/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.xpos.gui;

/**
 *
 * @author Jamit
 */
public class Brand extends javax.swing.JPanel {

    /**
     * Creates new form Brand
     */
    public Brand() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        productTable = new rojeru_san.complementos.RSTableMetro();
        prodSearch = new app.bolivia.swing.JCTextField();
        jPanel10 = new javax.swing.JPanel();
        prodDescription = new app.bolivia.swing.JCTextField();
        prodPurchPrice = new app.bolivia.swing.JCTextField();
        prodRetailPrice = new app.bolivia.swing.JCTextField();
        prodButInsert = new javax.swing.JButton();
        prodButEdit = new javax.swing.JButton();
        prodButDelete = new javax.swing.JButton();
        prodButCancel = new javax.swing.JButton();
        prodBarcode = new app.bolivia.swing.JCTextField();
        prodRetailPrice1 = new app.bolivia.swing.JCTextField();
        prodPurchPrice1 = new app.bolivia.swing.JCTextField();
        prodDescription1 = new app.bolivia.swing.JCTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setBackground(new java.awt.Color(26, 140, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("BRAND ");
        jLabel6.setOpaque(true);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Brand", "Company", "Company Address", "Company Reg NO", "Distributor", "Distributor Address", "Distributor Reg NO"
            }
        ));
        productTable.setColorBackgoundHead(new java.awt.Color(26, 140, 255));
        productTable.setFuenteHead(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        productTable.setRowHeight(25);
        productTable.setRowMargin(0);
        productTable.setSelectionBackground(new java.awt.Color(0, 60, 128));
        productTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(productTable);

        prodSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        prodSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        prodSearch.setPhColor(new java.awt.Color(0, 51, 255));
        prodSearch.setPlaceholder("Search");
        prodSearch.setPreferredSize(new java.awt.Dimension(200, 30));
        prodSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodSearchActionPerformed(evt);
            }
        });
        prodSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                prodSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
                    .addComponent(prodSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(prodSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        prodDescription.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Company Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        prodDescription.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        prodDescription.setPhColor(new java.awt.Color(0, 51, 255));
        prodDescription.setPlaceholder("Company Name");
        prodDescription.setPreferredSize(new java.awt.Dimension(200, 30));

        prodPurchPrice.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Company Address", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        prodPurchPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        prodPurchPrice.setPhColor(new java.awt.Color(0, 51, 255));
        prodPurchPrice.setPlaceholder("Company Address");
        prodPurchPrice.setPreferredSize(new java.awt.Dimension(200, 30));

        prodRetailPrice.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Company Register NO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        prodRetailPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        prodRetailPrice.setPhColor(new java.awt.Color(0, 51, 255));
        prodRetailPrice.setPlaceholder("Company Register NO");
        prodRetailPrice.setPreferredSize(new java.awt.Dimension(200, 30));

        prodButInsert.setBackground(new java.awt.Color(0, 60, 128));
        prodButInsert.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        prodButInsert.setForeground(new java.awt.Color(255, 255, 255));
        prodButInsert.setText("INSERT");
        prodButInsert.setBorder(null);
        prodButInsert.setFocusPainted(false);
        prodButInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodButInsertActionPerformed(evt);
            }
        });

        prodButEdit.setBackground(new java.awt.Color(0, 60, 128));
        prodButEdit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        prodButEdit.setForeground(new java.awt.Color(255, 255, 255));
        prodButEdit.setText("EDIT");
        prodButEdit.setBorder(null);
        prodButEdit.setFocusPainted(false);
        prodButEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodButEditActionPerformed(evt);
            }
        });

        prodButDelete.setBackground(new java.awt.Color(0, 60, 128));
        prodButDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        prodButDelete.setForeground(new java.awt.Color(255, 255, 255));
        prodButDelete.setText("DELETE");
        prodButDelete.setBorder(null);
        prodButDelete.setFocusPainted(false);
        prodButDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodButDeleteActionPerformed(evt);
            }
        });

        prodButCancel.setBackground(new java.awt.Color(0, 60, 128));
        prodButCancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        prodButCancel.setForeground(new java.awt.Color(255, 255, 255));
        prodButCancel.setText("CANCEL");
        prodButCancel.setBorder(null);
        prodButCancel.setFocusPainted(false);
        prodButCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodButCancelActionPerformed(evt);
            }
        });

        prodBarcode.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Brand Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        prodBarcode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        prodBarcode.setPhColor(new java.awt.Color(0, 51, 255));
        prodBarcode.setPlaceholder("Brand Name");
        prodBarcode.setPreferredSize(new java.awt.Dimension(200, 30));

        prodRetailPrice1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Distributor Register NO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        prodRetailPrice1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        prodRetailPrice1.setPhColor(new java.awt.Color(0, 51, 255));
        prodRetailPrice1.setPlaceholder("Distributor Register NO");
        prodRetailPrice1.setPreferredSize(new java.awt.Dimension(200, 30));

        prodPurchPrice1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Distributor Address", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        prodPurchPrice1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        prodPurchPrice1.setPhColor(new java.awt.Color(0, 51, 255));
        prodPurchPrice1.setPlaceholder("Distributor Address");
        prodPurchPrice1.setPreferredSize(new java.awt.Dimension(200, 30));

        prodDescription1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Distributor Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        prodDescription1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        prodDescription1.setPhColor(new java.awt.Color(0, 51, 255));
        prodDescription1.setPlaceholder("Distributor Name");
        prodDescription1.setPreferredSize(new java.awt.Dimension(200, 30));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(prodBarcode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(prodButInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(prodButEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(prodButDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(prodButCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(prodDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prodPurchPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prodRetailPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prodDescription1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prodPurchPrice1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prodRetailPrice1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(prodBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodPurchPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodRetailPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodDescription1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodPurchPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodRetailPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodButInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prodButEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prodButDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prodButCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void productTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productTableMouseClicked
        
    }//GEN-LAST:event_productTableMouseClicked

    private void prodSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodSearchActionPerformed

    private void prodSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prodSearchKeyReleased
       
    }//GEN-LAST:event_prodSearchKeyReleased

    private void prodButInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodButInsertActionPerformed
        
    }//GEN-LAST:event_prodButInsertActionPerformed

    private void prodButEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodButEditActionPerformed
        
    }//GEN-LAST:event_prodButEditActionPerformed

    private void prodButDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodButDeleteActionPerformed
        
    }//GEN-LAST:event_prodButDeleteActionPerformed

    private void prodButCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodButCancelActionPerformed
        
    }//GEN-LAST:event_prodButCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private app.bolivia.swing.JCTextField prodBarcode;
    private javax.swing.JButton prodButCancel;
    private javax.swing.JButton prodButDelete;
    private javax.swing.JButton prodButEdit;
    private javax.swing.JButton prodButInsert;
    private app.bolivia.swing.JCTextField prodDescription;
    private app.bolivia.swing.JCTextField prodDescription1;
    private app.bolivia.swing.JCTextField prodPurchPrice;
    private app.bolivia.swing.JCTextField prodPurchPrice1;
    private app.bolivia.swing.JCTextField prodRetailPrice;
    private app.bolivia.swing.JCTextField prodRetailPrice1;
    private app.bolivia.swing.JCTextField prodSearch;
    private rojeru_san.complementos.RSTableMetro productTable;
    // End of variables declaration//GEN-END:variables
}
