/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.xpos.gui;

import com.xpos.commons.SystemLogger;
import com.xpos.commons.Validate;
import com.xpos.database.DbConnect;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;

/**
 *
 * @author Jamit
 */
public class Category extends javax.swing.JPanel {

    DefaultTableModel tablemodel;
    DateTimeFormatter defaultDateFormat = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    private static Logger log;

    int catId;

    /**
     * Creates new form Category
     */
    public Category() {
        initComponents();
        SystemLogger.initLogger();
        log = Logger.getLogger(Category.class);
        clearCategoryPanel();
        log.info("category panel running...");
    }

    private boolean validateForm() {
        log.info("validate category form");
        return Validate.isText(catDescription.getText().toString());
    }

    public void clearCategoryPanel() {
        log.info("clear category panel");
        catDescription.setText("");
        catSpecNote.setText("");
        catSearch.setText("");
        fillCategoryTable(null);
    }

    private void fillCategoryTable(String query) {
        log.info("fill category table, query : " + query);
        tablemodel = (DefaultTableModel) categoryTable.getModel();
        tablemodel.setRowCount(0);
        if (query == null) {
            log.info("query null then assigning query");
            query = "SELECT `Id`, `Description`, `Note` FROM `category` where status=1";
        }
        try {
            log.info("executing query");
            ResultSet rs = DbConnect.getFromDB(query);
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getInt("Id"));
                v.add(rs.getString("Description"));
                v.add(rs.getString("Note"));

                tablemodel.addRow(v);
            }
            log.info("table filled with data");
        } catch (SQLException e) {
            log.error("table filling failed", e);
        } catch (ClassNotFoundException e) {
            log.error("table filling failed", e);
        } catch (Exception e) {
            log.error("table filling failed", e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        categoryTable = new rojeru_san.complementos.RSTableMetro();
        catSearch = new app.bolivia.swing.JCTextField();
        jPanel10 = new javax.swing.JPanel();
        catDescription = new app.bolivia.swing.JCTextField();
        catSpecNote = new app.bolivia.swing.JCTextField();
        catButInsert = new javax.swing.JButton();
        catButEdit = new javax.swing.JButton();
        catButDelete = new javax.swing.JButton();
        catButCancel = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setBackground(new java.awt.Color(26, 140, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CATEGORY");
        jLabel6.setOpaque(true);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        categoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Description", "Special Note"
            }
        ));
        categoryTable.setColorBackgoundHead(new java.awt.Color(26, 140, 255));
        categoryTable.setFuenteHead(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        categoryTable.setRowHeight(25);
        categoryTable.setRowMargin(0);
        categoryTable.setSelectionBackground(new java.awt.Color(0, 60, 128));
        categoryTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                categoryTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(categoryTable);

        catSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        catSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        catSearch.setPhColor(new java.awt.Color(0, 51, 255));
        catSearch.setPlaceholder("Search");
        catSearch.setPreferredSize(new java.awt.Dimension(200, 30));
        catSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catSearchActionPerformed(evt);
            }
        });
        catSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                catSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
                    .addComponent(catSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(catSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        catDescription.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Description", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        catDescription.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        catDescription.setPhColor(new java.awt.Color(0, 51, 255));
        catDescription.setPlaceholder("Description");
        catDescription.setPreferredSize(new java.awt.Dimension(200, 30));
        catDescription.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                catDescriptionKeyPressed(evt);
            }
        });

        catSpecNote.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Special Note", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        catSpecNote.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        catSpecNote.setPhColor(new java.awt.Color(0, 51, 255));
        catSpecNote.setPlaceholder("Special Note (Can be Null)");
        catSpecNote.setPreferredSize(new java.awt.Dimension(200, 30));

        catButInsert.setBackground(new java.awt.Color(0, 60, 128));
        catButInsert.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        catButInsert.setForeground(new java.awt.Color(255, 255, 255));
        catButInsert.setText("INSERT");
        catButInsert.setBorder(null);
        catButInsert.setFocusPainted(false);
        catButInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catButInsertActionPerformed(evt);
            }
        });

        catButEdit.setBackground(new java.awt.Color(0, 60, 128));
        catButEdit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        catButEdit.setForeground(new java.awt.Color(255, 255, 255));
        catButEdit.setText("EDIT");
        catButEdit.setBorder(null);
        catButEdit.setFocusPainted(false);
        catButEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catButEditActionPerformed(evt);
            }
        });

        catButDelete.setBackground(new java.awt.Color(0, 60, 128));
        catButDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        catButDelete.setForeground(new java.awt.Color(255, 255, 255));
        catButDelete.setText("DELETE");
        catButDelete.setBorder(null);
        catButDelete.setFocusPainted(false);
        catButDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catButDeleteActionPerformed(evt);
            }
        });

        catButCancel.setBackground(new java.awt.Color(0, 60, 128));
        catButCancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        catButCancel.setForeground(new java.awt.Color(255, 255, 255));
        catButCancel.setText("CANCEL");
        catButCancel.setBorder(null);
        catButCancel.setFocusPainted(false);
        catButCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catButCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(catDescription, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                    .addComponent(catSpecNote, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(catButInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(catButEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(catButDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(catButCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(catDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(catSpecNote, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(catButInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(catButEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(catButDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(catButCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void categoryTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoryTableMouseClicked
        log.info("user presses category table row");
        int selectedRow = categoryTable.getSelectedRow();
        catId = Integer.parseInt(categoryTable.getValueAt(selectedRow, 0).toString());
        catDescription.setText(categoryTable.getValueAt(selectedRow, 1).toString());
        catSpecNote.setText(categoryTable.getValueAt(selectedRow, 2).toString());
    }//GEN-LAST:event_categoryTableMouseClicked

    private void catSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catSearchActionPerformed
         //TODO add your handling code here:
    }//GEN-LAST:event_catSearchActionPerformed

    private void catSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_catSearchKeyReleased
        String query = "select * from category where description like '%" + catSearch.getText() + "%' and status=1";
        fillCategoryTable(query);
        log.info("category search, query : " + query);
    }//GEN-LAST:event_catSearchKeyReleased

    private void catButInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catButInsertActionPerformed
        log.info("user presses insert button");
        if (validateForm()) {
            log.info("validate process passed");
            String description = catDescription.getText();
            String note = catSpecNote.getText();
            String query = "INSERT INTO `category`(`Description`, `Note`) VALUES ('" + description + "','" + note + "')";
            try {
                DbConnect.pushToDB(query);
                clearCategoryPanel();
                log.info("execute insert query");
            } catch (ClassNotFoundException ex) {
                log.error("category insert failed", ex);
            } catch (SQLException ex) {
                log.error("category insert failed", ex);
            } catch (Exception ex) {
                log.error("category insert failed", ex);
            }
        } else {
            log.info("validate process failed");
            JOptionPane.showMessageDialog(null, "Form Validation Failed", "Validation Failed", 1);
        }
    }//GEN-LAST:event_catButInsertActionPerformed

    private void catButEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catButEditActionPerformed
        log.info("user presses edit button");
        if (validateForm()) {
            log.info("validate process passed");
            String description = catDescription.getText();
            String note = catSpecNote.getText();
            String query = "UPDATE `category` SET `Description`='" + description + "',`Note`='" + note + "' WHERE Id=" + catId;
            try {
                DbConnect.pushToDB(query);
                clearCategoryPanel();
                log.info("execute insert query");
            } catch (ClassNotFoundException ex) {
                log.error("category edit failed", ex);
            } catch (SQLException ex) {
                log.error("category edit failed", ex);
            } catch (Exception ex) {
                log.error("category edit failed", ex);
            }
        } else {
            log.info("validate process failed");
            JOptionPane.showMessageDialog(null, "Form Validation Failed", "Validation Failed", 1);
        }
    }//GEN-LAST:event_catButEditActionPerformed

    private void catButDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catButDeleteActionPerformed
        log.info("user presses delete button");
        String query = "UPDATE `category` SET `Status`=0 WHERE Id=" + catId;
        try {
            DbConnect.pushToDB(query);
            clearCategoryPanel();
            log.info("push delete query");
        } catch (ClassNotFoundException ex) {
            log.error("category delete failed", ex);
        } catch (SQLException ex) {
            log.error("category delete failed", ex);
        } catch (Exception ex) {
            log.error("category delete failed", ex);
        }
    }//GEN-LAST:event_catButDeleteActionPerformed

    private void catButCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catButCancelActionPerformed
         log.info("user presses cancel button");clearCategoryPanel();
    }//GEN-LAST:event_catButCancelActionPerformed

    private void catDescriptionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_catDescriptionKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            log.info("user presses enter on catdescription text field");
            if (Validate.isText(catDescription.getText().toString())) {
                log.info("validate process passed");
                catSpecNote.requestFocus();
            } else {
                log.info("validate process failed");
                JOptionPane.showMessageDialog(null, "Not Text", "Validation Failed", 1);
            }
        }        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_catDescriptionKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton catButCancel;
    private javax.swing.JButton catButDelete;
    private javax.swing.JButton catButEdit;
    private javax.swing.JButton catButInsert;
    private app.bolivia.swing.JCTextField catDescription;
    private app.bolivia.swing.JCTextField catSearch;
    private app.bolivia.swing.JCTextField catSpecNote;
    private rojeru_san.complementos.RSTableMetro categoryTable;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
