/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.xpos.gui;

import com.xpos.commons.Validate;
import com.xpos.database.DbConnect;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jamit
 */
public class Customer extends javax.swing.JPanel {

    DefaultTableModel tablemodel;
    DateTimeFormatter defaultDateFormat = DateTimeFormatter.ofPattern("yyyy-MM-dd");

    int customerId;

    /**
     * Creates new form Customer
     */
    public Customer() {
        initComponents();
        fillCustomerTable(null);
    }

    private boolean validateForm() {
        return Validate.isText(customerAddress.getText().toString())
                && Validate.isTelephone(customerTeleNumber.getText().toString())
                && Validate.isNIC(customerNIC.getText().toString())
                && Validate.isName(customerName.getText().toString())
                && Validate.isDate(customerDOB.getDate().toString())
                && Validate.isDate(customerJoinedDate.getDate().toString())
                && Validate.isEmail(customerEmail.getText().toString());
    }

    public void clearCustomerPanel() {
        customerName.setText("");
        customerAddress.setText("");
        customerTeleNumber.setText("");
        customerNIC.setText("");
        customerDOB.setDate(null);
        customerJoinedDate.setDate(null);
        customerEmail.setText("");
        customerGenMale.setSelected(true);
        customerSearch.setText("");
        fillCustomerTable(null);
    }

    private void fillCustomerTable(String query) {
        tablemodel = (DefaultTableModel) customerTable.getModel();
        tablemodel.setRowCount(0);
        if (query == null) {
            query = "SELECT * FROM `customer` WHERE STATUS=1";
        }
        try {
            ResultSet rs = DbConnect.getFromDB(query);
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getInt("Id"));
                v.add(rs.getString("Name"));
                v.add(rs.getString("Address"));
                v.add(rs.getString("TelephoneNo"));
                v.add(rs.getString("NIC"));
                v.add(rs.getDate("DOB"));
                v.add(rs.getDate("JoinedDate"));
                v.add(rs.getString("Email"));
                v.add(rs.getString("Gender") != null
                        ? (rs.getString("Gender").equals("M") ? "Male" : "Female") : (""));

                tablemodel.addRow(v);
            }
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender = new javax.swing.ButtonGroup();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        customerButInsert = new javax.swing.JButton();
        customerButEdit = new javax.swing.JButton();
        customerButDelete = new javax.swing.JButton();
        customerButCancel = new javax.swing.JButton();
        customerName = new app.bolivia.swing.JCTextField();
        customerAddress = new app.bolivia.swing.JCTextField();
        customerTeleNumber = new app.bolivia.swing.JCTextField();
        customerNIC = new app.bolivia.swing.JCTextField();
        customerDOB = new com.toedter.calendar.JDateChooser();
        customerJoinedDate = new com.toedter.calendar.JDateChooser();
        customerEmail = new app.bolivia.swing.JCTextField();
        jPanel6 = new javax.swing.JPanel();
        customerGenMale = new javax.swing.JRadioButton();
        customerGenFemale = new javax.swing.JRadioButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        customerTable = new rojeru_san.complementos.RSTableMetro();
        customerSearch = new app.bolivia.swing.JCTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setBackground(new java.awt.Color(26, 140, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("CUSTOMER");
        jLabel7.setOpaque(true);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        customerButInsert.setBackground(new java.awt.Color(0, 60, 128));
        customerButInsert.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        customerButInsert.setForeground(new java.awt.Color(255, 255, 255));
        customerButInsert.setText("INSERT");
        customerButInsert.setBorder(null);
        customerButInsert.setFocusPainted(false);
        customerButInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerButInsertActionPerformed(evt);
            }
        });

        customerButEdit.setBackground(new java.awt.Color(0, 60, 128));
        customerButEdit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        customerButEdit.setForeground(new java.awt.Color(255, 255, 255));
        customerButEdit.setText("EDIT");
        customerButEdit.setBorder(null);
        customerButEdit.setFocusPainted(false);
        customerButEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerButEditActionPerformed(evt);
            }
        });

        customerButDelete.setBackground(new java.awt.Color(0, 60, 128));
        customerButDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        customerButDelete.setForeground(new java.awt.Color(255, 255, 255));
        customerButDelete.setText("DELETE");
        customerButDelete.setBorder(null);
        customerButDelete.setFocusPainted(false);
        customerButDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerButDeleteActionPerformed(evt);
            }
        });

        customerButCancel.setBackground(new java.awt.Color(0, 60, 128));
        customerButCancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        customerButCancel.setForeground(new java.awt.Color(255, 255, 255));
        customerButCancel.setText("CANCEL");
        customerButCancel.setBorder(null);
        customerButCancel.setFocusPainted(false);
        customerButCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerButCancelActionPerformed(evt);
            }
        });

        customerName.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        customerName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customerName.setPhColor(new java.awt.Color(0, 51, 255));
        customerName.setPlaceholder("Name");
        customerName.setPreferredSize(new java.awt.Dimension(200, 30));
        customerName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                customerNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                customerNameKeyReleased(evt);
            }
        });

        customerAddress.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Address", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        customerAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customerAddress.setPhColor(new java.awt.Color(0, 51, 255));
        customerAddress.setPlaceholder("Address");
        customerAddress.setPreferredSize(new java.awt.Dimension(200, 30));
        customerAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                customerAddressKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                customerAddressKeyReleased(evt);
            }
        });

        customerTeleNumber.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Telephone Number", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        customerTeleNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customerTeleNumber.setPhColor(new java.awt.Color(0, 51, 255));
        customerTeleNumber.setPlaceholder("Telephone Number");
        customerTeleNumber.setPreferredSize(new java.awt.Dimension(200, 30));
        customerTeleNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                customerTeleNumberKeyPressed(evt);
            }
        });

        customerNIC.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "NIC", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        customerNIC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customerNIC.setPhColor(new java.awt.Color(0, 51, 255));
        customerNIC.setPlaceholder("NIC");
        customerNIC.setPreferredSize(new java.awt.Dimension(200, 30));
        customerNIC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                customerNICKeyPressed(evt);
            }
        });

        customerDOB.setBackground(new java.awt.Color(255, 255, 255));
        customerDOB.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Date Of Birth", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        customerDOB.setDateFormatString("yyyy-MM-dd");
        customerDOB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customerDOB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                customerDOBKeyPressed(evt);
            }
        });

        customerJoinedDate.setBackground(new java.awt.Color(255, 255, 255));
        customerJoinedDate.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Joined Date", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        customerJoinedDate.setDateFormatString("yyyy-MM-dd");
        customerJoinedDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customerJoinedDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                customerJoinedDateKeyPressed(evt);
            }
        });

        customerEmail.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Email", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        customerEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customerEmail.setPhColor(new java.awt.Color(0, 51, 255));
        customerEmail.setPlaceholder("Email");
        customerEmail.setPreferredSize(new java.awt.Dimension(200, 30));
        customerEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                customerEmailKeyPressed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Gender", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N

        customerGenMale.setBackground(new java.awt.Color(255, 255, 255));
        gender.add(customerGenMale);
        customerGenMale.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        customerGenMale.setForeground(new java.awt.Color(26, 140, 255));
        customerGenMale.setSelected(true);
        customerGenMale.setText("Male");
        customerGenMale.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                customerGenMaleKeyPressed(evt);
            }
        });

        customerGenFemale.setBackground(new java.awt.Color(255, 255, 255));
        gender.add(customerGenFemale);
        customerGenFemale.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        customerGenFemale.setForeground(new java.awt.Color(26, 140, 255));
        customerGenFemale.setText("Female");
        customerGenFemale.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                customerGenFemaleKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(customerGenMale)
                .addGap(18, 18, 18)
                .addComponent(customerGenFemale)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerGenMale)
                    .addComponent(customerGenFemale))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(customerButInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(customerButEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(customerButDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(customerButCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(customerEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customerJoinedDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customerDOB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customerNIC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customerTeleNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customerAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customerName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customerName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerTeleNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerJoinedDate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerButInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerButEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerButDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerButCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Address", "Telephone No", "NIC", "Date Of Birth", "Joined Date", "Email", "Gender"
            }
        ));
        customerTable.setColorBackgoundHead(new java.awt.Color(26, 140, 255));
        customerTable.setFuenteHead(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customerTable.setRowHeight(25);
        customerTable.setRowMargin(0);
        customerTable.setSelectionBackground(new java.awt.Color(0, 60, 128));
        customerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(customerTable);

        customerSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        customerSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customerSearch.setPhColor(new java.awt.Color(0, 51, 255));
        customerSearch.setPlaceholder("Search");
        customerSearch.setPreferredSize(new java.awt.Dimension(200, 30));
        customerSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                customerSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(customerSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customerSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1240, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void customerButInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerButInsertActionPerformed
        String name = customerName.getText();
        String address = customerAddress.getText();
        String teleNumber = customerTeleNumber.getText();
        String NIC = customerNIC.getText();
        LocalDate DOB = customerDOB.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate joinedDate = customerJoinedDate.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        String email = customerEmail.getText();
        String gender = (customerGenMale.isSelected()) ? "M" : "F";

        String query = "INSERT INTO `customer`(`Name`, `Address`, `TelephoneNo`,"
                + " `NIC`, `DOB`, `JoinedDate`, `Email`, `Gender`) VALUES ('" + name + "',"
                + "'" + address + "','" + teleNumber + "','" + NIC + "','" + DOB.format(defaultDateFormat) + "','"
                + joinedDate.format(defaultDateFormat) + "','" + email + "','" + gender + "')";
        try {
            DbConnect.pushToDB(query);
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
        clearCustomerPanel();
    }//GEN-LAST:event_customerButInsertActionPerformed

    private void customerButEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerButEditActionPerformed
        String name = customerName.getText();
        String address = customerAddress.getText();
        String teleNumber = customerTeleNumber.getText();
        String NIC = customerNIC.getText();
        LocalDate DOB = customerDOB.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate joinedDate = customerJoinedDate.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        String email = customerEmail.getText();
        String gender = (customerGenMale.isSelected()) ? "M" : "F";

        String query = "UPDATE customer SET Name='" + name + "',Address='" + address + "',"
                + "TelephoneNo='" + teleNumber + "',NIC='" + NIC + "',DOB='" + DOB.format(defaultDateFormat) + "',JoinedDate='" + joinedDate.format(defaultDateFormat) + "',"
                + "Email='" + email + "',Gender='" + gender + "' WHERE Id=" + customerId;
        try {
            DbConnect.pushToDB(query);
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
        clearCustomerPanel();
    }//GEN-LAST:event_customerButEditActionPerformed

    private void customerButDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerButDeleteActionPerformed
        String query = "UPDATE customer SET Status=0 WHERE Id=" + customerId;
        try {
            DbConnect.pushToDB(query);
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
        clearCustomerPanel();
    }//GEN-LAST:event_customerButDeleteActionPerformed

    private void customerButCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerButCancelActionPerformed
        clearCustomerPanel();        // TODO add your handling code here:
    }//GEN-LAST:event_customerButCancelActionPerformed

    private void customerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerTableMouseClicked
        int selectedRow = customerTable.getSelectedRow();
        customerId = Integer.parseInt(customerTable.getValueAt(selectedRow, 0).toString());

        try {
            customerName.setText(customerTable.getValueAt(selectedRow, 1).toString());
            customerAddress.setText(customerTable.getValueAt(selectedRow, 2).toString());
            customerTeleNumber.setText(customerTable.getValueAt(selectedRow, 3).toString());
            customerNIC.setText(customerTable.getValueAt(selectedRow, 4).toString());
            customerDOB.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(customerTable.getValueAt(selectedRow, 5).toString()));
            customerJoinedDate.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(customerTable.getValueAt(selectedRow, 6).toString()));
            customerEmail.setText(customerTable.getValueAt(selectedRow, 7).toString());
            customerGenMale.setSelected(customerTable.getValueAt(selectedRow, 8).toString().equals("Male"));
            customerGenFemale.setSelected(customerTable.getValueAt(selectedRow, 8).toString().equals("Female"));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_customerTableMouseClicked

    private void customerSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customerSearchKeyReleased
        String query = "SELECT * from customer WHERE Name LIKE '%" + customerSearch.getText().toString() + "%' and Status=1";
        fillCustomerTable(query);
    }//GEN-LAST:event_customerSearchKeyReleased

    private void customerNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customerNameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_customerNameKeyReleased

    private void customerAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customerAddressKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (Validate.isText(customerAddress.getText().toString())) {
                customerTeleNumber.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Not Text", "Validation Failed", 1);
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_customerAddressKeyPressed

    private void customerTeleNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customerTeleNumberKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (Validate.isTelephone(customerTeleNumber.getText().toString())) {
                customerNIC.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Not Text", "Validation Failed", 1);
            }
        }
    }//GEN-LAST:event_customerTeleNumberKeyPressed

    private void customerNICKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customerNICKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (Validate.isNIC(customerNIC.getText().toString())) {
                customerDOB.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Not Text", "Validation Failed", 1);
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_customerNICKeyPressed

    private void customerNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customerNameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (Validate.isName(customerName.getText().toString())) {
                customerAddress.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Not Text", "Validation Failed", 1);
            }
        }          // TODO add your handling code here:
    }//GEN-LAST:event_customerNameKeyPressed

    private void customerDOBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customerDOBKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (Validate.isDate(customerDOB.getDate().toString())) {
                customerJoinedDate.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Not Text", "Validation Failed", 1);
            }
        } // TODO add your handling code here:
    }//GEN-LAST:event_customerDOBKeyPressed

    private void customerJoinedDateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customerJoinedDateKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (Validate.isDate(customerJoinedDate.getDate().toString())) {
                customerEmail.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Not Text", "Validation Failed", 1);
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_customerJoinedDateKeyPressed

    private void customerEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customerEmailKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (Validate.isEmail(customerEmail.getText().toString())) {
                customerGenMale.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Not Text", "Validation Failed", 1);
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_customerEmailKeyPressed

    private void customerGenMaleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customerGenMaleKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            customerButInsert.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            customerGenFemale.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_customerGenMaleKeyPressed

    private void customerGenFemaleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customerGenFemaleKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            customerButInsert.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            customerGenMale.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_customerGenFemaleKeyPressed

    private void customerAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customerAddressKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_customerAddressKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.bolivia.swing.JCTextField customerAddress;
    private javax.swing.JButton customerButCancel;
    private javax.swing.JButton customerButDelete;
    private javax.swing.JButton customerButEdit;
    private javax.swing.JButton customerButInsert;
    private com.toedter.calendar.JDateChooser customerDOB;
    private app.bolivia.swing.JCTextField customerEmail;
    private javax.swing.JRadioButton customerGenFemale;
    private javax.swing.JRadioButton customerGenMale;
    private com.toedter.calendar.JDateChooser customerJoinedDate;
    private app.bolivia.swing.JCTextField customerNIC;
    private app.bolivia.swing.JCTextField customerName;
    private app.bolivia.swing.JCTextField customerSearch;
    private rojeru_san.complementos.RSTableMetro customerTable;
    private app.bolivia.swing.JCTextField customerTeleNumber;
    private javax.swing.ButtonGroup gender;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
