/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.xpos.gui;

import com.xpos.database.DbConnect;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jamit
 */
public class Employee extends javax.swing.JPanel {

    DefaultTableModel tablemodel;
    DateTimeFormatter defaultDateFormat = DateTimeFormatter.ofPattern("yyyy-MM-dd");

    int employeeId;

    /**
     * Creates new form Employee
     */
    public Employee() {
        initComponents();
        fillEmpTable(null);
        loadEmpPosCombo();
    }

    public void clearEmployePanel() {
        empName.setText("");
        empAddress.setText("");
        empTeleNumber.setText("");
        empNIC.setText("");
        empDOB.setDate(null);
        empJoinedDate.setDate(null);
        empEmail.setText("");
        empGenMale.setSelected(true);
        empPositionCombo.setSelectedIndex(0);
        fillEmpTable(null);
        loadEmpPosCombo();
    }

    public void loadEmpPosCombo() {
        try {
            ResultSet rs = DbConnect.getFromDB("select Id,PositionName from employeeposition where status=1");
            Vector v = new Vector();
            v.add("Select Position");
            while (rs.next()) {
                String position = rs.getString("Id") + " - " + rs.getString("PositionName");
                v.add(position);
            }
            empPositionCombo.setModel(new DefaultComboBoxModel(v));
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void fillEmpTable(String query) {
        tablemodel = (DefaultTableModel) empTable.getModel();
        tablemodel.setRowCount(0);
        if (query == null) {
            query = "SELECT * FROM employee join employeeposition on employee.EmployeePosition_id=employeeposition.Id  where employee.status=1";
        }
        try {
            ResultSet rs = DbConnect.getFromDB(query);
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getInt("Id"));
                v.add(rs.getString("Name"));
                v.add(rs.getString("Address"));
                v.add(rs.getString("TelephoneNo"));
                v.add(rs.getString("NIC"));
                v.add(rs.getDate("DOB"));
                v.add(rs.getDate("JoinedDate"));
                v.add(rs.getString("Email"));
                v.add(rs.getString("Gender").equals("M") ? "Male" : "Female");
                v.add(rs.getInt("employeeposition.Id"));
                v.add(rs.getString("PositionName"));

                tablemodel.addRow(v);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender = new javax.swing.ButtonGroup();
        jLabel9 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        empButInsert = new javax.swing.JButton();
        empButEdit = new javax.swing.JButton();
        empButDelete = new javax.swing.JButton();
        empButCancel = new javax.swing.JButton();
        empName = new app.bolivia.swing.JCTextField();
        empAddress = new app.bolivia.swing.JCTextField();
        empTeleNumber = new app.bolivia.swing.JCTextField();
        empNIC = new app.bolivia.swing.JCTextField();
        empDOB = new com.toedter.calendar.JDateChooser();
        empJoinedDate = new com.toedter.calendar.JDateChooser();
        empEmail = new app.bolivia.swing.JCTextField();
        jPanel16 = new javax.swing.JPanel();
        empGenMale = new javax.swing.JRadioButton();
        empGenFemale = new javax.swing.JRadioButton();
        empPositionCombo = new javax.swing.JComboBox<>();
        jPanel17 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        empTable = new rojeru_san.complementos.RSTableMetro();
        empSearch = new app.bolivia.swing.JCTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setBackground(new java.awt.Color(26, 140, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("EMPLOYEE");
        jLabel9.setOpaque(true);
        jLabel9.setPreferredSize(new java.awt.Dimension(150, 22));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));

        empButInsert.setBackground(new java.awt.Color(0, 60, 128));
        empButInsert.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        empButInsert.setForeground(new java.awt.Color(255, 255, 255));
        empButInsert.setText("INSERT");
        empButInsert.setBorder(null);
        empButInsert.setFocusPainted(false);
        empButInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empButInsertActionPerformed(evt);
            }
        });

        empButEdit.setBackground(new java.awt.Color(0, 60, 128));
        empButEdit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        empButEdit.setForeground(new java.awt.Color(255, 255, 255));
        empButEdit.setText("EDIT");
        empButEdit.setBorder(null);
        empButEdit.setFocusPainted(false);
        empButEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empButEditActionPerformed(evt);
            }
        });

        empButDelete.setBackground(new java.awt.Color(0, 60, 128));
        empButDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        empButDelete.setForeground(new java.awt.Color(255, 255, 255));
        empButDelete.setText("DELETE");
        empButDelete.setBorder(null);
        empButDelete.setFocusPainted(false);
        empButDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empButDeleteActionPerformed(evt);
            }
        });

        empButCancel.setBackground(new java.awt.Color(0, 60, 128));
        empButCancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        empButCancel.setForeground(new java.awt.Color(255, 255, 255));
        empButCancel.setText("CANCEL");
        empButCancel.setBorder(null);
        empButCancel.setFocusPainted(false);
        empButCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empButCancelActionPerformed(evt);
            }
        });

        empName.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        empName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        empName.setPhColor(new java.awt.Color(0, 51, 255));
        empName.setPlaceholder("Name");
        empName.setPreferredSize(new java.awt.Dimension(200, 30));

        empAddress.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Address", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        empAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        empAddress.setPhColor(new java.awt.Color(0, 51, 255));
        empAddress.setPlaceholder("Address");
        empAddress.setPreferredSize(new java.awt.Dimension(200, 30));

        empTeleNumber.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Telephone Number", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        empTeleNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        empTeleNumber.setPhColor(new java.awt.Color(0, 51, 255));
        empTeleNumber.setPlaceholder("Telephone Number");
        empTeleNumber.setPreferredSize(new java.awt.Dimension(200, 30));

        empNIC.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "NIC", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        empNIC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        empNIC.setPhColor(new java.awt.Color(0, 51, 255));
        empNIC.setPlaceholder("NIC");
        empNIC.setPreferredSize(new java.awt.Dimension(200, 30));

        empDOB.setBackground(new java.awt.Color(255, 255, 255));
        empDOB.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Date Of Birth", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        empDOB.setDateFormatString("yyyy-MM-dd");
        empDOB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        empJoinedDate.setBackground(new java.awt.Color(255, 255, 255));
        empJoinedDate.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Joined Date", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        empJoinedDate.setDateFormatString("yyyy-MM-dd");
        empJoinedDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        empEmail.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Email", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        empEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        empEmail.setPhColor(new java.awt.Color(0, 51, 255));
        empEmail.setPlaceholder("Email");
        empEmail.setPreferredSize(new java.awt.Dimension(200, 30));

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Gender", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N

        empGenMale.setBackground(new java.awt.Color(255, 255, 255));
        gender.add(empGenMale);
        empGenMale.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        empGenMale.setForeground(new java.awt.Color(26, 140, 255));
        empGenMale.setSelected(true);
        empGenMale.setText("Male");

        empGenFemale.setBackground(new java.awt.Color(255, 255, 255));
        gender.add(empGenFemale);
        empGenFemale.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        empGenFemale.setForeground(new java.awt.Color(26, 140, 255));
        empGenFemale.setText("Female");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(empGenMale)
                .addGap(18, 18, 18)
                .addComponent(empGenFemale)
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empGenMale)
                    .addComponent(empGenFemale))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        empPositionCombo.setForeground(new java.awt.Color(26, 140, 255));
        empPositionCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Position" }));
        empPositionCombo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Select Position", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        empPositionCombo.setOpaque(false);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(empEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(empJoinedDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(empDOB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(empNIC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(empTeleNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(empAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(empName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(empButInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(empButEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(empButDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(empButCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(empPositionCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(empName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empTeleNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empJoinedDate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empPositionCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empButInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empButEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empButDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empButCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));

        empTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Address", "Telephone No", "NIC", "Date Of Birth", "Joined Date", "Email", "Gender", "Position ID", "Position"
            }
        ));
        empTable.setColorBackgoundHead(new java.awt.Color(26, 140, 255));
        empTable.setFuenteHead(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        empTable.setRowHeight(25);
        empTable.setRowMargin(0);
        empTable.setSelectionBackground(new java.awt.Color(0, 60, 128));
        empTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empTableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(empTable);

        empSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        empSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        empSearch.setPhColor(new java.awt.Color(0, 51, 255));
        empSearch.setPlaceholder("Search");
        empSearch.setPreferredSize(new java.awt.Dimension(200, 30));
        empSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                empSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addComponent(empSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(empSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1240, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void empButInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empButInsertActionPerformed
        String name = empName.getText();
        String address = empAddress.getText();
        String teleNumber = empTeleNumber.getText();
        String NIC = empNIC.getText();
        LocalDate DOB = empDOB.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate joinedDate = empJoinedDate.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        String email = empEmail.getText();
        String gender = empGenMale.isSelected() ? "M" : "F";
        int positionId = Integer.parseInt(empPositionCombo.getSelectedItem().toString().split(" - ")[0]);

        String query = "INSERT INTO `employee`( `Name`, `Address`, `TelephoneNo`, `NIC`,"
                + " `DOB`, `JoinedDate`, `Email`, `Gender`, `EmployeePosition_id`) VALUES "
                + "('" + name + "','" + address + "','" + teleNumber + "','" + NIC + "','" + DOB.format(defaultDateFormat)
                + "','" + joinedDate.format(defaultDateFormat) + "','" + email + "','" + gender + "'," + positionId + ")";

        try {
            DbConnect.pushToDB(query);
            clearEmployePanel();
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_empButInsertActionPerformed

    private void empButEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empButEditActionPerformed
        String name = empName.getText();
        String address = empAddress.getText();
        String teleNumber = empTeleNumber.getText();
        String NIC = empNIC.getText();
        LocalDate DOB = empDOB.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate joinedDate = empJoinedDate.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        String email = empEmail.getText();
        String gender = empGenMale.isSelected() ? "M" : "F";
        int positionId = Integer.parseInt(empPositionCombo.getSelectedItem().toString().split(" - ")[0]);

        String query = "UPDATE `employee` SET `Name`='" + name + "',`Address`='" + address + "',`TelephoneNo`='" + teleNumber
                + "',`NIC`='" + NIC + "',`DOB`='" + DOB.format(defaultDateFormat) + "',`JoinedDate`='" + joinedDate.format(defaultDateFormat)
                + "',`Email`='" + email + "',`Gender`='" + gender + "',`EmployeePosition_id`=" + positionId + " WHERE Id=" + employeeId;
        try {
            DbConnect.pushToDB(query);
            clearEmployePanel();
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_empButEditActionPerformed

    private void empButDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empButDeleteActionPerformed
        String query = "UPDATE `employee` SET Status=0 WHERE Id=" + employeeId;
        try {
            DbConnect.pushToDB(query);
            clearEmployePanel();
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_empButDeleteActionPerformed

    private void empButCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empButCancelActionPerformed
        clearEmployePanel();
    }//GEN-LAST:event_empButCancelActionPerformed

    private void empTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empTableMouseClicked
        try {
            int selectedRow = empTable.getSelectedRow();
            employeeId = Integer.parseInt(empTable.getValueAt(selectedRow, 0).toString());

            empName.setText(empTable.getValueAt(selectedRow, 1).toString());
            empAddress.setText(empTable.getValueAt(selectedRow, 2).toString());
            empTeleNumber.setText(empTable.getValueAt(selectedRow, 3).toString());
            empNIC.setText(empTable.getValueAt(selectedRow, 4).toString());
            empDOB.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(empTable.getValueAt(selectedRow, 5).toString()));
            empJoinedDate.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(empTable.getValueAt(selectedRow, 6).toString()));
            empEmail.setText(empTable.getValueAt(selectedRow, 7).toString());
            empGenMale.setSelected(empTable.getValueAt(selectedRow, 8).toString().equals("Male"));
            empGenFemale.setSelected(empTable.getValueAt(selectedRow, 8).toString().equals("Female"));
            empPositionCombo.setSelectedItem(empTable.getValueAt(selectedRow, 9).toString() + " - " + empTable.getValueAt(selectedRow, 10).toString());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_empTableMouseClicked

    private void empSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_empSearchKeyReleased
        String query = "SELECT * FROM employee join employeeposition on "
                + "employee.EmployeePosition_id=employeeposition.Id  "
                + "where employee.status=1 and employee.name like '%" + empSearch.getText() + "%'";
        fillEmpTable(query);
    }//GEN-LAST:event_empSearchKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.bolivia.swing.JCTextField empAddress;
    private javax.swing.JButton empButCancel;
    private javax.swing.JButton empButDelete;
    private javax.swing.JButton empButEdit;
    private javax.swing.JButton empButInsert;
    private com.toedter.calendar.JDateChooser empDOB;
    private app.bolivia.swing.JCTextField empEmail;
    private javax.swing.JRadioButton empGenFemale;
    private javax.swing.JRadioButton empGenMale;
    private com.toedter.calendar.JDateChooser empJoinedDate;
    private app.bolivia.swing.JCTextField empNIC;
    private app.bolivia.swing.JCTextField empName;
    private javax.swing.JComboBox<String> empPositionCombo;
    private app.bolivia.swing.JCTextField empSearch;
    private rojeru_san.complementos.RSTableMetro empTable;
    private app.bolivia.swing.JCTextField empTeleNumber;
    private javax.swing.ButtonGroup gender;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables
}
