/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.xpos.gui;

import com.xpos.commons.SystemLogger;
import com.xpos.commons.Validate;
import com.xpos.database.DbConnect;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;

/**
 *
 * @author Jamit
 */
public class ExCost extends javax.swing.JPanel {

    DefaultTableModel tablemodel;
    DateTimeFormatter defaultDateFormat = DateTimeFormatter.ofPattern("yyyy-MM-dd");

    private static Logger log;
    int xCostId;

    /**
     * Creates new form ExCost
     */
    public ExCost() {
        initComponents();
        SystemLogger.initLogger();
        log = Logger.getLogger(ExCost.class);
        log.info("excost panel running start...");
        fillExCostTable(null);
    }

    private boolean validateForm() {
        log.info("validate excost form");
        return Validate.isDate(xCostDate.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate().toString())
                && Validate.isText(xCostDescription.getText().toString())
                && Validate.isDoubleNumber(xCostAmount.getText().toString());
    }

    public void clearExCostPanel() {
        log.info("validate excost form");
        xCostDate.setDate(null);
        xCostDescription.setText("");
        xCostAmount.setText("");
        xCostSearch.setText("");
        fillExCostTable(null);
    }

    private void fillExCostTable(String query) {
        tablemodel = (DefaultTableModel) xCostTable.getModel();
        tablemodel.setRowCount(0);
        log.info("fill table, query : "+query);
        if (query == null) {
            log.info("assign query because null");
            query = "select * from excost where Status=1";
        }
        try {
            ResultSet rs = DbConnect.getFromDB(query);
            log.info("executing query");
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getInt("Id"));
                v.add(rs.getDate("Date"));
                v.add(rs.getString("Description"));
                v.add(rs.getDouble("CostAmount"));
                tablemodel.addRow(v);
            }
            log.info("table filled");
        } catch (SQLException e) {
            log.error("table fill failed", e);
        } catch (ClassNotFoundException e) {
            log.error("table fill failed", e);
        } catch (Exception e) {
            log.error("table fill failed", e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        xCostButInsert = new javax.swing.JButton();
        xCostButEdit = new javax.swing.JButton();
        xCostButDelete = new javax.swing.JButton();
        xCostButCancel = new javax.swing.JButton();
        xCostDescription = new app.bolivia.swing.JCTextField();
        xCostAmount = new app.bolivia.swing.JCTextField();
        xCostDate = new com.toedter.calendar.JDateChooser();
        jPanel23 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        xCostTable = new rojeru_san.complementos.RSTableMetro();
        xCostSearch = new app.bolivia.swing.JCTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setBackground(new java.awt.Color(26, 140, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("ADDITIONAL COST");
        jLabel11.setOpaque(true);

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));

        xCostButInsert.setBackground(new java.awt.Color(0, 60, 128));
        xCostButInsert.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        xCostButInsert.setForeground(new java.awt.Color(255, 255, 255));
        xCostButInsert.setText("INSERT");
        xCostButInsert.setBorder(null);
        xCostButInsert.setFocusPainted(false);
        xCostButInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xCostButInsertActionPerformed(evt);
            }
        });

        xCostButEdit.setBackground(new java.awt.Color(0, 60, 128));
        xCostButEdit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        xCostButEdit.setForeground(new java.awt.Color(255, 255, 255));
        xCostButEdit.setText("EDIT");
        xCostButEdit.setBorder(null);
        xCostButEdit.setFocusPainted(false);
        xCostButEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xCostButEditActionPerformed(evt);
            }
        });

        xCostButDelete.setBackground(new java.awt.Color(0, 60, 128));
        xCostButDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        xCostButDelete.setForeground(new java.awt.Color(255, 255, 255));
        xCostButDelete.setText("DELETE");
        xCostButDelete.setBorder(null);
        xCostButDelete.setFocusPainted(false);
        xCostButDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xCostButDeleteActionPerformed(evt);
            }
        });

        xCostButCancel.setBackground(new java.awt.Color(0, 60, 128));
        xCostButCancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        xCostButCancel.setForeground(new java.awt.Color(255, 255, 255));
        xCostButCancel.setText("CANCEL");
        xCostButCancel.setBorder(null);
        xCostButCancel.setFocusPainted(false);
        xCostButCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xCostButCancelActionPerformed(evt);
            }
        });

        xCostDescription.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Description", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        xCostDescription.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        xCostDescription.setPhColor(new java.awt.Color(0, 51, 255));
        xCostDescription.setPlaceholder("Description");
        xCostDescription.setPreferredSize(new java.awt.Dimension(200, 30));
        xCostDescription.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                xCostDescriptionKeyPressed(evt);
            }
        });

        xCostAmount.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Amount", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        xCostAmount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        xCostAmount.setPhColor(new java.awt.Color(0, 51, 255));
        xCostAmount.setPlaceholder("Cost Amount");
        xCostAmount.setPreferredSize(new java.awt.Dimension(200, 30));
        xCostAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                xCostAmountKeyPressed(evt);
            }
        });

        xCostDate.setBackground(new java.awt.Color(255, 255, 255));
        xCostDate.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Date", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        xCostDate.setDateFormatString("yyyy-MM-dd");
        xCostDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        xCostDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                xCostDateKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addComponent(xCostButInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(xCostButEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(xCostButDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(xCostButCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(xCostDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(xCostAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(xCostDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(xCostDate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xCostDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xCostAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xCostButInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xCostButEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xCostButDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xCostButCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel23.setBackground(new java.awt.Color(255, 255, 255));

        xCostTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Date", "Description", "Cost Amount"
            }
        ));
        xCostTable.setColorBackgoundHead(new java.awt.Color(26, 140, 255));
        xCostTable.setFuenteHead(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        xCostTable.setRowHeight(25);
        xCostTable.setRowMargin(0);
        xCostTable.setSelectionBackground(new java.awt.Color(0, 60, 128));
        xCostTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xCostTableMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(xCostTable);

        xCostSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        xCostSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        xCostSearch.setPhColor(new java.awt.Color(0, 51, 255));
        xCostSearch.setPlaceholder("Search");
        xCostSearch.setPreferredSize(new java.awt.Dimension(200, 30));
        xCostSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                xCostSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7)
                    .addComponent(xCostSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xCostSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1240, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void xCostButInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xCostButInsertActionPerformed
        log.info("user presses insert button");
        if (validateForm()) {
            log.info("form validate passed");
            LocalDate date = xCostDate.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            String desc = xCostDescription.getText().toString();
            double amount = Double.valueOf(xCostAmount.getText().toString());
            String query = "INSERT INTO `excost`(`Date`, `Description`, `CostAmount`) VALUES ('" + date.format(defaultDateFormat)
                    + "','" + desc + "'," + amount + ")";
            try {
                log.info("execute query");
                DbConnect.pushToDB(query);
                clearExCostPanel();
            } catch (SQLException e) {
                log.error("data insert failed", e);
            } catch (ClassNotFoundException e) {
                log.error("data insert failed", e);
            } catch (Exception e) {
                log.error("data insert failed", e);
            }
        } else {
            log.info("form validate failed");
            JOptionPane.showMessageDialog(null, "Form Validation Failed", "Validation Failed", 1);
        }
    }//GEN-LAST:event_xCostButInsertActionPerformed

    private void xCostButEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xCostButEditActionPerformed
        log.info("user presses edit button");
        if (validateForm()) {
            log.info("form validate passed");
            LocalDate date = xCostDate.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            String desc = xCostDescription.getText().toString();
            double amount = Double.valueOf(xCostAmount.getText().toString());
            String query = "update excost set Date='" + date + "',Description='" + desc + "',CostAmount=" + amount + " where Id=" + xCostId;
            try {
                log.info("execute query");
                DbConnect.pushToDB(query);
                clearExCostPanel();
            } catch (SQLException e) {
                log.error("data edit failed", e);
            } catch (ClassNotFoundException e) {
                log.error("data edit failed", e);
            } catch (Exception e) {
                log.error("data edit failed", e);
            }
        } else {
            log.info("form validate failed");
            JOptionPane.showMessageDialog(null, "Form Validation Failed", "Validation Failed", 1);
        }
    }//GEN-LAST:event_xCostButEditActionPerformed

    private void xCostButDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xCostButDeleteActionPerformed
        log.info("user presses delete button");
        String query = "update excost set Status=0 where Id=" + xCostId;
        try {
            log.info("execute query");
            DbConnect.pushToDB(query);
            clearExCostPanel();
        } catch (SQLException e) {
            log.error("data delete failed", e);
        } catch (ClassNotFoundException e) {
            log.error("data delete failed", e);
        } catch (Exception e) {
            log.error("data delete failed", e);
        }// TODO add your handling code here:
    }//GEN-LAST:event_xCostButDeleteActionPerformed

    private void xCostButCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xCostButCancelActionPerformed
        log.info("user presses cancel button");
        clearExCostPanel();
    }//GEN-LAST:event_xCostButCancelActionPerformed

    private void xCostTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xCostTableMouseClicked
        log.info("user selected a row");
        int selectedRow = xCostTable.getSelectedRow();
        try {
            xCostId = Integer.parseInt(xCostTable.getValueAt(selectedRow, 0).toString());
            xCostDate.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(xCostTable.getValueAt(selectedRow, 1).toString()));
            xCostDescription.setText(xCostTable.getValueAt(selectedRow, 2).toString());
            xCostAmount.setText(xCostTable.getValueAt(selectedRow, 3).toString());
        } catch (Exception e) {
            log.error("row selection failed", e);
        }
    }//GEN-LAST:event_xCostTableMouseClicked

    private void xCostSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_xCostSearchKeyReleased
        String query = "select * from excost where Description like '%" + xCostSearch.getText().toString() + "%' and status=1";
        fillExCostTable(query);
        log.info("xcost search : query = " + query);
    }//GEN-LAST:event_xCostSearchKeyReleased

    private void xCostDateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_xCostDateKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            log.info("user presses enter to date chooser");
            if (Validate.isDate(xCostDate.getDate().toString())) {
                log.info("date validation passed and set focus to description");
                xCostDescription.requestFocus();
            } else {
                log.info("date validation failed");
                JOptionPane.showMessageDialog(null, "Not Text", "Validation Failed", 1);
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_xCostDateKeyPressed

    private void xCostDescriptionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_xCostDescriptionKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            log.info("user presses enter to description text field");
            if (Validate.isText(xCostDescription.getText().toString())) {
                log.info("validation passed and set focus to amount");
                xCostAmount.requestFocus();
            } else {
                log.info("validation failed");
                JOptionPane.showMessageDialog(null, "Not Text", "Validation Failed", 1);
            }
        }   // TODO add your handling code here:
    }//GEN-LAST:event_xCostDescriptionKeyPressed

    private void xCostAmountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_xCostAmountKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            log.info("user presses enter to amount field");
            if (Validate.isDoubleNumber(xCostAmount.getText().toString())) {
                log.info("validation passed");
                xCostButInsert.requestFocus();
            } else {
                log.info("validation failed");
                JOptionPane.showMessageDialog(null, "Not Text", "Validation Failed", 1);
            }
        }         // TODO add your handling code here:
    }//GEN-LAST:event_xCostAmountKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JScrollPane jScrollPane7;
    private app.bolivia.swing.JCTextField xCostAmount;
    private javax.swing.JButton xCostButCancel;
    private javax.swing.JButton xCostButDelete;
    private javax.swing.JButton xCostButEdit;
    private javax.swing.JButton xCostButInsert;
    private com.toedter.calendar.JDateChooser xCostDate;
    private app.bolivia.swing.JCTextField xCostDescription;
    private app.bolivia.swing.JCTextField xCostSearch;
    private rojeru_san.complementos.RSTableMetro xCostTable;
    // End of variables declaration//GEN-END:variables
}
