/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.xpos.gui;

import com.xpos.commons.Validate;
import com.xpos.database.DbConnect;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jamit
 */
public class ExIncome extends javax.swing.JPanel {

    DefaultTableModel tablemodel;
    DateTimeFormatter defaultDateFormat = DateTimeFormatter.ofPattern("yyyy-MM-dd");

    int xIncomeId;

    /**
     * Creates new form ExIncome
     */
    public ExIncome() {
        initComponents();
        fillExIncomeTable(null);
    }

    private boolean validateForm() {
        return Validate.isDate(xIncomeDate.getDate().toString())
                && Validate.isText(xIncomeDescription.getText().toString())
                && Validate.isDoubleNumber(xIncomeAmount.getText().toString());
    }

    public void clearExIncomePanel() {
        xIncomeDate.setDate(null);
        xIncomeDescription.setText("");
        xIncomeAmount.setText("");
        xIncomeSearch.setText("");
        fillExIncomeTable(null);
    }

    public void fillExIncomeTable(String query) {
        tablemodel = (DefaultTableModel) xIncomeTable.getModel();
        tablemodel.setRowCount(0);
        if (query == null) {
            query = "select * from exincome where Status=1";
        }
        try {
            ResultSet rs = DbConnect.getFromDB(query);
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getInt("Id"));
                v.add(rs.getDate("Date"));
                v.add(rs.getString("Description"));
                v.add(rs.getDouble("IncomeAmount"));
                tablemodel.addRow(v);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        xIncomeButInsert = new javax.swing.JButton();
        xIncomeButEdit = new javax.swing.JButton();
        xIncomeButDelete = new javax.swing.JButton();
        xIncomeButCancel = new javax.swing.JButton();
        xIncomeDescription = new app.bolivia.swing.JCTextField();
        xIncomeAmount = new app.bolivia.swing.JCTextField();
        xIncomeDate = new com.toedter.calendar.JDateChooser();
        jPanel24 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        xIncomeTable = new rojeru_san.complementos.RSTableMetro();
        xIncomeSearch = new app.bolivia.swing.JCTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setBackground(new java.awt.Color(26, 140, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("EXTRA INCOME");
        jLabel12.setOpaque(true);

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));

        xIncomeButInsert.setBackground(new java.awt.Color(0, 60, 128));
        xIncomeButInsert.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        xIncomeButInsert.setForeground(new java.awt.Color(255, 255, 255));
        xIncomeButInsert.setText("INSERT");
        xIncomeButInsert.setBorder(null);
        xIncomeButInsert.setFocusPainted(false);
        xIncomeButInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xIncomeButInsertActionPerformed(evt);
            }
        });

        xIncomeButEdit.setBackground(new java.awt.Color(0, 60, 128));
        xIncomeButEdit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        xIncomeButEdit.setForeground(new java.awt.Color(255, 255, 255));
        xIncomeButEdit.setText("EDIT");
        xIncomeButEdit.setBorder(null);
        xIncomeButEdit.setFocusPainted(false);
        xIncomeButEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xIncomeButEditActionPerformed(evt);
            }
        });

        xIncomeButDelete.setBackground(new java.awt.Color(0, 60, 128));
        xIncomeButDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        xIncomeButDelete.setForeground(new java.awt.Color(255, 255, 255));
        xIncomeButDelete.setText("DELETE");
        xIncomeButDelete.setBorder(null);
        xIncomeButDelete.setFocusPainted(false);
        xIncomeButDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xIncomeButDeleteActionPerformed(evt);
            }
        });

        xIncomeButCancel.setBackground(new java.awt.Color(0, 60, 128));
        xIncomeButCancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        xIncomeButCancel.setForeground(new java.awt.Color(255, 255, 255));
        xIncomeButCancel.setText("CANCEL");
        xIncomeButCancel.setBorder(null);
        xIncomeButCancel.setFocusPainted(false);
        xIncomeButCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xIncomeButCancelActionPerformed(evt);
            }
        });

        xIncomeDescription.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Description", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        xIncomeDescription.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        xIncomeDescription.setPhColor(new java.awt.Color(0, 51, 255));
        xIncomeDescription.setPlaceholder("Description");
        xIncomeDescription.setPreferredSize(new java.awt.Dimension(200, 30));
        xIncomeDescription.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                xIncomeDescriptionKeyPressed(evt);
            }
        });

        xIncomeAmount.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Amount", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        xIncomeAmount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        xIncomeAmount.setPhColor(new java.awt.Color(0, 51, 255));
        xIncomeAmount.setPlaceholder("Income Amount");
        xIncomeAmount.setPreferredSize(new java.awt.Dimension(200, 30));
        xIncomeAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                xIncomeAmountKeyPressed(evt);
            }
        });

        xIncomeDate.setBackground(new java.awt.Color(255, 255, 255));
        xIncomeDate.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Date", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        xIncomeDate.setDateFormatString("yyyy-MM-dd");
        xIncomeDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        xIncomeDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                xIncomeDateKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addComponent(xIncomeButInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(xIncomeButEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(xIncomeButDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(xIncomeButCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(xIncomeDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(xIncomeAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(xIncomeDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(xIncomeDate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xIncomeDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xIncomeAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xIncomeButInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xIncomeButEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xIncomeButDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xIncomeButCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel24.setBackground(new java.awt.Color(255, 255, 255));

        xIncomeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Date", "Description", "Income Amount"
            }
        ));
        xIncomeTable.setColorBackgoundHead(new java.awt.Color(26, 140, 255));
        xIncomeTable.setFuenteHead(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        xIncomeTable.setRowHeight(25);
        xIncomeTable.setRowMargin(0);
        xIncomeTable.setSelectionBackground(new java.awt.Color(0, 60, 128));
        xIncomeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xIncomeTableMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(xIncomeTable);

        xIncomeSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        xIncomeSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        xIncomeSearch.setPhColor(new java.awt.Color(0, 51, 255));
        xIncomeSearch.setPlaceholder("Search");
        xIncomeSearch.setPreferredSize(new java.awt.Dimension(200, 30));
        xIncomeSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                xIncomeSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8)
                    .addComponent(xIncomeSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xIncomeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1240, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void xIncomeButInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xIncomeButInsertActionPerformed
        if (validateForm()) {
            LocalDate date = xIncomeDate.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            String desc = xIncomeDescription.getText().toString();
            double amount = Double.valueOf(xIncomeAmount.getText().toString());
            String query = "INSERT INTO `exincome`(`Date`, `Description`, `IncomeAmount`) VALUES ('" + date.format(defaultDateFormat)
                    + "','" + desc + "'," + amount + ")";
            try {
                DbConnect.pushToDB(query);
                clearExIncomePanel();
            } catch (SQLException e) {
                e.printStackTrace();
            } catch (ClassNotFoundException e) {
                e.printStackTrace();
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Form Validation Failed", "Validation Failed", 1);
        }
    }//GEN-LAST:event_xIncomeButInsertActionPerformed

    private void xIncomeButEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xIncomeButEditActionPerformed
        if (validateForm()) {
            LocalDate date = xIncomeDate.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            String desc = xIncomeDescription.getText().toString();
            double amount = Double.valueOf(xIncomeAmount.getText().toString());
            String query = "update exincome set Date='" + date + "',Description='" + desc + "',IncomeAmount=" + amount + " where Id=" + xIncomeId;
            try {
                DbConnect.pushToDB(query);
                clearExIncomePanel();
            } catch (SQLException e) {
                e.printStackTrace();
            } catch (ClassNotFoundException e) {
                e.printStackTrace();
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Form Validation Failed", "Validation Failed", 1);
        }
    }//GEN-LAST:event_xIncomeButEditActionPerformed

    private void xIncomeButDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xIncomeButDeleteActionPerformed
        String query = "update exincome set Status=0 where Id=" + xIncomeId;
        try {
            DbConnect.pushToDB(query);
            clearExIncomePanel();
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_xIncomeButDeleteActionPerformed

    private void xIncomeButCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xIncomeButCancelActionPerformed
        clearExIncomePanel();
    }//GEN-LAST:event_xIncomeButCancelActionPerformed

    private void xIncomeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xIncomeTableMouseClicked
        int selectedRow = xIncomeTable.getSelectedRow();
        try {
            xIncomeId = Integer.parseInt(xIncomeTable.getValueAt(selectedRow, 0).toString());
            xIncomeDate.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(xIncomeTable.getValueAt(selectedRow, 1).toString()));
            xIncomeDescription.setText(xIncomeTable.getValueAt(selectedRow, 2).toString());
            xIncomeAmount.setText(xIncomeTable.getValueAt(selectedRow, 3).toString());
        } catch (Exception e) {

        }
    }//GEN-LAST:event_xIncomeTableMouseClicked

    private void xIncomeSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_xIncomeSearchKeyReleased
        String query = "select * from exincome where Description like '%" + xIncomeSearch.getText().toString() + "%' and status=1";
        fillExIncomeTable(query);
    }//GEN-LAST:event_xIncomeSearchKeyReleased

    private void xIncomeDateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_xIncomeDateKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (Validate.isDate(xIncomeDate.getDate().toString())) {
                xIncomeDescription.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Not Text", "Validation Failed", 1);
            }
        }         // TODO add your handling code here:
    }//GEN-LAST:event_xIncomeDateKeyPressed

    private void xIncomeDescriptionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_xIncomeDescriptionKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (Validate.isText(xIncomeDescription.getText().toString())) {
                xIncomeAmount.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Not Text", "Validation Failed", 1);
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_xIncomeDescriptionKeyPressed

    private void xIncomeAmountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_xIncomeAmountKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (Validate.isDoubleNumber(xIncomeAmount.getText().toString())) {
                xIncomeButInsert.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Not Text", "Validation Failed", 1);
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_xIncomeAmountKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JScrollPane jScrollPane8;
    private app.bolivia.swing.JCTextField xIncomeAmount;
    private javax.swing.JButton xIncomeButCancel;
    private javax.swing.JButton xIncomeButDelete;
    private javax.swing.JButton xIncomeButEdit;
    private javax.swing.JButton xIncomeButInsert;
    private com.toedter.calendar.JDateChooser xIncomeDate;
    private app.bolivia.swing.JCTextField xIncomeDescription;
    private app.bolivia.swing.JCTextField xIncomeSearch;
    private rojeru_san.complementos.RSTableMetro xIncomeTable;
    // End of variables declaration//GEN-END:variables
}
