/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.xpos.gui;

import com.xpos.database.DbConnect;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jamith
 */
public class Product extends javax.swing.JPanel {

    DefaultTableModel tablemodel;
    DateTimeFormatter defaultDateFormat = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    int supplierId;
    int customerId;
    int xCostId;
    int xIncomeId;
    int empPosId;
    int employeeId;
    int productId;
    int batchId;
    int userProId;

    /**
     * Creates new form Product
     */
    public Product() {
        initComponents();
        fillProductTable(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        productTable = new rojeru_san.complementos.RSTableMetro();
        prodSearch = new app.bolivia.swing.JCTextField();
        jPanel10 = new javax.swing.JPanel();
        prodDescription = new app.bolivia.swing.JCTextField();
        prodPurchPrice = new app.bolivia.swing.JCTextField();
        prodRetailPrice = new app.bolivia.swing.JCTextField();
        prodQuantity = new app.bolivia.swing.JCTextField();
        prodButInsert = new javax.swing.JButton();
        prodButEdit = new javax.swing.JButton();
        prodButDelete = new javax.swing.JButton();
        prodButCancel = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1440, 937));

        jLabel6.setBackground(new java.awt.Color(26, 140, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("PRODUCT");
        jLabel6.setOpaque(true);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Description", "Brand", "Category", "Re-Order Level", "Ordered Quantity", "Quantity"
            }
        ));
        productTable.setColorBackgoundHead(new java.awt.Color(26, 140, 255));
        productTable.setFuenteHead(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        productTable.setRowHeight(25);
        productTable.setRowMargin(0);
        productTable.setSelectionBackground(new java.awt.Color(0, 60, 128));
        productTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(productTable);

        prodSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        prodSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        prodSearch.setPhColor(new java.awt.Color(0, 51, 255));
        prodSearch.setPlaceholder("Search");
        prodSearch.setPreferredSize(new java.awt.Dimension(200, 30));
        prodSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodSearchActionPerformed(evt);
            }
        });
        prodSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                prodSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
                    .addComponent(prodSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(prodSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        prodDescription.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Description", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        prodDescription.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        prodDescription.setPhColor(new java.awt.Color(0, 51, 255));
        prodDescription.setPlaceholder("Description");
        prodDescription.setPreferredSize(new java.awt.Dimension(200, 30));

        prodPurchPrice.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Re-Order Level", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        prodPurchPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        prodPurchPrice.setPhColor(new java.awt.Color(0, 51, 255));
        prodPurchPrice.setPlaceholder("Re-Order Level");
        prodPurchPrice.setPreferredSize(new java.awt.Dimension(200, 30));

        prodRetailPrice.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Ordered Quantity", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        prodRetailPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        prodRetailPrice.setPhColor(new java.awt.Color(0, 51, 255));
        prodRetailPrice.setPlaceholder("Ordered Quantity");
        prodRetailPrice.setPreferredSize(new java.awt.Dimension(200, 30));

        prodQuantity.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Quantity", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        prodQuantity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        prodQuantity.setPhColor(new java.awt.Color(0, 51, 255));
        prodQuantity.setPlaceholder("Quantity");
        prodQuantity.setPreferredSize(new java.awt.Dimension(200, 30));

        prodButInsert.setBackground(new java.awt.Color(0, 60, 128));
        prodButInsert.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        prodButInsert.setForeground(new java.awt.Color(255, 255, 255));
        prodButInsert.setText("INSERT");
        prodButInsert.setBorder(null);
        prodButInsert.setFocusPainted(false);
        prodButInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodButInsertActionPerformed(evt);
            }
        });

        prodButEdit.setBackground(new java.awt.Color(0, 60, 128));
        prodButEdit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        prodButEdit.setForeground(new java.awt.Color(255, 255, 255));
        prodButEdit.setText("EDIT");
        prodButEdit.setBorder(null);
        prodButEdit.setFocusPainted(false);
        prodButEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodButEditActionPerformed(evt);
            }
        });

        prodButDelete.setBackground(new java.awt.Color(0, 60, 128));
        prodButDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        prodButDelete.setForeground(new java.awt.Color(255, 255, 255));
        prodButDelete.setText("DELETE");
        prodButDelete.setBorder(null);
        prodButDelete.setFocusPainted(false);
        prodButDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodButDeleteActionPerformed(evt);
            }
        });

        prodButCancel.setBackground(new java.awt.Color(0, 60, 128));
        prodButCancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        prodButCancel.setForeground(new java.awt.Color(255, 255, 255));
        prodButCancel.setText("CANCEL");
        prodButCancel.setBorder(null);
        prodButCancel.setFocusPainted(false);
        prodButCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodButCancelActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Brand" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Category" }));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
                                .addComponent(prodButInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(prodButEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(prodButDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(prodButCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(prodDescription, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(prodPurchPrice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(prodRetailPrice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(prodQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(prodDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodPurchPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodRetailPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodButInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prodButEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prodButDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prodButCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void fillProductTable(String query) {
        tablemodel = (DefaultTableModel) productTable.getModel();
        tablemodel.setRowCount(0);
        if (query == null) {
            query = "select * from product where Status=1";
        }
        try {
            ResultSet rs = DbConnect.getFromDB(query);
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getInt("Id"));
                v.add(rs.getString("Barcode"));
                v.add(rs.getString("Description"));
                v.add(rs.getFloat("PurchasePrice"));
                v.add(rs.getFloat("RetailPrice"));
                v.add(rs.getInt("TotalQuantity"));

                tablemodel.addRow(v);
            }
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void clearProductPanel() {
        //prodBarcode.setText("");
        prodDescription.setText("");
        prodPurchPrice.setText("");
        prodRetailPrice.setText("");
        prodQuantity.setText("");
        prodSearch.setText("");
        fillProductTable(null);
    }

    private void productTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productTableMouseClicked
        int selectedRow = productTable.getSelectedRow();
        productId = Integer.parseInt(productTable.getValueAt(selectedRow, 0).toString());
        //prodBarcode.setText(productTable.getValueAt(selectedRow, 1).toString());
        prodDescription.setText(productTable.getValueAt(selectedRow, 2).toString());
        prodPurchPrice.setText(productTable.getValueAt(selectedRow, 3).toString());
        prodRetailPrice.setText(productTable.getValueAt(selectedRow, 4).toString());
        prodQuantity.setText(productTable.getValueAt(selectedRow, 5).toString());
    }//GEN-LAST:event_productTableMouseClicked

    private void prodSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodSearchActionPerformed

    private void prodSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prodSearchKeyReleased
        String query = "select * from product where description like '%" + prodSearch.getText() + "%' and status=1";
        fillProductTable(query);
    }//GEN-LAST:event_prodSearchKeyReleased

    private void prodButInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodButInsertActionPerformed
        //String barcode = prodBarcode.getText();
        String description = prodDescription.getText();
        double purchasePrice = Double.parseDouble(prodPurchPrice.getText());
        double retailPrice = Double.parseDouble(prodRetailPrice.getText());
        int quantity = Integer.parseInt(prodQuantity.getText());
//        String query = "INSERT INTO `product`( `Barcode`, `Description`,"
//                + " `PurchasePrice`, `RetailPrice`, `TotalQuantity`) "
//                + "VALUES ('" + barcode + "','" + description + "'," + purchasePrice
//                + "," + retailPrice + "," + quantity + ")";
//        try {
//            DbConnect.pushToDB(query);
//            clearProductPanel();
//        } catch (ClassNotFoundException e) {
//            e.printStackTrace();
//        } catch (SQLException e) {
//            e.printStackTrace();
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_prodButInsertActionPerformed

    private void prodButEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodButEditActionPerformed
        //String barcode = prodBarcode.getText();
        String description = prodDescription.getText();
        double purchasePrice = Double.parseDouble(prodPurchPrice.getText());
        double retailPrice = Double.parseDouble(prodRetailPrice.getText());
        int quantity = Integer.parseInt(prodQuantity.getText());

//        String query = "UPDATE `product` SET `Barcode`='" + barcode + "',`Description`='" + description
//                + "',`PurchasePrice`='" + purchasePrice + "',`RetailPrice`='" + retailPrice
//                + "',`TotalQuantity`='" + quantity + "' WHERE Id=" + productId;
//
//        try {
//            DbConnect.pushToDB(query);
//            clearProductPanel();
//        } catch (ClassNotFoundException e) {
//            e.printStackTrace();
//        } catch (SQLException e) {
//            e.printStackTrace();
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_prodButEditActionPerformed

    private void prodButDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodButDeleteActionPerformed
        String query = "UPDATE `product` SET `Status`=0 WHERE Id=" + productId;
        try {
            DbConnect.pushToDB(query);
            clearProductPanel();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_prodButDeleteActionPerformed

    private void prodButCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodButCancelActionPerformed
        clearProductPanel();
    }//GEN-LAST:event_prodButCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton prodButCancel;
    private javax.swing.JButton prodButDelete;
    private javax.swing.JButton prodButEdit;
    private javax.swing.JButton prodButInsert;
    private app.bolivia.swing.JCTextField prodDescription;
    private app.bolivia.swing.JCTextField prodPurchPrice;
    private app.bolivia.swing.JCTextField prodQuantity;
    private app.bolivia.swing.JCTextField prodRetailPrice;
    private app.bolivia.swing.JCTextField prodSearch;
    private rojeru_san.complementos.RSTableMetro productTable;
    // End of variables declaration//GEN-END:variables
}
