/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.xpos.gui;

import com.xpos.SystemUser;
import com.xpos.database.DbConnect;
import com.xpos.report.Report;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.HashMap;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Jamit
 */
public class Purchase extends javax.swing.JPanel {

    DefaultTableModel tablemodel;

    DateTimeFormatter defaultDateFormat = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    DateTimeFormatter defaultTimeFormat = DateTimeFormatter.ofPattern("hh:mm:ss");

    Double totalWithNoDiscount = 0.0;
    Double discount = 0.0;
    Double finalTotal = 0.0;
    int purchaseOrderId = 0;
    int supplierId = 0;

    /**
     * Creates new form Purchase
     */
    public Purchase() {
        initComponents();
        loadPurchaseSupplierCombo();
        fillPurchaseProdTable(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        purchDisGroup = new javax.swing.ButtonGroup();
        jLabel13 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        purchProdTable = new rojeru_san.complementos.RSTableMetro();
        purchProdDescription = new app.bolivia.swing.JCTextField();
        jPanel27 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        purchBatchTable = new rojeru_san.complementos.RSTableMetro();
        purchProdBatchNumber = new app.bolivia.swing.JCTextField();
        purchProdBarcode = new app.bolivia.swing.JCTextField();
        jPanel3 = new javax.swing.JPanel();
        purchProductId = new app.bolivia.swing.JCTextField();
        purchBarcode = new app.bolivia.swing.JCTextField();
        purchDescription = new javax.swing.JLabel();
        purchManufacDate = new javax.swing.JLabel();
        purchExpireDate = new javax.swing.JLabel();
        purchQuantity = new app.bolivia.swing.JCTextField();
        purchPurchasePrice = new app.bolivia.swing.JCTextField();
        purchAddToTable = new javax.swing.JButton();
        purchBatchId = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        purchComplete = new javax.swing.JButton();
        purchDeleteItem = new javax.swing.JButton();
        purchCancel = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        purchSubTotal = new javax.swing.JLabel();
        purchDiscount = new app.bolivia.swing.JCTextField();
        purchDisAmount = new javax.swing.JRadioButton();
        purchDisPercent = new javax.swing.JRadioButton();
        jLabel40 = new javax.swing.JLabel();
        purchTotal = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        purchFinalDiscount = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        purchProduct = new rojeru_san.complementos.RSTableMetro();
        purchSupplierCombo = new javax.swing.JComboBox<>();
        purchPurchaseOrderCombo = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setBackground(new java.awt.Color(26, 140, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("PURCHASE");
        jLabel13.setOpaque(true);

        jPanel26.setBackground(new java.awt.Color(255, 255, 255));
        jPanel26.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Products", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(26, 140, 255))); // NOI18N

        purchProdTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Category", "Brand", "Description", "Quantity (In Stock)", "Ordered Quantoty"
            }
        ));
        purchProdTable.setColorBackgoundHead(new java.awt.Color(26, 140, 255));
        purchProdTable.setFuenteHead(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        purchProdTable.setRowHeight(25);
        purchProdTable.setRowMargin(0);
        purchProdTable.setSelectionBackground(new java.awt.Color(0, 60, 128));
        purchProdTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purchProdTableMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(purchProdTable);

        purchProdDescription.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Description", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        purchProdDescription.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        purchProdDescription.setPhColor(new java.awt.Color(0, 51, 255));
        purchProdDescription.setPlaceholder("Search by Description");
        purchProdDescription.setPreferredSize(new java.awt.Dimension(200, 30));
        purchProdDescription.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                purchProdDescriptionKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addComponent(purchProdDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel26Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(purchProdDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
        );

        jPanel27.setBackground(new java.awt.Color(255, 255, 255));
        jPanel27.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Batch details of Products", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(26, 140, 255))); // NOI18N

        purchBatchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Batch Number", "Barcode", "Quantities By Batch", "Purchase Price", "Retail Price", "Manufac. Date", "Expire Date"
            }
        ));
        purchBatchTable.setColorBackgoundHead(new java.awt.Color(26, 140, 255));
        purchBatchTable.setFuenteHead(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        purchBatchTable.setRowHeight(25);
        purchBatchTable.setRowMargin(0);
        purchBatchTable.setSelectionBackground(new java.awt.Color(0, 60, 128));
        purchBatchTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purchBatchTableMouseClicked(evt);
            }
        });
        jScrollPane10.setViewportView(purchBatchTable);

        purchProdBatchNumber.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Batch Number", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        purchProdBatchNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        purchProdBatchNumber.setPhColor(new java.awt.Color(0, 51, 255));
        purchProdBatchNumber.setPlaceholder("Search By Batch Number");
        purchProdBatchNumber.setPreferredSize(new java.awt.Dimension(200, 30));
        purchProdBatchNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                purchProdBatchNumberKeyReleased(evt);
            }
        });

        purchProdBarcode.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Barcode", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        purchProdBarcode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        purchProdBarcode.setPhColor(new java.awt.Color(0, 51, 255));
        purchProdBarcode.setPlaceholder("Search Barcode");
        purchProdBarcode.setPreferredSize(new java.awt.Dimension(200, 30));
        purchProdBarcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                purchProdBarcodeKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addComponent(purchProdBatchNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(purchProdBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel27Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(purchProdBatchNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(purchProdBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        purchProductId.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Product Id", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        purchProductId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        purchProductId.setPhColor(new java.awt.Color(0, 51, 255));
        purchProductId.setPlaceholder("Search by Product Id");
        purchProductId.setPreferredSize(new java.awt.Dimension(200, 30));
        purchProductId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                purchProductIdKeyReleased(evt);
            }
        });

        purchBarcode.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Barcode", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        purchBarcode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        purchBarcode.setPhColor(new java.awt.Color(0, 51, 255));
        purchBarcode.setPlaceholder("Search Barcode");
        purchBarcode.setPreferredSize(new java.awt.Dimension(200, 30));
        purchBarcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                purchBarcodeKeyReleased(evt);
            }
        });

        purchDescription.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        purchDescription.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Description", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N

        purchManufacDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        purchManufacDate.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Manufacture Date", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N

        purchExpireDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        purchExpireDate.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Expire Date", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N

        purchQuantity.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Quantity", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        purchQuantity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        purchQuantity.setPhColor(new java.awt.Color(0, 51, 255));
        purchQuantity.setPlaceholder("Enter Quantity");
        purchQuantity.setPreferredSize(new java.awt.Dimension(200, 30));
        purchQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                purchQuantityKeyReleased(evt);
            }
        });

        purchPurchasePrice.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Purchase Price", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        purchPurchasePrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        purchPurchasePrice.setPhColor(new java.awt.Color(0, 51, 255));
        purchPurchasePrice.setPlaceholder("Enter Purchase Price");
        purchPurchasePrice.setPreferredSize(new java.awt.Dimension(200, 30));
        purchPurchasePrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                purchPurchasePriceKeyReleased(evt);
            }
        });

        purchAddToTable.setBackground(new java.awt.Color(0, 60, 128));
        purchAddToTable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        purchAddToTable.setForeground(new java.awt.Color(255, 255, 255));
        purchAddToTable.setText("ADD TO TABLE");
        purchAddToTable.setBorder(null);
        purchAddToTable.setFocusPainted(false);
        purchAddToTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchAddToTableActionPerformed(evt);
            }
        });

        purchBatchId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        purchBatchId.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Batch Id", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(purchProductId, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(purchBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(purchDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addComponent(purchBatchId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(purchExpireDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(purchManufacDate, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(purchPurchasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(purchQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(purchAddToTable, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(purchAddToTable, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(purchPurchasePrice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(purchManufacDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(purchDescription, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(purchProductId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(purchExpireDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(purchQuantity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(purchBarcode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(purchBatchId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Purchase Actions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(26, 140, 255))); // NOI18N

        purchComplete.setBackground(new java.awt.Color(0, 60, 128));
        purchComplete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        purchComplete.setForeground(new java.awt.Color(255, 255, 255));
        purchComplete.setText("COMPLETE PURCHASE");
        purchComplete.setBorder(null);
        purchComplete.setFocusPainted(false);
        purchComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchCompleteActionPerformed(evt);
            }
        });

        purchDeleteItem.setBackground(new java.awt.Color(0, 60, 128));
        purchDeleteItem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        purchDeleteItem.setForeground(new java.awt.Color(255, 255, 255));
        purchDeleteItem.setText("DELETE ITEM");
        purchDeleteItem.setBorder(null);
        purchDeleteItem.setFocusPainted(false);
        purchDeleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchDeleteItemActionPerformed(evt);
            }
        });

        purchCancel.setBackground(new java.awt.Color(0, 60, 128));
        purchCancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        purchCancel.setForeground(new java.awt.Color(255, 255, 255));
        purchCancel.setText("CANCEL PURCHASE");
        purchCancel.setBorder(null);
        purchCancel.setFocusPainted(false);
        purchCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchCancelActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Total Price : ");

        purchSubTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        purchSubTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        purchSubTotal.setText("0.0");

        purchDiscount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)));
        purchDiscount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        purchDiscount.setText("0");
        purchDiscount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        purchDiscount.setPhColor(new java.awt.Color(0, 51, 255));
        purchDiscount.setPlaceholder("Discount");
        purchDiscount.setPreferredSize(new java.awt.Dimension(200, 30));
        purchDiscount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                purchDiscountKeyReleased(evt);
            }
        });

        purchDisAmount.setBackground(new java.awt.Color(255, 255, 255));
        purchDisGroup.add(purchDisAmount);
        purchDisAmount.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        purchDisAmount.setSelected(true);
        purchDisAmount.setText("Amount");
        purchDisAmount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purchDisAmountMouseClicked(evt);
            }
        });

        purchDisPercent.setBackground(new java.awt.Color(255, 255, 255));
        purchDisGroup.add(purchDisPercent);
        purchDisPercent.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        purchDisPercent.setText("Percent (%)");
        purchDisPercent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purchDisPercentMouseClicked(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel40.setText("Discount Amount :");

        purchTotal.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        purchTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        purchTotal.setText("0.00");

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel42.setText("Total :");

        purchFinalDiscount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        purchFinalDiscount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        purchFinalDiscount.setText("0.0");

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel41.setText("Discount :");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(purchCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(purchComplete, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(purchSubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(purchDeleteItem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(purchTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel41)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(purchDisAmount)))
                        .addGap(18, 18, 18)
                        .addComponent(purchDisPercent))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel40)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(purchFinalDiscount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(purchDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(purchSubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(purchDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(purchDisPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(purchDisAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(purchFinalDiscount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(purchTotal)
                        .addGap(18, 18, 18)
                        .addComponent(purchDeleteItem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(purchCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(purchComplete, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel42)))
        );

        jPanel25.setBackground(new java.awt.Color(255, 255, 255));
        jPanel25.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Purchased Products", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(26, 140, 255))); // NOI18N

        purchProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Description", "Batch Id", "Purchase Price", "Quantity", "Total"
            }
        ));
        purchProduct.setColorBackgoundHead(new java.awt.Color(26, 140, 255));
        purchProduct.setFuenteHead(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        purchProduct.setRowHeight(25);
        purchProduct.setRowMargin(0);
        purchProduct.setSelectionBackground(new java.awt.Color(0, 60, 128));
        purchProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purchProductMouseClicked(evt);
            }
        });
        jScrollPane11.setViewportView(purchProduct);

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane11)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        purchSupplierCombo.setForeground(new java.awt.Color(26, 140, 255));
        purchSupplierCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Supplier" }));
        purchSupplierCombo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Supplier", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        purchSupplierCombo.setOpaque(false);
        purchSupplierCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchSupplierComboActionPerformed(evt);
            }
        });

        purchPurchaseOrderCombo.setForeground(new java.awt.Color(26, 140, 255));
        purchPurchaseOrderCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Purchase Order" }));
        purchPurchaseOrderCombo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Purchase Order", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        purchPurchaseOrderCombo.setOpaque(false);
        purchPurchaseOrderCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchPurchaseOrderComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(purchSupplierCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(310, 310, 310))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(purchPurchaseOrderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(purchSupplierCombo)
                    .addComponent(purchPurchaseOrderCombo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loadPurchaseSupplierCombo() {
        try {
            ResultSet rs = DbConnect.getFromDB("select Id,Name from supplier where status=1");
            Vector v = new Vector();
            v.add("Select Supplier");
            while (rs.next()) {
                String supplier = rs.getString("Id") + " - " + rs.getString("Name");
                v.add(supplier);
            }
            purchSupplierCombo.setModel(new DefaultComboBoxModel(v));
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadPurchaseOrderCombo() {
        try {
            int supplierId = Integer.parseInt(purchSupplierCombo.getSelectedItem().toString().split(" - ")[0].trim());
            ResultSet rs = DbConnect.getFromDB("select Id from purchaseorder where status=1 and IsSupplied=0 and Supplier_Id=" + supplierId);
            Vector v = new Vector();
            v.add("Select Purchase Order");
            while (rs.next()) {
                String supplier = rs.getString("Id");
                v.add(supplier);
            }
            purchPurchaseOrderCombo.setModel(new DefaultComboBoxModel(v));
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void fillPurchaseProdTable(String query) {
        tablemodel = (DefaultTableModel) purchProdTable.getModel();
        tablemodel.setRowCount(0);
        if (query == null) {
            query = "SELECT product.Id as Id, product.Brand_Id as brandId, brand.BrandName as brandName,"
                    + " product.Category_Id as categoryId, category.Description as categoryName,"
                    + " product.Description as description, product.TotalQuantity as totalQuantity, product.orderedQuantity as orderedQuantity"
                    + " FROM ((product JOIN brand ON product.Brand_Id=brand.Id) JOIN category ON product.Category_Id=category.Id)"
                    + " WHERE product.Status = 1";
        }
        try {
            ResultSet rs = DbConnect.getFromDB(query);
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getInt("Id"));
                v.add(rs.getString("categoryId") + " - " + rs.getString("categoryName"));
                v.add(rs.getString("brandId") + " - " + rs.getString("brandName"));
                v.add(rs.getString("Description"));
                v.add(rs.getInt("totalQuantity"));
                v.add(rs.getInt("orderedQuantity"));

                tablemodel.addRow(v);
            }
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void fillPurchaseBatchTable(String query) {
        int prodId = 0;
        tablemodel = (DefaultTableModel) purchBatchTable.getModel();
        tablemodel.setRowCount(0);
        if (query == null) {
            prodId = Integer.parseInt(purchProdTable.getValueAt(purchProdTable.getSelectedRow(), 0).toString().trim());
            query = "SELECT batchesofproduct.Id as batchid,"
                    + " batchesofproduct.Barcode as Barcode,"
                    + " batchesofproduct.BatchNumber as BatchNumber,"
                    + " batchesofproduct.QuantityByBatch as quantity,"
                    + " batchesofproduct.PurchasePrice as purchPrice,"
                    + " batchesofproduct.RetailPrice AS RetailPrice"
                    + " FROM batchesofproduct "
                    + " WHERE batchesofproduct.Status = 1 and batchesofproduct.Product_Id=" + prodId;
        }
        try {
            ResultSet rs = DbConnect.getFromDB(query);
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getInt("batchid"));
                v.add(rs.getInt("BatchNumber"));
                v.add(rs.getInt("Barcode"));
                v.add(rs.getInt("quantity"));
                v.add(rs.getDouble("purchPrice"));
                v.add(rs.getDouble("RetailPrice"));

                String query2 = "select ManufactureDate as manufacDate,"
                        + "ExpireDate as expireDate "
                        + "from datesOfBatch "
                        + "where Status=1 and BatchesOfProduct_Id="
                        + rs.getInt("batchId");
                ResultSet rs2 = DbConnect.getFromDB(query2);
                if (rs2.next()) {
                    v.add(rs2.getDate("manufacDate"));
                    v.add(rs2.getDate("expireDate"));
                }
                tablemodel.addRow(v);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void calPurchaseDetails() {
        int rows = purchProduct.getRowCount();
        totalWithNoDiscount = 0.0;
        discount = 0.0;
        finalTotal = 0.0;
        for (int i = 0; i < rows; i++) {
            totalWithNoDiscount = totalWithNoDiscount + Double.parseDouble(purchProduct.getValueAt(i, 5).toString());
        }
        if (purchDisAmount.isSelected()) {
            discount = Double.parseDouble(purchDiscount.getText().toString());
        } else if (purchDisPercent.isSelected()) {
            discount = totalWithNoDiscount * Double.parseDouble(purchDiscount.getText().toString()) / 100;
        }
        finalTotal = totalWithNoDiscount - discount;
        purchSubTotal.setText(totalWithNoDiscount.toString());
        purchFinalDiscount.setText(discount.toString());
        purchTotal.setText(finalTotal.toString());
    }

    private void clearPurchPanel() {
        purchSupplierCombo.setSelectedIndex(0);
        ((DefaultTableModel) purchProduct.getModel()).setRowCount(0);
        ((DefaultTableModel) purchProdTable.getModel()).setRowCount(0);
        ((DefaultTableModel) purchBatchTable.getModel()).setRowCount(0);
        purchPurchaseOrderCombo.setSelectedIndex(0);
        purchBarcode.setText("");
        purchDescription.setText("");
        purchManufacDate.setText("");
        purchPurchasePrice.setText("");
        purchProductId.setText("");
        purchBatchId.setText("");
        purchExpireDate.setText("");
        purchQuantity.setText("");
        purchProdBarcode.setText("");
        purchProdDescription.setText("");
        purchProdBatchNumber.setText("");
        purchSubTotal.setText("0.0");
        purchDiscount.setText("0");
        purchDisAmount.setSelected(true);
        purchTotal.setText("0.00");
        fillPurchaseProdTable(null);
    }

    private void purchProdTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchProdTableMouseClicked
        fillPurchaseBatchTable(null);
        int selectedRow = purchProdTable.getSelectedRow();
        purchProductId.setText(purchProdTable.getValueAt(selectedRow, 0).toString());
        purchDescription.setText(purchProdTable.getValueAt(selectedRow, 3).toString());
        purchBarcode.setText("");
        purchExpireDate.setText("");
        purchManufacDate.setText("");
        purchPurchasePrice.setText("");
        purchQuantity.setText("");
        purchBatchId.setText("");
    }//GEN-LAST:event_purchProdTableMouseClicked

    private void purchProdDescriptionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_purchProdDescriptionKeyReleased
        String query = "SELECT product.Id as Id, product.Brand_Id as brandId, brand.BrandName as brandName,"
                + " product.Category_Id as categoryId, category.Description as categoryName,"
                + " product.Description as description, product.TotalQuantity as totalQuantity, product.orderedQuantity as orderedQuantity"
                + " FROM ((product JOIN brand ON product.Brand_Id=brand.Id) JOIN category ON product.Category_Id=category.Id)"
                + " WHERE product.Status = 1 and product.Description like '%" + purchProdDescription.getText().toString() + "%'";
        fillPurchaseProdTable(query);
    }//GEN-LAST:event_purchProdDescriptionKeyReleased

    private void purchBatchTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchBatchTableMouseClicked
        int selectedRow = purchBatchTable.getSelectedRow();
        purchBarcode.setText(purchBatchTable.getValueAt(selectedRow, 2).toString());
        purchExpireDate.setText(purchBatchTable.getValueAt(selectedRow, 7) == null ? "" : purchBatchTable.getValueAt(selectedRow, 7).toString());
        purchManufacDate.setText(purchBatchTable.getValueAt(selectedRow, 6) == null ? "" : purchBatchTable.getValueAt(selectedRow, 6).toString());
        purchPurchasePrice.setText(purchBatchTable.getValueAt(selectedRow, 4).toString());
        purchBatchId.setText(purchBatchTable.getValueAt(selectedRow, 0).toString());
    }//GEN-LAST:event_purchBatchTableMouseClicked

    private void purchProdBatchNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_purchProdBatchNumberKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String query2 = "SELECT batchesofproduct.Id as batchid,"
                    + " batchesofproduct.Barcode as Barcode,"
                    + " batchesofproduct.BatchNumber as BatchNumber,"
                    + " batchesofproduct.QuantityByBatch as quantity,"
                    + " batchesofproduct.PurchasePrice as purchPrice,"
                    + " batchesofproduct.RetailPrice AS RetailPrice"
                    + " FROM batchesofproduct "
                    + " WHERE batchesofproduct.Status = 1 and batchesofproduct.BatchNumber=" + purchProdBatchNumber.getText().toString();
            fillPurchaseBatchTable(query2);
        }
    }//GEN-LAST:event_purchProdBatchNumberKeyReleased

    private void purchProductIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_purchProductIdKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String query = "SELECT `Id`, `Description` FROM `product` WHERE status=1 and Id="
                    + purchProductId.getText();
            try {
                ResultSet rs = DbConnect.getFromDB(query);
                if (rs.next()) {
                    purchDescription.setText(rs.getString("Description").toString());
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Purchase.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Purchase.class.getName()).log(Level.SEVERE, null, ex);
            }
            purchBarcode.setText("");
            purchExpireDate.setText("");
            purchManufacDate.setText("");
            purchPurchasePrice.setText("");
            purchQuantity.setText("");
            purchBatchId.setText("");

            String query1 = "SELECT product.Id as Id, product.Brand_Id as brandId, brand.BrandName as brandName,"
                    + " product.Category_Id as categoryId, category.Description as categoryName,"
                    + " product.Description as description, product.TotalQuantity as totalQuantity, product.orderedQuantity as orderedQuantity"
                    + " FROM ((product JOIN brand ON product.Brand_Id=brand.Id) JOIN category ON product.Category_Id=category.Id)"
                    + " WHERE product.Status = 1 and product.Id=" + purchProductId.getText();
            fillPurchaseProdTable(query1);
            String query2 = "SELECT batchesofproduct.Id as batchid,"
                    + " batchesofproduct.Barcode as Barcode,"
                    + " batchesofproduct.BatchNumber as BatchNumber,"
                    + " batchesofproduct.QuantityByBatch as quantity,"
                    + " batchesofproduct.PurchasePrice as purchPrice,"
                    + " batchesofproduct.RetailPrice AS RetailPrice"
                    + " FROM batchesofproduct "
                    + " WHERE batchesofproduct.Status = 1 and batchesofproduct.Product_Id=" + purchProductId.getText();
            fillPurchaseBatchTable(query2);
        }
    }//GEN-LAST:event_purchProductIdKeyReleased

    private void purchBarcodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_purchBarcodeKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int prodId = 0;
            String query = "SELECT batchesofproduct.Id as batchId,"
                    + " batchesofproduct.Product_Id as ProductId,"
                    + " product.Description as description,"
                    + " batchesofproduct.Barcode as Barcode,"
                    + " batchesofproduct.PurchasePrice as PurchasePrice,"
                    + " datesofbatch.ManufactureDate as manufacDate,"
                    + " datesofbatch.ExpireDate as expDate"
                    + " FROM ((`batchesofproduct`"
                    + " JOIN product on batchesofproduct.Product_Id=product.Id)"
                    + " JOIN datesofbatch on batchesofproduct.Id=datesofbatch.BatchesOfProduct_Id)"
                    + " WHERE batchesofproduct.Barcode=" + purchBarcode.getText().toString().trim();
            try {
                ResultSet rs = DbConnect.getFromDB(query);
                if (rs.next()) {
                    prodId = Integer.parseInt(rs.getString("ProductId").toString());
                    purchProductId.setText(rs.getString("ProductId").toString());
                    purchBatchId.setText(rs.getString("ProductId").toString());
                    purchDescription.setText(rs.getString("description").toString());
                    purchBarcode.setText(rs.getString("Barcode").toString());
                    purchPurchasePrice.setText(rs.getString("PurchasePrice").toString());
                    purchManufacDate.setText(rs.getString("manufacDate").toString());
                    purchExpireDate.setText(rs.getString("expDate").toString());
                }
                String query1 = "SELECT product.Id as Id, product.Brand_Id as brandId, brand.BrandName as brandName,"
                        + " product.Category_Id as categoryId, category.Description as categoryName,"
                        + " product.Description as description, product.TotalQuantity as totalQuantity, product.orderedQuantity as orderedQuantity"
                        + " FROM ((product JOIN brand ON product.Brand_Id=brand.Id) JOIN category ON product.Category_Id=category.Id)"
                        + " WHERE product.Status = 1 and product.Id=" + prodId;
                fillPurchaseProdTable(query1);

                String query2 = "SELECT batchesofproduct.Id as batchid,"
                        + " batchesofproduct.Barcode as Barcode,"
                        + " batchesofproduct.BatchNumber as BatchNumber,"
                        + " batchesofproduct.QuantityByBatch as quantity,"
                        + " batchesofproduct.PurchasePrice as purchPrice,"
                        + " batchesofproduct.RetailPrice AS RetailPrice"
                        + " FROM batchesofproduct "
                        + " WHERE batchesofproduct.Status = 1 and batchesofproduct.Product_Id=" + prodId;
                fillPurchaseBatchTable(query2);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Purchase.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Purchase.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_purchBarcodeKeyReleased

    private void purchQuantityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_purchQuantityKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_purchQuantityKeyReleased

    private void purchPurchasePriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_purchPurchasePriceKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_purchPurchasePriceKeyReleased

    private void purchAddToTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchAddToTableActionPerformed
        Vector v = new Vector();
        v.add(purchProductId.getText());
        v.add(purchDescription.getText());
        v.add(purchBatchId.getText());
        v.add(purchPurchasePrice.getText());
        v.add(purchQuantity.getText());
        v.add(Double.parseDouble(purchPurchasePrice.getText()) * Integer.parseInt(purchQuantity.getText()));

        tablemodel = (DefaultTableModel) purchProduct.getModel();
        tablemodel.addRow(v);

        purchProductId.setText("");
        purchBarcode.setText("");
        purchDescription.setText("");
        purchExpireDate.setText("");
        purchManufacDate.setText("");
        purchPurchasePrice.setText("");
        purchQuantity.setText("");
        purchBatchId.setText("");
        calPurchaseDetails();
    }//GEN-LAST:event_purchAddToTableActionPerformed

    private void purchCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchCompleteActionPerformed
        if ((purchProduct.getRowCount() > 0) && (purchSupplierCombo.getSelectedIndex() > 0)) {
            String date = new Date().toInstant().atZone(ZoneId.systemDefault()).toLocalDate().format(defaultDateFormat);

            calPurchaseDetails();

            int userProId = SystemUser.getUserId();
            int currentPurchaseId = 0;

            String purchQuery = "INSERT INTO `purchase`(`PurchaseDate`, `Total`, `Discount`, `Balance`,"
                    + " `Supplier_Id`, `UserProfile_Id`,`PurchaseOrder_Id`) "
                    + "VALUES ('" + date + "'," + totalWithNoDiscount + "," + discount + "," + finalTotal + ","
                    + supplierId + "," + userProId + "," + purchaseOrderId + ")";
            try {
                PreparedStatement pst = DbConnect.getDBConnection().prepareStatement(purchQuery, Statement.RETURN_GENERATED_KEYS);
                pst.executeUpdate();
                ResultSet rs = pst.getGeneratedKeys();
                if (rs.next()) {
                    currentPurchaseId = rs.getInt(1);
                }
            } catch (SQLException e) {
                e.printStackTrace();
            } catch (ClassNotFoundException e) {
                e.printStackTrace();
            } catch (Exception e) {
                e.printStackTrace();
            }

            for (int i = 0; i < purchProduct.getRowCount(); i++) {
                String proId = purchProduct.getValueAt(i, 0).toString();
                String batchId = purchProduct.getValueAt(i, 2).toString();
                String purchPrice = purchProduct.getValueAt(i, 3).toString();
                String quantity = purchProduct.getValueAt(i, 4).toString();
                String itemTotal = purchProduct.getValueAt(i, 5).toString();

                try {
                    String purchPriceAndQuantity = "select PurchasePrice,QuantityByBatch as TotalQuantity from batchesofproduct"
                            + " where Id=" + batchId;
                    ResultSet rs = DbConnect.getFromDB(purchPriceAndQuantity);
                    double prePurchPrice = 0.0;
                    int preQuantity = 0;
                    if (rs.next()) {
                        prePurchPrice = rs.getDouble("PurchasePrice");
                        preQuantity = rs.getInt("TotalQuantity");
                    }
                    double curStockValue = prePurchPrice * preQuantity;
                    double newStockValue = Double.parseDouble(purchPrice) * Integer.parseInt(quantity);
                    double avgPurchPrice = (curStockValue + newStockValue) / (Integer.parseInt(quantity) + preQuantity);

                    String updateBatch = "UPDATE batchesofproduct SET PurchasePrice=" + avgPurchPrice
                            + ",QuantityByBatch=QuantityByBatch+" + quantity + " WHERE Id=" + batchId;

                    String itemQuery = "INSERT INTO `purchaseitem`( `Purchase_Id`, `Product_Id`, `PurchasePrice`,"
                            + " `Quantity`, `TotalPrice`, `BatchesOfProduct_Id`) "
                            + "VALUES (" + currentPurchaseId + "," + proId + "," + purchPrice + ","
                            + quantity + "," + itemTotal + "," + batchId + ")";

                    String updateProduct = "UPDATE product SET TotalQuantity=TotalQuantity+"
                            + quantity + ", OrderedQuantity=OrderedQuantity-" + quantity + " WHERE Id=" + proId;

                    String purchaseOrderQuery = "UPDATE `purchaseorder` SET `IsSupplied`=1 WHERE `Id`=" + purchaseOrderId;

                    DbConnect.pushToDB(itemQuery);
                    DbConnect.pushToDB(updateBatch);
                    DbConnect.pushToDB(updateProduct);
                    DbConnect.pushToDB(purchaseOrderQuery);
                } catch (SQLException e) {
                    e.printStackTrace();
                } catch (ClassNotFoundException e) {
                    e.printStackTrace();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
            if (currentPurchaseId > 0) {
                printInvoice(currentPurchaseId);
            }
            clearPurchPanel();
            calPurchaseDetails();
        } else {
            if (purchProduct.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "No Items In the Purchased Product Table");
            }
            if (purchSupplierCombo.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(this, "Please select Supplier");
            }
        }
    }//GEN-LAST:event_purchCompleteActionPerformed

    private void printInvoice(int invoiceId) {
        try {
            HashMap<String, Object> para = new HashMap<String, Object>();
            para.put("purchaseId", invoiceId);
            JasperPrint jprint = JasperFillManager.fillReport(Report.purchaseReport, para, DbConnect.getDBConnection());
            JasperViewer.viewReport(jprint, false);
        } catch (JRException ex) {
            Logger.getLogger(Sale.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(Sale.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void purchDeleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchDeleteItemActionPerformed
        try {
            tablemodel = (DefaultTableModel) purchProduct.getModel();
            tablemodel.removeRow(purchProduct.getSelectedRow());
            calPurchaseDetails();
        } catch (ArrayIndexOutOfBoundsException e) {
        }
    }//GEN-LAST:event_purchDeleteItemActionPerformed

    private void purchCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchCancelActionPerformed
        clearPurchPanel();
    }//GEN-LAST:event_purchCancelActionPerformed

    private void purchDiscountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_purchDiscountKeyReleased
        calPurchaseDetails();
    }//GEN-LAST:event_purchDiscountKeyReleased

    private void purchDisAmountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchDisAmountMouseClicked
        calPurchaseDetails();
    }//GEN-LAST:event_purchDisAmountMouseClicked

    private void purchDisPercentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchDisPercentMouseClicked
        calPurchaseDetails();
    }//GEN-LAST:event_purchDisPercentMouseClicked

    private void purchProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchProductMouseClicked

    }//GEN-LAST:event_purchProductMouseClicked

    private void purchSupplierComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchSupplierComboActionPerformed
        if (purchSupplierCombo.getSelectedIndex() > 0) {
            supplierId = Integer.parseInt(purchSupplierCombo.getSelectedItem().toString().split(" - ")[0].trim());
            String query = "SELECT product.Id as Id, product.Brand_Id as brandId, brand.BrandName as brandName,"
                    + " product.Category_Id as categoryId, category.Description as categoryName,"
                    + " product.Description as description, product.TotalQuantity as totalQuantity, product.orderedQuantity as orderedQuantity"
                    + " FROM (((product JOIN brand ON product.Brand_Id=brand.Id)"
                    + " JOIN category ON product.Category_Id=category.Id)"
                    + " JOIN SupplierProduct ON product.Id=SupplierProduct.Product_Id)"
                    + " WHERE product.Status = 1 and SupplierProduct.Supplier_Id=" + supplierId;
            fillPurchaseProdTable(query);
            loadPurchaseOrderCombo();
        }
    }//GEN-LAST:event_purchSupplierComboActionPerformed

    private void purchProdBarcodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_purchProdBarcodeKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String query2 = "SELECT batchesofproduct.Id as batchid,"
                    + " batchesofproduct.Barcode as Barcode,"
                    + " batchesofproduct.BatchNumber as BatchNumber,"
                    + " batchesofproduct.QuantityByBatch as quantity,"
                    + " batchesofproduct.PurchasePrice as purchPrice,"
                    + " batchesofproduct.RetailPrice AS RetailPrice"
                    + " FROM batchesofproduct "
                    + " WHERE batchesofproduct.Status = 1 and batchesofproduct.barcode=" + purchProdBarcode.getText().toString();
            fillPurchaseBatchTable(query2);
        }
    }//GEN-LAST:event_purchProdBarcodeKeyReleased

    private void purchPurchaseOrderComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchPurchaseOrderComboActionPerformed
        if (purchPurchaseOrderCombo.getSelectedIndex() > 0) {
            purchaseOrderId = Integer.parseInt(purchPurchaseOrderCombo.getSelectedItem().toString().split(" - ")[0].trim());
            String query = "SELECT product.Id as Id,"
                    + " product.Brand_Id as brandId,"
                    + " brand.BrandName as brandName,"
                    + " product.Category_Id as categoryId,"
                    + " category.Description as categoryName,"
                    + " product.Description as description,"
                    + " product.TotalQuantity as totalQuantity,"
                    + " product.orderedQuantity as orderedQuantity"
                    + " FROM (((purchaseorderitem JOIN product ON purchaseorderitem.Product_Id=product.Id)"
                    + " JOIN brand ON product.Brand_Id=brand.Id)"
                    + " join category ON product.Category_Id=category.Id)"
                    + " WHERE purchaseorderitem.PurchaseOrder_Id=" + purchaseOrderId;
            fillPurchaseProdTable(query);
        }
    }//GEN-LAST:event_purchPurchaseOrderComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JButton purchAddToTable;
    private app.bolivia.swing.JCTextField purchBarcode;
    private javax.swing.JLabel purchBatchId;
    private rojeru_san.complementos.RSTableMetro purchBatchTable;
    private javax.swing.JButton purchCancel;
    private javax.swing.JButton purchComplete;
    private javax.swing.JButton purchDeleteItem;
    private javax.swing.JLabel purchDescription;
    private javax.swing.JRadioButton purchDisAmount;
    private javax.swing.ButtonGroup purchDisGroup;
    private javax.swing.JRadioButton purchDisPercent;
    private app.bolivia.swing.JCTextField purchDiscount;
    private javax.swing.JLabel purchExpireDate;
    private javax.swing.JLabel purchFinalDiscount;
    private javax.swing.JLabel purchManufacDate;
    private app.bolivia.swing.JCTextField purchProdBarcode;
    private app.bolivia.swing.JCTextField purchProdBatchNumber;
    private app.bolivia.swing.JCTextField purchProdDescription;
    private rojeru_san.complementos.RSTableMetro purchProdTable;
    private rojeru_san.complementos.RSTableMetro purchProduct;
    private app.bolivia.swing.JCTextField purchProductId;
    private javax.swing.JComboBox<String> purchPurchaseOrderCombo;
    private app.bolivia.swing.JCTextField purchPurchasePrice;
    private app.bolivia.swing.JCTextField purchQuantity;
    private javax.swing.JLabel purchSubTotal;
    private javax.swing.JComboBox<String> purchSupplierCombo;
    private javax.swing.JLabel purchTotal;
    // End of variables declaration//GEN-END:variables
}
