/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.xpos.gui;

import com.xpos.SystemUser;
import com.xpos.database.DbConnect;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jamit
 */
public class QuateInvoice extends javax.swing.JPanel {

    /**
     * Creates new form Purchase
     */
    public QuateInvoice() {
        initComponents();
        fillQuateInvoiceTable(null);
    }

    private void fillQuateInvoiceTable(String query) {
        DefaultTableModel tableModel = (DefaultTableModel) quateItemTable.getModel();
        tableModel.setRowCount(0);
        tableModel = (DefaultTableModel) quateTable.getModel();
        tableModel.setRowCount(0);
        try {
            if (query == null) {
                query = "SELECT reqforquate.Id as quatereqid,"
                        + " reqforquate.Date as quatereqdate,"
                        + " reqforquate.IsResponses as IsResponses,"
                        + " reqforquate.Supplier_Id as Supplier_Id,"
                        + " reqforquate.UserProfile_Id as userprofile,"
                        + " supplier.Name as suppliername,"
                        + " userprofile.Username as username"
                        + " from reqforquate INNER JOIN supplier"
                        + " ON reqforquate.Supplier_Id=supplier.Id"
                        + " INNER JOIN userprofile"
                        + " ON userprofile.Id=reqforquate.UserProfile_Id"
                        + " WHERE reqforquate.Status=1";
            }
            ResultSet rs = DbConnect.getFromDB(query);
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getInt("quatereqid"));
                v.add(rs.getDate("quatereqdate"));
                v.add(rs.getInt("Supplier_Id") + " - " + rs.getString("suppliername"));
                v.add(rs.getBoolean("IsResponses")? "Responsed":"Not Responsed");
                v.add(rs.getString("username"));
                tableModel.addRow(v);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PurchaseInvoice.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PurchaseInvoice.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void fillQuateItemTable(int quateId) {
        if (quateId == 0) {
            quateId = Integer.parseInt(quateTable.getValueAt(quateTable.getSelectedRow(), 0).toString());
        }
        DefaultTableModel tableModel = (DefaultTableModel) quateItemTable.getModel();
        tableModel.setRowCount(0);
        try {

            String query = "SELECT *,"
                    + "(select supplierproduct.ItemCode from supplierproduct"
                    + " WHERE supplierproduct.Supplier_Id=(SELECT reqforquate.Supplier_Id FROM reqforquate"
                    + " WHERE reqforquate.Id=reqforquateitem.ReqForQuate_Id"
                    + ") AND supplierproduct.Product_Id=reqforquateitem.Product_Id) as itemcode,"
                    + "(SELECT product.Description FROM product WHERE product.Id=Product_Id) as productName"
                    + " FROM `reqforquateitem` WHERE reqforquateitem.ReqForQuate_Id=" + quateId;

            ResultSet rs = DbConnect.getFromDB(query);
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getInt("product_Id"));
                v.add(rs.getString("productName"));
                v.add(rs.getString("itemcode"));
                v.add(rs.getInt("quantity"));
                tableModel.addRow(v);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SaleInvoice.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SaleInvoice.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        saleSearchByInvoice = new app.bolivia.swing.JCTextField();
        saleSearchByCustomer = new app.bolivia.swing.JCTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        quateTable = new rojeru_san.complementos.RSTableMetro();
        jScrollPane3 = new javax.swing.JScrollPane();
        quateItemTable = new rojeru_san.complementos.RSTableMetro();
        butSetResponsed = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setBackground(new java.awt.Color(26, 140, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("QUATE INVOICE");
        jLabel13.setOpaque(true);

        saleSearchByInvoice.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Invoice Number", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        saleSearchByInvoice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saleSearchByInvoice.setPhColor(new java.awt.Color(0, 51, 255));
        saleSearchByInvoice.setPlaceholder("Search Invoice Number");
        saleSearchByInvoice.setPreferredSize(new java.awt.Dimension(200, 30));
        saleSearchByInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleSearchByInvoiceActionPerformed(evt);
            }
        });
        saleSearchByInvoice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                saleSearchByInvoiceKeyReleased(evt);
            }
        });

        saleSearchByCustomer.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Search Customer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        saleSearchByCustomer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saleSearchByCustomer.setPhColor(new java.awt.Color(0, 51, 255));
        saleSearchByCustomer.setPlaceholder("Search Customer");
        saleSearchByCustomer.setPreferredSize(new java.awt.Dimension(200, 30));
        saleSearchByCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleSearchByCustomerActionPerformed(evt);
            }
        });
        saleSearchByCustomer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                saleSearchByCustomerKeyReleased(evt);
            }
        });

        quateTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Date", "Supplier", "Is Responsed", "System User"
            }
        ));
        quateTable.setColorBackgoundHead(new java.awt.Color(26, 140, 255));
        quateTable.setFuenteHead(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quateTable.setRowHeight(25);
        quateTable.setRowMargin(0);
        quateTable.setSelectionBackground(new java.awt.Color(0, 60, 128));
        quateTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quateTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(quateTable);

        quateItemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Id", "Product Name", "Item Code", "Quantity"
            }
        ));
        quateItemTable.setColorBackgoundHead(new java.awt.Color(26, 140, 255));
        quateItemTable.setFuenteHead(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quateItemTable.setRowHeight(25);
        quateItemTable.setRowMargin(0);
        quateItemTable.setSelectionBackground(new java.awt.Color(0, 60, 128));
        quateItemTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quateItemTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(quateItemTable);

        butSetResponsed.setBackground(new java.awt.Color(0, 60, 128));
        butSetResponsed.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butSetResponsed.setForeground(new java.awt.Color(255, 255, 255));
        butSetResponsed.setText("SET RESPONSED");
        butSetResponsed.setBorder(null);
        butSetResponsed.setFocusPainted(false);
        butSetResponsed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSetResponsedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saleSearchByInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saleSearchByCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(794, 794, 794)
                        .addComponent(butSetResponsed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saleSearchByInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saleSearchByCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butSetResponsed, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saleSearchByInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleSearchByInvoiceActionPerformed
        
    }//GEN-LAST:event_saleSearchByInvoiceActionPerformed

    private void saleSearchByInvoiceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_saleSearchByInvoiceKeyReleased
       
    }//GEN-LAST:event_saleSearchByInvoiceKeyReleased

    private void saleSearchByCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleSearchByCustomerActionPerformed
        
    }//GEN-LAST:event_saleSearchByCustomerActionPerformed

    private void saleSearchByCustomerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_saleSearchByCustomerKeyReleased
        
    }//GEN-LAST:event_saleSearchByCustomerKeyReleased

    private void quateTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quateTableMouseClicked
        fillQuateItemTable(0);
    }//GEN-LAST:event_quateTableMouseClicked

    private void quateItemTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quateItemTableMouseClicked
        
    }//GEN-LAST:event_quateItemTableMouseClicked

    private void butSetResponsedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSetResponsedActionPerformed
        try {
            String query = "UPDATE `reqforquate` SET `IsResponses`=1 WHERE `Id`="+quateTable.getValueAt(quateTable.getSelectedRow(), 0);
            DbConnect.pushToDB(query);
            fillQuateInvoiceTable(null);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QuateInvoice.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(QuateInvoice.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_butSetResponsedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butSetResponsed;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private rojeru_san.complementos.RSTableMetro quateItemTable;
    private rojeru_san.complementos.RSTableMetro quateTable;
    private app.bolivia.swing.JCTextField saleSearchByCustomer;
    private app.bolivia.swing.JCTextField saleSearchByInvoice;
    // End of variables declaration//GEN-END:variables
}
