/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.xpos.gui;

import com.xpos.database.DbConnect;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import com.xpos.commons.Validate;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Jamit
 */
public class ReturnInvoice extends javax.swing.JPanel {

    /**
     * Creates new form Brand
     */
    public ReturnInvoice() {
        initComponents();
        fillReturnInvoiceTable(null);
    }

    private void fillReturnInvoiceTable(String query) {
        DefaultTableModel tableModel = (DefaultTableModel) returnItemTable.getModel();
        tableModel.setRowCount(0);
        tableModel = (DefaultTableModel) returnTable.getModel();
        tableModel.setRowCount(0);
        try {
            if (query == null) {
                query = "SELECT `return`.`Id` as returnId,"
                        + " `return`.`Sale_Id` as saleId,"
                        + " `return`.`Date` as saleDate,"
                        + " `return`.`RefundAmount` as refundTotal,"
                        + " sale.Customer_Id as customerId,"
                        + " customer.Name as customerName"
                        + " FROM ((`return`"
                        + " JOIN sale on `return`.Sale_Id=sale.Id)"
                        + " JOIN customer ON sale.Customer_Id=customer.Id)"
                        + " WHERE `return`.`Status`=1";
            }
            ResultSet rs = DbConnect.getFromDB(query);
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getInt("returnId"));
                v.add(rs.getInt("saleId"));
                v.add(rs.getDate("saleDate"));
                v.add(rs.getInt("customerId") + " - " + rs.getString("customerName"));
                v.add(rs.getFloat("refundTotal"));
                tableModel.addRow(v);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PurchaseInvoice.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PurchaseInvoice.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void fillReturnItemTable(int returnId) {
        if (returnId == 0) {
            returnId = Integer.parseInt(returnTable.getValueAt(returnTable.getSelectedRow(), 0).toString());
        }
        DefaultTableModel tableModel = (DefaultTableModel) returnItemTable.getModel();
        tableModel.setRowCount(0);
        try {

            String query = "SELECT `returnitem`.`Product_Id` as productId,"
                    + " `returnitem`.`Type` as type,"
                    + " `returnitem`.`Cond` as cond,"
                    + " `returnitem`.`Quantity` as quantity,"
                    + " `returnitem`.`ReturnPrice` as refundTotal,"
                    + " product.Description as description"
                    + " FROM `returnitem`"
                    + " JOIN product ON returnitem.Product_Id=product.Id"
                    + " WHERE `returnitem`.`Status`=1 and returnitem.`Return_Id`=" + returnId;

            ResultSet rs = DbConnect.getFromDB(query);
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getInt("productId") + " - " + rs.getString("description"));
                v.add(rs.getString("type").equals("C") ? "Cash Refund" : "Exchange");
                v.add(rs.getString("cond").equals("D") ? "Damage" : "Good");
                v.add(rs.getInt("quantity"));
                v.add(rs.getFloat("refundTotal"));
                tableModel.addRow(v);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PurchaseInvoice.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PurchaseInvoice.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        returnTable = new rojeru_san.complementos.RSTableMetro();
        returnSearchBySaleInvoice = new app.bolivia.swing.JCTextField();
        returnSearchByCustomer = new app.bolivia.swing.JCTextField();
        returnSearchByReturnInvoice = new app.bolivia.swing.JCTextField();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        returnItemTable = new rojeru_san.complementos.RSTableMetro();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setBackground(new java.awt.Color(26, 140, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("RETURN INVOICES");
        jLabel6.setOpaque(true);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        returnTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "sale ID", "Date", "Customer", "Total Refund Amount"
            }
        ));
        returnTable.setColorBackgoundHead(new java.awt.Color(26, 140, 255));
        returnTable.setFuenteHead(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        returnTable.setRowHeight(25);
        returnTable.setRowMargin(0);
        returnTable.setSelectionBackground(new java.awt.Color(0, 60, 128));
        returnTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(returnTable);

        returnSearchBySaleInvoice.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Sale Invoice Number", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        returnSearchBySaleInvoice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        returnSearchBySaleInvoice.setPhColor(new java.awt.Color(0, 51, 255));
        returnSearchBySaleInvoice.setPlaceholder("Search Sale Invoice No");
        returnSearchBySaleInvoice.setPreferredSize(new java.awt.Dimension(200, 30));
        returnSearchBySaleInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnSearchBySaleInvoiceActionPerformed(evt);
            }
        });
        returnSearchBySaleInvoice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                returnSearchBySaleInvoiceKeyReleased(evt);
            }
        });

        returnSearchByCustomer.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Search Customer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        returnSearchByCustomer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        returnSearchByCustomer.setPhColor(new java.awt.Color(0, 51, 255));
        returnSearchByCustomer.setPlaceholder("Search Customer");
        returnSearchByCustomer.setPreferredSize(new java.awt.Dimension(200, 30));
        returnSearchByCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnSearchByCustomerActionPerformed(evt);
            }
        });
        returnSearchByCustomer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                returnSearchByCustomerKeyReleased(evt);
            }
        });

        returnSearchByReturnInvoice.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Return Invoice Number", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        returnSearchByReturnInvoice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        returnSearchByReturnInvoice.setPhColor(new java.awt.Color(0, 51, 255));
        returnSearchByReturnInvoice.setPlaceholder("Search Return Invoice No");
        returnSearchByReturnInvoice.setPreferredSize(new java.awt.Dimension(200, 30));
        returnSearchByReturnInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnSearchByReturnInvoiceActionPerformed(evt);
            }
        });
        returnSearchByReturnInvoice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                returnSearchByReturnInvoiceKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(returnSearchBySaleInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(returnSearchByReturnInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(returnSearchByCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 88, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnSearchBySaleInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnSearchByCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnSearchByReturnInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        returnItemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID - Product", "Return Type", "Product Condition", "Quantity", "Refund Total"
            }
        ));
        returnItemTable.setColorBackgoundHead(new java.awt.Color(26, 140, 255));
        returnItemTable.setFuenteHead(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        returnItemTable.setRowHeight(25);
        returnItemTable.setRowMargin(0);
        returnItemTable.setSelectionBackground(new java.awt.Color(0, 60, 128));
        returnItemTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnItemTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(returnItemTable);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void returnTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnTableMouseClicked
        fillReturnItemTable(Integer.parseInt(returnTable.getValueAt(returnTable.getSelectedRow(), 0).toString()));
    }//GEN-LAST:event_returnTableMouseClicked

    private void returnSearchBySaleInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnSearchBySaleInvoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_returnSearchBySaleInvoiceActionPerformed

    private void returnSearchBySaleInvoiceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_returnSearchBySaleInvoiceKeyReleased
        String query = null;
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int saleId = Integer.parseInt(returnSearchBySaleInvoice.getText().toString().equals("") ? "0" : returnSearchBySaleInvoice.getText().toString());
            if (saleId != 0) {
                query = "SELECT `return`.`Id` as returnId,"
                        + " `return`.`Sale_Id` as saleId,"
                        + " `return`.`Date` as saleDate,"
                        + " `return`.`RefundAmount` as refundTotal,"
                        + " sale.Customer_Id as customerId,"
                        + " customer.Name as customerName"
                        + " FROM ((`return`"
                        + " JOIN sale on `return`.Sale_Id=sale.Id)"
                        + " JOIN customer ON sale.Customer_Id=customer.Id)"
                        + " WHERE `return`.`Status`=1 and return.Sale_Id=" + saleId;
            }
        }
        fillReturnInvoiceTable(query);

    }//GEN-LAST:event_returnSearchBySaleInvoiceKeyReleased

    private void returnItemTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnItemTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_returnItemTableMouseClicked

    private void returnSearchByCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnSearchByCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_returnSearchByCustomerActionPerformed

    private void returnSearchByCustomerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_returnSearchByCustomerKeyReleased
        String query = "SELECT `return`.`Id` as returnId,"
                + " `return`.`Sale_Id` as saleId,"
                + " `return`.`Date` as saleDate,"
                + " `return`.`RefundAmount` as refundTotal,"
                + " sale.Customer_Id as customerId,"
                + " customer.Name as customerName"
                + " FROM ((`return`"
                + " JOIN sale on `return`.Sale_Id=sale.Id)"
                + " JOIN customer ON sale.Customer_Id=customer.Id)"
                + " WHERE `return`.`Status`=1 and customer.Name like '%" + returnSearchByCustomer.getText().toString() + "%'";
        fillReturnInvoiceTable(query);
    }//GEN-LAST:event_returnSearchByCustomerKeyReleased

    private void returnSearchByReturnInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnSearchByReturnInvoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_returnSearchByReturnInvoiceActionPerformed

    private void returnSearchByReturnInvoiceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_returnSearchByReturnInvoiceKeyReleased
        String query = null;
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int returnId = Integer.parseInt(returnSearchByReturnInvoice.getText().toString().equals("") ? "0" : returnSearchByReturnInvoice.getText().toString());
            if (returnId != 0) {
                query = "SELECT `return`.`Id` as returnId,"
                        + " `return`.`Sale_Id` as saleId,"
                        + " `return`.`Date` as saleDate,"
                        + " `return`.`RefundAmount` as refundTotal,"
                        + " sale.Customer_Id as customerId,"
                        + " customer.Name as customerName"
                        + " FROM ((`return`"
                        + " JOIN sale on `return`.Sale_Id=sale.Id)"
                        + " JOIN customer ON sale.Customer_Id=customer.Id)"
                        + " WHERE `return`.`Status`=1 and `return`.`Id`=" + returnId;
            }
        }
        fillReturnInvoiceTable(query);
    }//GEN-LAST:event_returnSearchByReturnInvoiceKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private rojeru_san.complementos.RSTableMetro returnItemTable;
    private app.bolivia.swing.JCTextField returnSearchByCustomer;
    private app.bolivia.swing.JCTextField returnSearchByReturnInvoice;
    private app.bolivia.swing.JCTextField returnSearchBySaleInvoice;
    private rojeru_san.complementos.RSTableMetro returnTable;
    // End of variables declaration//GEN-END:variables
}
