/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.xpos.gui;

import com.xpos.database.DbConnect;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jamit
 */
public class SelectInvoicePopup extends javax.swing.JPanel {

    DefaultTableModel tablemodel;
    String invoiceId;

    public String getInvoiceId() {
        return invoiceId;
    }

    private void setInvoiceId(String cusIdName) {
        this.invoiceId = cusIdName;
    }

    /**
     * Creates new form SelectCustPopup
     */
    public SelectInvoicePopup() {
        initComponents();
        fillInvoiceTable(null);
    }

    public void fillInvoiceTable(String query) {
        tablemodel = (DefaultTableModel) invoiceTable.getModel();
        tablemodel.setRowCount(0);
        if (query == null) {
            query = "SELECT sale.Id, sale.Date, sale.Time, sale.Customer_Id,sale.FinalTotal,customer.Name"
                    + " FROM `sale` JOIN customer ON customer.Id=sale.Customer_Id"
                    + " WHERE sale.STATUS=1";
        }
        try {
            ResultSet rs = DbConnect.getFromDB(query);
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getInt("Id"));
                v.add(rs.getDate("Date") + " - " + rs.getTime("Time"));
                v.add(rs.getInt("Customer_Id") + " - " + rs.getString("Name"));
                v.add(rs.getDouble("FinalTotal"));
                tablemodel.addRow(v);
            }
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        invoiceTable = new rojeru_san.complementos.RSTableMetro();
        invoiceSearch = new app.bolivia.swing.JCTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        invoiceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Invoice ID", "Date - Time", "Customer", "Final Total"
            }
        ));
        invoiceTable.setColorBackgoundHead(new java.awt.Color(26, 140, 255));
        invoiceTable.setRowHeight(25);
        invoiceTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                invoiceTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(invoiceTable);

        invoiceSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        invoiceSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        invoiceSearch.setPhColor(new java.awt.Color(0, 51, 255));
        invoiceSearch.setPlaceholder("Search by invoice Id and customer Name");
        invoiceSearch.setPreferredSize(new java.awt.Dimension(200, 30));
        invoiceSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                invoiceSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                    .addComponent(invoiceSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(invoiceSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void invoiceSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_invoiceSearchKeyReleased
        String query = "SELECT sale.Id, sale.Date, sale.Time, sale.Customer_Id, sale.FinalTotal, customer.Name"
                + " FROM `sale` JOIN customer ON customer.Id=sale.Customer_Id"
                + " WHERE ((customer.Name LIKE '%" + invoiceSearch.getText().toString() + "%')"
                + " OR (sale.Id LIKE '%" + invoiceSearch.getText().toString() + "%'))"
                + " AND sale.Status=1";
        fillInvoiceTable(query);
    }//GEN-LAST:event_invoiceSearchKeyReleased

    private void invoiceTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invoiceTableMouseClicked
        setInvoiceId(invoiceTable.getValueAt(invoiceTable.getSelectedRow(), 0).toString());
    }//GEN-LAST:event_invoiceTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.bolivia.swing.JCTextField invoiceSearch;
    private rojeru_san.complementos.RSTableMetro invoiceTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
