/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.xpos.gui;

/**
 *
 * @author Jamit
 */
public class SupplierProduct extends javax.swing.JPanel {

    /**
     * Creates new form SupplierProduct
     */
    public SupplierProduct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        supName = new app.bolivia.swing.JCTextField();
        supButInsert = new javax.swing.JButton();
        supButEdit = new javax.swing.JButton();
        supButDelete = new javax.swing.JButton();
        supButCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        supName1 = new app.bolivia.swing.JCTextField();
        jLabel2 = new javax.swing.JLabel();
        supName2 = new app.bolivia.swing.JCTextField();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        supplierTable = new rojeru_san.complementos.RSTableMetro();
        supSearch = new app.bolivia.swing.JCTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        productTable = new rojeru_san.complementos.RSTableMetro();
        prodSearch = new app.bolivia.swing.JCTextField();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        supplierTable1 = new rojeru_san.complementos.RSTableMetro();
        supSearch1 = new app.bolivia.swing.JCTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setBackground(new java.awt.Color(26, 140, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("SUPPLIER PRODUCTS");
        jLabel5.setOpaque(true);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        supName.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Supplier ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        supName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        supName.setPhColor(new java.awt.Color(0, 51, 255));
        supName.setPlaceholder("Supplier ID");
        supName.setPreferredSize(new java.awt.Dimension(200, 30));

        supButInsert.setBackground(new java.awt.Color(0, 60, 128));
        supButInsert.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        supButInsert.setForeground(new java.awt.Color(255, 255, 255));
        supButInsert.setText("INSERT");
        supButInsert.setBorder(null);
        supButInsert.setFocusPainted(false);
        supButInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supButInsertActionPerformed(evt);
            }
        });

        supButEdit.setBackground(new java.awt.Color(0, 60, 128));
        supButEdit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        supButEdit.setForeground(new java.awt.Color(255, 255, 255));
        supButEdit.setText("EDIT");
        supButEdit.setBorder(null);
        supButEdit.setFocusPainted(false);
        supButEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supButEditActionPerformed(evt);
            }
        });

        supButDelete.setBackground(new java.awt.Color(0, 60, 128));
        supButDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        supButDelete.setForeground(new java.awt.Color(255, 255, 255));
        supButDelete.setText("DELETE");
        supButDelete.setBorder(null);
        supButDelete.setFocusPainted(false);
        supButDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supButDeleteActionPerformed(evt);
            }
        });

        supButCancel.setBackground(new java.awt.Color(0, 60, 128));
        supButCancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        supButCancel.setForeground(new java.awt.Color(255, 255, 255));
        supButCancel.setText("CANCEL");
        supButCancel.setBorder(null);
        supButCancel.setFocusPainted(false);
        supButCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supButCancelActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Supplier Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N

        supName1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Select Product", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        supName1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        supName1.setPhColor(new java.awt.Color(0, 51, 255));
        supName1.setPlaceholder("Select Product");
        supName1.setPreferredSize(new java.awt.Dimension(200, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Supplier Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N

        supName2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Item Code", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        supName2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        supName2.setPhColor(new java.awt.Color(0, 51, 255));
        supName2.setPlaceholder("Item Code");
        supName2.setPreferredSize(new java.awt.Dimension(200, 30));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(supName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel11Layout.createSequentialGroup()
                                .addComponent(supButInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(supButEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(supButDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(supButCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(supName1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(supName2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(supName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(supName1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(supName2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supButInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supButEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supButDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supButCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        supplierTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Supplier ID", "Supplier Name", "Product ID", "Product Name", "Item Code"
            }
        ));
        supplierTable.setColorBackgoundHead(new java.awt.Color(26, 140, 255));
        supplierTable.setFuenteHead(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        supplierTable.setRowHeight(25);
        supplierTable.setRowMargin(0);
        supplierTable.setSelectionBackground(new java.awt.Color(0, 60, 128));
        supplierTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supplierTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(supplierTable);

        supSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        supSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        supSearch.setPhColor(new java.awt.Color(0, 51, 255));
        supSearch.setPlaceholder("Search");
        supSearch.setPreferredSize(new java.awt.Dimension(200, 30));
        supSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                supSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(supSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1045, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(supSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Prodcts", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N

        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Description", "Brand", "Category", "Re-Order Level", "Ordered Quantity", "Quantity"
            }
        ));
        productTable.setColorBackgoundHead(new java.awt.Color(26, 140, 255));
        productTable.setFuenteHead(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        productTable.setRowHeight(25);
        productTable.setRowMargin(0);
        productTable.setSelectionBackground(new java.awt.Color(0, 60, 128));
        productTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(productTable);

        prodSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        prodSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        prodSearch.setPhColor(new java.awt.Color(0, 51, 255));
        prodSearch.setPlaceholder("Search");
        prodSearch.setPreferredSize(new java.awt.Dimension(200, 30));
        prodSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodSearchActionPerformed(evt);
            }
        });
        prodSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                prodSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(prodSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane3)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(prodSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Suppliers", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N

        supplierTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Address", "Telephone No", "Register No"
            }
        ));
        supplierTable1.setColorBackgoundHead(new java.awt.Color(26, 140, 255));
        supplierTable1.setFuenteHead(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        supplierTable1.setRowHeight(25);
        supplierTable1.setRowMargin(0);
        supplierTable1.setSelectionBackground(new java.awt.Color(0, 60, 128));
        supplierTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supplierTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(supplierTable1);

        supSearch1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        supSearch1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        supSearch1.setPhColor(new java.awt.Color(0, 51, 255));
        supSearch1.setPlaceholder("Search");
        supSearch1.setPreferredSize(new java.awt.Dimension(200, 30));
        supSearch1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                supSearch1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(supSearch1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(supSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void supButInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supButInsertActionPerformed
//        String name = supName.getText();
//        String address = supAddress.getText();
//        String teleNumber = supTeleNumber.getText();
//        String regNumber = supRegisterNumber.getText();
//
//        String query = "INSERT INTO supplier(Name,Address,TelephoneNo,RegisterNo) VALUES('" + name + "','" + address + "','" + teleNumber + "'," + regNumber + ")";
//        try {
//            DbConnect.pushToDB(query);
//        } catch (SQLException e) {
//            e.printStackTrace();
//        } catch (ClassNotFoundException e) {
//            e.printStackTrace();
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//        clearSupPanel();
    }//GEN-LAST:event_supButInsertActionPerformed

    private void supButEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supButEditActionPerformed
//        String name = supName.getText();
//        String address = supAddress.getText();
//        String teleNumber = supTeleNumber.getText();
//        String regNumber = supRegisterNumber.getText();
//
//        String query = "UPDATE supplier set Name='" + name + "', Address='" + address + "',TelephoneNo='" + teleNumber + "',RegisterNo=" + regNumber + " WHERE Id=" + supplierId;
//        try {
//            DbConnect.pushToDB(query);
//        } catch (SQLException e) {
//            e.printStackTrace();
//        } catch (ClassNotFoundException e) {
//            e.printStackTrace();
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//        clearSupPanel();
    }//GEN-LAST:event_supButEditActionPerformed

    private void supButDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supButDeleteActionPerformed
//        String query = "UPDATE supplier set Status=" + 0 + " where Id=" + supplierId;
//        try {
//            DbConnect.pushToDB(query);
//        } catch (SQLException e) {
//            e.printStackTrace();
//        } catch (ClassNotFoundException e) {
//            e.printStackTrace();
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//        clearSupPanel();
    }//GEN-LAST:event_supButDeleteActionPerformed

    private void supButCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supButCancelActionPerformed
        //clearSupPanel();
    }//GEN-LAST:event_supButCancelActionPerformed

    private void supplierTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierTableMouseClicked
        int selRow = supplierTable.getSelectedRow();
        //supplierId = Integer.parseInt(supplierTable.getValueAt(selRow, 0).toString());

        supName.setText(supplierTable.getValueAt(selRow, 1).toString());
        //supAddress.setText(supplierTable.getValueAt(selRow, 2).toString());
        //supTeleNumber.setText(supplierTable.getValueAt(selRow, 3).toString());
        //supRegisterNumber.setText(supplierTable.getValueAt(selRow, 4).toString());
    }//GEN-LAST:event_supplierTableMouseClicked

    private void supSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_supSearchKeyReleased
        String query = "SELECT * from supplier WHERE Name LIKE '%" + supSearch.getText().toString() + "%' and Status=1";
        //fillSupTable(query);
    }//GEN-LAST:event_supSearchKeyReleased

    private void supplierTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierTable1MouseClicked
//        int selRow = supplierTable.getSelectedRow();
//        supplierId = Integer.parseInt(supplierTable.getValueAt(selRow, 0).toString());
//
//        supName.setText(supplierTable.getValueAt(selRow, 1).toString());
//        supAddress.setText(supplierTable.getValueAt(selRow, 2).toString());
//        supTeleNumber.setText(supplierTable.getValueAt(selRow, 3).toString());
//        supRegisterNumber.setText(supplierTable.getValueAt(selRow, 4).toString());
    }//GEN-LAST:event_supplierTable1MouseClicked

    private void supSearch1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_supSearch1KeyReleased
        String query = "SELECT * from supplier WHERE Name LIKE '%" + supSearch.getText().toString() + "%' and Status=1";
        //fillSupTable(query);
    }//GEN-LAST:event_supSearch1KeyReleased

    private void productTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productTableMouseClicked
//        int selectedRow = productTable.getSelectedRow();
//        productId = Integer.parseInt(productTable.getValueAt(selectedRow, 0).toString());
//        //prodBarcode.setText(productTable.getValueAt(selectedRow, 1).toString());
//        prodDescription.setText(productTable.getValueAt(selectedRow, 2).toString());
//        prodPurchPrice.setText(productTable.getValueAt(selectedRow, 3).toString());
//        prodRetailPrice.setText(productTable.getValueAt(selectedRow, 4).toString());
//        prodQuantity.setText(productTable.getValueAt(selectedRow, 5).toString());
    }//GEN-LAST:event_productTableMouseClicked

    private void prodSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodSearchActionPerformed

    private void prodSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prodSearchKeyReleased
        String query = "select * from product where description like '%" + prodSearch.getText() + "%' and status=1";
        //fillProductTable(query);
    }//GEN-LAST:event_prodSearchKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private app.bolivia.swing.JCTextField prodSearch;
    private rojeru_san.complementos.RSTableMetro productTable;
    private javax.swing.JButton supButCancel;
    private javax.swing.JButton supButDelete;
    private javax.swing.JButton supButEdit;
    private javax.swing.JButton supButInsert;
    private app.bolivia.swing.JCTextField supName;
    private app.bolivia.swing.JCTextField supName1;
    private app.bolivia.swing.JCTextField supName2;
    private app.bolivia.swing.JCTextField supSearch;
    private app.bolivia.swing.JCTextField supSearch1;
    private rojeru_san.complementos.RSTableMetro supplierTable;
    private rojeru_san.complementos.RSTableMetro supplierTable1;
    // End of variables declaration//GEN-END:variables
}
