/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.xpos.gui;

import com.xpos.commons.Validate;
import com.xpos.database.DbConnect;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jamit
 */
public class Supply extends javax.swing.JPanel {

    DefaultTableModel tablemodel;
    int supplierId;

    /**
     * Creates new form Supply
     */
    public Supply() {
        initComponents();
        fillSupTable(null);
    }

    private boolean validateForm() {
        return Validate.isName(supName.getText().toString())
                && Validate.isText(supAddress.getText().toString())
                && Validate.isTelephone(supTeleNumber.getText().toString())
                && Validate.isText(supRegisterNumber.getText().toString());
    }

    public void clearSupPanel() {
        supName.setText("");
        supAddress.setText("");
        supTeleNumber.setText("");
        supRegisterNumber.setText("");
        supSearch.setText("");
        fillSupTable(null);
    }

    public void fillSupTable(String query) {
        tablemodel = (DefaultTableModel) supplierTable.getModel();
        tablemodel.setRowCount(0);
        if (query == null) {
            query = "select * from supplier where Status=1";
        }
        try {
            ResultSet rs = DbConnect.getFromDB(query);
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getInt("Id"));
                v.add(rs.getString("Name"));
                v.add(rs.getString("Address"));
                v.add(rs.getString("TelephoneNo"));
                v.add(rs.getString("RegisterNo"));
                tablemodel.addRow(v);
            }

        } catch (SQLException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        supName = new app.bolivia.swing.JCTextField();
        supAddress = new app.bolivia.swing.JCTextField();
        supTeleNumber = new app.bolivia.swing.JCTextField();
        supRegisterNumber = new app.bolivia.swing.JCTextField();
        supButInsert = new javax.swing.JButton();
        supButEdit = new javax.swing.JButton();
        supButDelete = new javax.swing.JButton();
        supButCancel = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        supplierTable = new rojeru_san.complementos.RSTableMetro();
        supSearch = new app.bolivia.swing.JCTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setBackground(new java.awt.Color(26, 140, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("SUPPLIER");
        jLabel5.setOpaque(true);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        supName.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        supName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        supName.setPhColor(new java.awt.Color(0, 51, 255));
        supName.setPlaceholder("Name");
        supName.setPreferredSize(new java.awt.Dimension(200, 30));
        supName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                supNameKeyPressed(evt);
            }
        });

        supAddress.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Address", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        supAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        supAddress.setPhColor(new java.awt.Color(0, 51, 255));
        supAddress.setPlaceholder("Address");
        supAddress.setPreferredSize(new java.awt.Dimension(200, 30));
        supAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                supAddressKeyPressed(evt);
            }
        });

        supTeleNumber.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Telephone Number", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        supTeleNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        supTeleNumber.setPhColor(new java.awt.Color(0, 51, 255));
        supTeleNumber.setPlaceholder("Telephone Number");
        supTeleNumber.setPreferredSize(new java.awt.Dimension(200, 30));
        supTeleNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                supTeleNumberKeyPressed(evt);
            }
        });

        supRegisterNumber.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Register Number", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        supRegisterNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        supRegisterNumber.setPhColor(new java.awt.Color(0, 51, 255));
        supRegisterNumber.setPlaceholder("Register Number");
        supRegisterNumber.setPreferredSize(new java.awt.Dimension(200, 30));
        supRegisterNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                supRegisterNumberKeyPressed(evt);
            }
        });

        supButInsert.setBackground(new java.awt.Color(0, 60, 128));
        supButInsert.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        supButInsert.setForeground(new java.awt.Color(255, 255, 255));
        supButInsert.setText("INSERT");
        supButInsert.setBorder(null);
        supButInsert.setFocusPainted(false);
        supButInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supButInsertActionPerformed(evt);
            }
        });

        supButEdit.setBackground(new java.awt.Color(0, 60, 128));
        supButEdit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        supButEdit.setForeground(new java.awt.Color(255, 255, 255));
        supButEdit.setText("EDIT");
        supButEdit.setBorder(null);
        supButEdit.setFocusPainted(false);
        supButEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supButEditActionPerformed(evt);
            }
        });

        supButDelete.setBackground(new java.awt.Color(0, 60, 128));
        supButDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        supButDelete.setForeground(new java.awt.Color(255, 255, 255));
        supButDelete.setText("DELETE");
        supButDelete.setBorder(null);
        supButDelete.setFocusPainted(false);
        supButDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supButDeleteActionPerformed(evt);
            }
        });

        supButCancel.setBackground(new java.awt.Color(0, 60, 128));
        supButCancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        supButCancel.setForeground(new java.awt.Color(255, 255, 255));
        supButCancel.setText("CANCEL");
        supButCancel.setBorder(null);
        supButCancel.setFocusPainted(false);
        supButCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supButCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(supName, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                        .addComponent(supAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel11Layout.createSequentialGroup()
                            .addComponent(supButInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(supButEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(supButDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(supButCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(supRegisterNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(supTeleNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(supName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(supAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(supTeleNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(supRegisterNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supButInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supButEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supButDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supButCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        supplierTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Address", "Telephone No", "Register No"
            }
        ));
        supplierTable.setColorBackgoundHead(new java.awt.Color(26, 140, 255));
        supplierTable.setFuenteHead(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        supplierTable.setRowHeight(25);
        supplierTable.setRowMargin(0);
        supplierTable.setSelectionBackground(new java.awt.Color(0, 60, 128));
        supplierTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supplierTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(supplierTable);

        supSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        supSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        supSearch.setPhColor(new java.awt.Color(0, 51, 255));
        supSearch.setPlaceholder("Search");
        supSearch.setPreferredSize(new java.awt.Dimension(200, 30));
        supSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                supSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(supSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(supSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void supButInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supButInsertActionPerformed
        if (validateForm()) {
            String name = supName.getText();
            String address = supAddress.getText();
            String teleNumber = supTeleNumber.getText();
            String regNumber = supRegisterNumber.getText();

            String query = "INSERT INTO supplier(Name,Address,TelephoneNo,RegisterNo) VALUES('" + name + "','" + address + "','" + teleNumber + "'," + regNumber + ")";
            try {
                DbConnect.pushToDB(query);
            } catch (SQLException e) {
                e.printStackTrace();
            } catch (ClassNotFoundException e) {
                e.printStackTrace();
            } catch (Exception e) {
                e.printStackTrace();
            }
            clearSupPanel();
        } else {
            JOptionPane.showMessageDialog(null, "Form Validation Failed", "Validation Failed", 1);
        }
    }//GEN-LAST:event_supButInsertActionPerformed

    private void supButEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supButEditActionPerformed
        if (validateForm()) {
            String name = supName.getText();
            String address = supAddress.getText();
            String teleNumber = supTeleNumber.getText();
            String regNumber = supRegisterNumber.getText();

            String query = "UPDATE supplier set Name='" + name + "', Address='" + address + "',TelephoneNo='" + teleNumber + "',RegisterNo=" + regNumber + " WHERE Id=" + supplierId;
            try {
                DbConnect.pushToDB(query);
            } catch (SQLException e) {
                e.printStackTrace();
            } catch (ClassNotFoundException e) {
                e.printStackTrace();
            } catch (Exception e) {
                e.printStackTrace();
            }
            clearSupPanel();
        } else {
            JOptionPane.showMessageDialog(null, "Form Validation Failed", "Validation Failed", 1);
        }
    }//GEN-LAST:event_supButEditActionPerformed

    private void supButDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supButDeleteActionPerformed
        String query = "UPDATE supplier set Status=" + 0 + " where Id=" + supplierId;
        try {
            DbConnect.pushToDB(query);
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
        clearSupPanel();
    }//GEN-LAST:event_supButDeleteActionPerformed

    private void supButCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supButCancelActionPerformed
        clearSupPanel();
    }//GEN-LAST:event_supButCancelActionPerformed

    private void supplierTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierTableMouseClicked
        int selRow = supplierTable.getSelectedRow();
        supplierId = Integer.parseInt(supplierTable.getValueAt(selRow, 0).toString());

        supName.setText(supplierTable.getValueAt(selRow, 1).toString());
        supAddress.setText(supplierTable.getValueAt(selRow, 2).toString());
        supTeleNumber.setText(supplierTable.getValueAt(selRow, 3).toString());
        supRegisterNumber.setText(supplierTable.getValueAt(selRow, 4).toString());
    }//GEN-LAST:event_supplierTableMouseClicked

    private void supSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_supSearchKeyReleased
        String query = "SELECT * from supplier WHERE Name LIKE '%" + supSearch.getText().toString() + "%' and Status=1";
        fillSupTable(query);
    }//GEN-LAST:event_supSearchKeyReleased

    private void supNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_supNameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (Validate.isText(supName.getText().toString())) {
                supAddress.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Not Text", "Validation Failed", 1);
            }
        }         // TODO add your handling code here:
    }//GEN-LAST:event_supNameKeyPressed

    private void supAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_supAddressKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (Validate.isText(supAddress.getText().toString())) {
                supTeleNumber.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Not Text", "Validation Failed", 1);
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_supAddressKeyPressed

    private void supTeleNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_supTeleNumberKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (Validate.isTelephone(supTeleNumber.getText().toString())) {
                supRegisterNumber.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Not Text", "Validation Failed", 1);
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_supTeleNumberKeyPressed

    private void supRegisterNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_supRegisterNumberKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (Validate.isText(supRegisterNumber.getText().toString())) {
                supButInsert.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Not Text", "Validation Failed", 1);
            }
        }         // TODO add your handling code here:
    }//GEN-LAST:event_supRegisterNumberKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JScrollPane jScrollPane1;
    private app.bolivia.swing.JCTextField supAddress;
    private javax.swing.JButton supButCancel;
    private javax.swing.JButton supButDelete;
    private javax.swing.JButton supButEdit;
    private javax.swing.JButton supButInsert;
    private app.bolivia.swing.JCTextField supName;
    private app.bolivia.swing.JCTextField supRegisterNumber;
    private app.bolivia.swing.JCTextField supSearch;
    private app.bolivia.swing.JCTextField supTeleNumber;
    private rojeru_san.complementos.RSTableMetro supplierTable;
    // End of variables declaration//GEN-END:variables
}
