/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.xpos.gui;

import com.xpos.database.DbConnect;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import com.xpos.commons.Validate;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Jamit
 */
public class User extends javax.swing.JPanel {

    DefaultTableModel tablemodel;
    DateTimeFormatter defaultDateFormat = DateTimeFormatter.ofPattern("yyyy-MM-dd");

    int brandId;

    /**
     * Creates new form Brand
     */
    public User() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        userProButInsert = new javax.swing.JButton();
        userProButEdit = new javax.swing.JButton();
        userProButDelete = new javax.swing.JButton();
        userProButCancel = new javax.swing.JButton();
        userProUsername = new app.bolivia.swing.JCTextField();
        jPanel19 = new javax.swing.JPanel();
        userProActive = new javax.swing.JRadioButton();
        userProNotActive = new javax.swing.JRadioButton();
        userProEmployeeCombo = new javax.swing.JComboBox<>();
        userProPassword = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setBackground(new java.awt.Color(26, 140, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("USER");
        jLabel6.setOpaque(true);

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));

        userProButInsert.setBackground(new java.awt.Color(0, 60, 128));
        userProButInsert.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        userProButInsert.setForeground(new java.awt.Color(255, 255, 255));
        userProButInsert.setText("INSERT");
        userProButInsert.setBorder(null);
        userProButInsert.setFocusPainted(false);
        userProButInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userProButInsertActionPerformed(evt);
            }
        });

        userProButEdit.setBackground(new java.awt.Color(0, 60, 128));
        userProButEdit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        userProButEdit.setForeground(new java.awt.Color(255, 255, 255));
        userProButEdit.setText("EDIT");
        userProButEdit.setBorder(null);
        userProButEdit.setFocusPainted(false);
        userProButEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userProButEditActionPerformed(evt);
            }
        });

        userProButDelete.setBackground(new java.awt.Color(0, 60, 128));
        userProButDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        userProButDelete.setForeground(new java.awt.Color(255, 255, 255));
        userProButDelete.setText("DELETE");
        userProButDelete.setBorder(null);
        userProButDelete.setFocusPainted(false);
        userProButDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userProButDeleteActionPerformed(evt);
            }
        });

        userProButCancel.setBackground(new java.awt.Color(0, 60, 128));
        userProButCancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        userProButCancel.setForeground(new java.awt.Color(255, 255, 255));
        userProButCancel.setText("CANCEL");
        userProButCancel.setBorder(null);
        userProButCancel.setFocusPainted(false);
        userProButCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userProButCancelActionPerformed(evt);
            }
        });

        userProUsername.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Username", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        userProUsername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        userProUsername.setPhColor(new java.awt.Color(0, 51, 255));
        userProUsername.setPreferredSize(new java.awt.Dimension(200, 30));

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Is Active", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N

        userProActive.setBackground(new java.awt.Color(255, 255, 255));
        userProActive.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        userProActive.setForeground(new java.awt.Color(26, 140, 255));
        userProActive.setSelected(true);
        userProActive.setText("Active");

        userProNotActive.setBackground(new java.awt.Color(255, 255, 255));
        userProNotActive.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        userProNotActive.setForeground(new java.awt.Color(26, 140, 255));
        userProNotActive.setText("Not-Active");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userProActive)
                .addGap(18, 18, 18)
                .addComponent(userProNotActive)
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userProActive)
                    .addComponent(userProNotActive))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        userProEmployeeCombo.setForeground(new java.awt.Color(26, 140, 255));
        userProEmployeeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Employee" }));
        userProEmployeeCombo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Select Employee", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N
        userProEmployeeCombo.setOpaque(false);

        userProPassword.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 140, 255)), "Default Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(26, 140, 255))); // NOI18N

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userProPassword)
                    .addComponent(jPanel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userProUsername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userProEmployeeCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel18Layout.createSequentialGroup()
                        .addComponent(userProButInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(userProButEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(userProButDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(userProButCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userProEmployeeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userProUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userProPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userProButInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userProButEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userProButDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userProButCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(464, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(996, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void userProButInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userProButInsertActionPerformed
//        int employeeId = Integer.parseInt(userProEmployeeCombo.getSelectedItem().toString().split(" - ")[0]);
//        String username = userProUsername.getText();
//        String password = MD5.getMd5(new String(userProPassword.getPassword()));
//        boolean active = userProActive.isSelected() ? true : false;
//
//        String query = "INSERT INTO `userprofile`(`Employee_Id`, `Username`, `Password`, `Status`) VALUES (" + employeeId
//        + ",'" + username + "','" + password + "'," + active + ")";
//        try {
//            DbConnect.pushToDB(query);
//            clearUserProPanel();
//        } catch (SQLException e) {
//            e.printStackTrace();
//        } catch (ClassNotFoundException e) {
//            e.printStackTrace();
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_userProButInsertActionPerformed

    private void userProButEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userProButEditActionPerformed
//        int employeeId = Integer.parseInt(userProEmployeeCombo.getSelectedItem().toString().split(" - ")[0]);
//        String username = userProUsername.getText();
//        String password = MD5.getMd5(new String(userProPassword.getPassword()));
//        boolean active = userProActive.isSelected() ? true : false;
//
//        String query = null;
//
//        if (password.equals("d41d8cd98f00b204e9800998ecf8427e")) {
//            query = "UPDATE `userprofile` SET `Employee_Id`=" + employeeId + ",`Username`='" + username
//            + "',`Status`=" + active + " WHERE Id=" + userProId;
//        } else {
//            query = "UPDATE `userprofile` SET `Employee_Id`=" + employeeId + ",`Username`='" + username
//            + "',`Password`='" + password + "',`Status`=" + active + " WHERE Id=" + userProId;
//        }
//        try {
//            DbConnect.pushToDB(query);
//            clearUserProPanel();
//        } catch (SQLException e) {
//            e.printStackTrace();
//        } catch (ClassNotFoundException e) {
//            e.printStackTrace();
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_userProButEditActionPerformed

    private void userProButDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userProButDeleteActionPerformed
//        String query = "UPDATE `userprofile` SET `Status`=0 WHERE Id=" + userProId;
//        try {
//            DbConnect.pushToDB(query);
//            clearUserProPanel();
//        } catch (SQLException e) {
//            e.printStackTrace();
//        } catch (ClassNotFoundException e) {
//            e.printStackTrace();
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_userProButDeleteActionPerformed

    private void userProButCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userProButCancelActionPerformed
        //clearUserProPanel();
    }//GEN-LAST:event_userProButCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JRadioButton userProActive;
    private javax.swing.JButton userProButCancel;
    private javax.swing.JButton userProButDelete;
    private javax.swing.JButton userProButEdit;
    private javax.swing.JButton userProButInsert;
    private javax.swing.JComboBox<String> userProEmployeeCombo;
    private javax.swing.JRadioButton userProNotActive;
    private javax.swing.JPasswordField userProPassword;
    private app.bolivia.swing.JCTextField userProUsername;
    // End of variables declaration//GEN-END:variables
}
